### ISSUE TITLE
PRs defasados

### ISSUE THREAD

**Issue by williamespindola** [portabilis/i-educar#200]
Vi que todos os Pull Requests abertos são de 2015, ainda será feito merge deles?

**Comment by farribeiro** [comment]
Mover essa discussão para o Slack, e de preferência no repo comunitário. Lá te responderei

**Comment by nawarian** [comment]
@farribeiro por favor dê uma olhada aqui: https://github.com/portabilis/i-educar/pull/203

**Comment by farribeiro** [comment]
Closes #200
