### ISSUE TITLE
[Votação] Adicionar integração com Travis CI

### ISSUE THREAD

**Issue by nawarian** [portabilis/i-educar#208]
Gostaria de abrir para discussão a proposta de @farribeiro.

Basicamente adicionaríamos o Travis CI para rodar testes unitários primeiramente, com o tempo poderia ser evoluído.

Travis CI é uma ferramenta gratuita para projetos Open Source, mais detalhes aqui: https://travis-ci.org/

Por favor dêem seus 👍  ou 👎

**Comment by williamespindola** [comment]
Acho que nem precisa de votação para isto travis e para rodar os testes e scrutinizer para análise ciclomática, coverage e também testes. São ferramentas gratuitas para projetos open source e excelentes.

Usamos no respect, se quiserem ver como funcionar:
- [scrutinizer config](https://github.com/Respect/Validation/blob/1.1/.scrutinizer.yml) - [veja rodando](https://scrutinizer-ci.com/g/Respect/Validation/)
- [travis config](https://github.com/Respect/Validation/blob/1.1/.travis.yml) - [veja rodando](https://travis-ci.org/Respect/Validation)

No skeleton do The php League também tem também se quiserem comparar as configurações para ver como rola https://github.com/thephpleague/skeleton

**Comment by nawarian** [comment]
Massa. Acha que você consegue tocar isso @farribeiro?

**Comment by farribeiro** [comment]
Aí @nawarian

**Comment by MarceloCajueiro** [comment]
Acho bem válido, mas para isso temos que começar a cobrir com testes aos poucos, até para termos certeza que vamos conseguir refatorar o que está ruim.

**Comment by MarceloCajueiro** [comment]
Travis ativado: https://travis-ci.org/portabilis/i-educar

Basta termos a build com algum teste rodando ;)

**Comment by farribeiro** [comment]
Tá inacabada... mas podem fazer o review até o ponto?

**Comment by MarceloCajueiro** [comment]
scrutinizer: https://scrutinizer-ci.com/g/portabilis/i-educar/

**Comment by farribeiro** [comment]
Geração de ambiente e pacotes e só

**Comment by MarceloCajueiro** [comment]
Já que está configurado, vou fechar.
