### ISSUE TITLE
[Votação] Criar imagem no DockerHUB

### ISSUE THREAD

**Issue by nawarian** [portabilis/i-educar#209]
Gostaria de abrir para discussão a proposta de @farribeiro.

Refere-se a criar uma imagem docker já preparada com o ambiente i-educar, pronta para ser utilizada.
A primeira proposta refere-se à imagem como `portabilis/i-educar`. O nome também está aberto para discussão.

Favor adicionar seus 👍 ou 👎 e comentar em caso de solicitação de alterações.

**Comment by williamespindola** [comment]
Vai ser algo como deploy imutável com a imagem do docker? Gosto bastante!
Só não sei como funciona a instalação nas escolas o @MarceloCajueiro pode nos dizer como funcionar, pois dependendo como for o docker só vai rolar pra gente desenvolver, ai só um docker-compose basta.

**Comment by farribeiro** [comment]
@williamespindola A aplicação quando fechado release é imutável... não é necessário nem de volume

**Comment by williamespindola** [comment]
@nawarian faz sim. Confundi uma coisa aqui e deixa eu concertar rapidinho.

Dois casos diferentes: **imagem para stack**, **imagem para deploy**.

**Imagem para stack** seria uma imagem com o ambiente pronto e assim teria mos um docker-compose de dev com algumas coisas para dev como por exemplo xdebug e outro docker-compose para prod

**imagem para deploy** seria uma imagem com toda a aplicação rodando com aquele docker-compose de produção e esta imagem inteira seria feito o deploy. Este seria o imutável e depende de como o deploy do projeto funciona.

@farribeiro saquei este seria o caso da imagem de deploy que falei aqui. 
Só um detalhe sobre os volumes, ok em dev não ter, mas em prod se não tiver se mater os containers tudo é reiniciado e dados de banco e arquivos são excluídos. Saca?

**Comment by farribeiro** [comment]
Isso ficará a cargo do responsável do repositório.

Aguardando PR #207

**Comment by williamespindola** [comment]
@farribeiro vou comentar aqui sobre o PR #210 pois seria a maneira com ele ele poderia ser implementado. 

Eu entendi o target la, esta certo, mas não seria com mais um Dockerfile. Neste caso usaria-mos esta **imagem de stack** para fazer isto. Ou seja, a stack onde os teses estão rodando é a mesma usada para desenvolvimento e produção (caso evolua para isto).
Configuramos no travis assim https://docs.travis-ci.com/user/docker/#Using-Docker-Compose
E depois rodamos um docker run.

**Comment by farribeiro** [comment]
Para a imagem DockerHUB utilizar a PR #207

**Comment by farribeiro** [comment]
A saber... https://hub.docker.com/r/farribeiro/i-educar/builds/

**Comment by farribeiro** [comment]
Link #232

**Comment by farribeiro** [comment]
A imagem foi encerrada, não havendo possibilidade no momento de ofertar ao público usuário esta opção
