### ISSUE TITLE
Corrigir permissões de arquivos

### ISSUE THREAD

**Issue by farribeiro** [portabilis/i-educar#212]
Por gentileza revisar as permissões de arquivos e pastas. Para padronização

Existem bastantes arquivos com permissões diferentes ao default (`644`) como CSS por exemplo e soluciona-se este problema dessa seguinte maneira no raiz do projeto:

```
git:master [fribeiro@localhost ~/i-educar]$ find . -type f -exec chmod 644 {} \;
git:master [fribeiro@localhost ~/i-educar]$ find . -type d -exec chmod 755 {} \;
```

**Comment by farribeiro** [comment]
Quero aproveitar para que ou @MarceloCajueiro ou @giustin apagarem os branches que já foram "megeados", tal como o branch `master-3`

**Comment by MarceloCajueiro** [comment]
Não entendi.

**Comment by farribeiro** [comment]
Abre a lista de branches

**Comment by MarceloCajueiro** [comment]
Já foram apagados, só tem branches importantes.

**Comment by farribeiro** [comment]
Obrigado, @MarceloCajueiro !

Porém a PR referente a esse issue continua

**Comment by farribeiro** [comment]
Continua #213
