### ISSUE TITLE
Uso do CDNJS

### ISSUE THREAD

**Issue by farribeiro** [portabilis/i-educar#216]
Será uma boa opção de retirar o jquery e usá-lo via cdnjs?

**Comment by MarceloCajueiro** [comment]
Se for a versão usada para não quebrar, sim, faz sentido.

**Comment by farribeiro** [comment]
Cria um branch pra quebrar

**Comment by MarceloCajueiro** [comment]
Não entendi.

**Comment by JDias** [comment]
Eu sou contra o uso de cdn, pois nem toda escola tem acesso a Internet, mas sim, a ideia de usar branchs é exatamente essa, poder quebrar as coisas 😊

**Comment by farribeiro** [comment]
A ideia é trazer a mais fresca ferramenta ao projeto

**Comment by JDias** [comment]
não sou contra atualizar nada @farribeiro , só acho que o sistema tem que ser compatível com cenários sem Internet (que por sinal é diferente de internet :) )

**Comment by farribeiro** [comment]
Nenhum dos dois necessitam de acesso a internet, embora como dependências e não como parte do projeto

**Comment by MarceloCajueiro** [comment]
O sistema é web, independente da solução de escolha do jquery, vai precisar de internet. Essa solução não funciona offline. O CDN deixa o sistema mais rápido.

Agora, se você pretende rodar o sistema em intranet, aí faz sentido não usar CDN.

**Comment by farribeiro** [comment]
A cdn não tem finalidade de entregar no lugar mais perto possível e também o framework mais recente

**Comment by MarceloCajueiro** [comment]
Esse sistema é web, não funciona offline, logo, CDN é uma ótima opção. Mas como eu disse, tem que garantir a versão atual para não quebrar o que depende dela.

**Comment by JDias** [comment]
@MarceloCajueiro um sistema web, como o sr mesmo disse, pode funcionar numa "intranet" ...
nada impede de uma escola ter uma rede de computadores tcp/ip (internet) e não ter conexão wlan (Internet), acho.

Se o sr for trabalhar com algo como webpack, o sr pode importar via npm i package --save e depois "build" dist files para a produção, acho.

**Comment by JDias** [comment]
@farribeiro do pouco que eu vi:
1- cdn ninguém mais usa em produção. (quem vai colocar "latest" como opção de produção?)
2-jquery tbm esta saindo fora, bem como seus plugins

eu tenho usado o npm, apesar de ter outras opções como bower ou yarn, acho, invés de trabalhar com os arquivos de dist dos outros, o sr. trabalha com o source e faz sua própria build, pelo que eu entendi.

por exemplo misturando todos js em um único arquivo e minificando.
dessa forma seu javascript se torna apenas 1 requisição, e não varias.

**Comment by farribeiro** [comment]
Cdnjs tem os arquivos @JDias

**Comment by JDias** [comment]
ok @farribeiro , vocês são livres para escolher as abordagens que acharem mais conveniente, dei uma opinião, mas realmente não é essa cereja de bolo que vai fazer diferença.

A gente tem toda a eternidade para deixar o i-educar modernoso!

**Comment by farribeiro** [comment]
Perguntar, não há como fazer um selector ou mesmo já começar a usar o CDNJS?

**Comment by eberfreitas** [comment]
Tô aqui pensando no racional da gente usar um CDN pros assets. O CDN é bacana porque:

1. Distribui o fornecimento dos arquivos pra mais perto do usuário, deixando o carregamento mais rápido;
2. Eventualmente permite o upgrade "automágico" das versões das bibliotecas.

Eu não vejo muita vantagem no ponto 1 já que não temos uma base de usuários espalhadas pelo mundo e, uma vez baixado o arquivo, ele deve ir pro cache do browser. Não vejo a utilização do script no servidor original como um problema de performance que precise ser resolvido.

O segundo ponto é mais interessante. A gente tem automaticamente as versões mais recentes com os últimos bug fixes. Ao mesmo tempo pode ser algo meio instável, se testarmos nossos scripts com uma versão específica e rolar alguma regressão...

Fico bem em dúvida se vale realmente a pena discutir mais sobre o assunto.

**Comment by farribeiro** [comment]
Fechando pois está desgastando a paciência
