### ISSUE TITLE
Sobre mudanças cosméticas

### ISSUE THREAD

**Issue by eberfreitas** [portabilis/i-educar#218]
Acho interessante integrarmos ao guia de contribuição alguma política a respeito de PRs totalmente cosméticos com base nas políticas do Ruby on Rails:

https://github.com/rails/rails/blob/master/CONTRIBUTING.md#did-you-fix-whitespace-format-code-or-make-a-purely-cosmetic-patch

**Comment by williamespindola** [comment]
Tem dois lados esta história um lado é o programador que não tem experiência ou tem medo e quer contribuir e o outro é o caroço, só quer ter um PR aprovado para falar que contribui. É bem complicado lidar com isto, a melhor forma é um dialogo, se alguém fez um PR "cosmético" falar que aquela contribuição não ajuda e se ele pode ajudar com alguma outra coisa, e que nós podemos ajudar ele a entender um problema real e trabalhar nele.
Uma boa pratica e adicionar tags nas issues como `easy-pick` `help-wanted` ja ajuda a guiar.

**Comment by MarceloCajueiro** [comment]
Concordo com o @williamespindola.

@eberfreitas acho que o i-Educar ainda tem muito problema com falta de padrão, e até lá, PRs cosméticos, dependendo do objetivo, pode ser bom.

**Comment by farribeiro** [comment]
Eu gostaria de lançar uma PR cosmética, rebaixando o nível do diretório `ieducar` para a raiz do projeto, não há necessidade de manter dentro de tal diretório

**Comment by MarceloCajueiro** [comment]
Realmente @eberfreitas. Vou fechar esse PR. Do jeito que foi escrito, nos atende super bem.
