### ISSUE TITLE
receive commit email notification

### ISSUE THREAD

**Issue by JDias** [portabilis/i-educar#220]
opiniões?

https://help.github.com/articles/choosing-the-types-of-notifications-you-receive/

**Comment by JDias** [comment]
como assim @farribeiro ?
o matrix.org é um projeto bem legal, mas como o sr faz para receber os emails dos commits do i-educar?

**Comment by farribeiro** [comment]
Não emails... sim mensagens de notificação... Ele também tem um monte de integrações legais... IRC, slack, gitter, github (para algumas funcões de issues/comentários), telegram e  discord

**Comment by JDias** [comment]
uau, parece bem "porradão"

o melhor que eu tinha era https://github.com/portabilis/i-educar/commits/master.atom

mas eu acredito que ter um mailing list com os commits seria melhor que usar 3rd party rss2mail.

eu tenho recebido numa boa os follow-ups das issues, mas não os commits. (eu consigo saber o que está acontecendo pq vcs estão vinculando os commits nas issues, mas se não comentarem não vai funcionar.

**Comment by farribeiro** [comment]
O meu usuário IRC fica on direto pela matrix... E não é bouncer

**Comment by farribeiro** [comment]
![image](https://user-images.githubusercontent.com/198756/41209122-ccd16dc0-6cff-11e8-88b1-6c6a699ff3ac.png)
![image](https://user-images.githubusercontent.com/198756/41209140-de25cd6e-6cff-11e8-99f4-18f680fa210f.png)
![image](https://user-images.githubusercontent.com/198756/41209146-f00dafd8-6cff-11e8-8343-2f7987317413.png)
![image](https://user-images.githubusercontent.com/198756/41209154-fccd2f0a-6cff-11e8-9d19-9d8b9e91c27a.png)

**Comment by farribeiro** [comment]
Os `master` que ando seguindo...
![image](https://user-images.githubusercontent.com/198756/41209290-f5e96a04-6d00-11e8-862f-e977bc50f890.png)

Ia transcrever mas tá na cara.

**Comment by JDias** [comment]
legal, vou testar. :)

**Comment by farribeiro** [comment]
Sabe o que é mais legal? Ela tem funcionamento semelhante ao email... cada um pode ter o seu servidor e tb pode ser distribuída

**Comment by JDias** [comment]
legal, eu não conhecia o ring.cx ... vamos acompanhando! :)

**Comment by JDias** [comment]
o sr integrou o slack do i-educar com a sala do i-educar na freenode @farribeiro ?

**Comment by farribeiro** [comment]
No... trouble na integração

**Comment by farribeiro** [comment]
Sem canal nenhum, como eu gostaria no passado, mas felizmente precisamos de OT

**Comment by JDias** [comment]
?!?!

**Comment by farribeiro** [comment]
IRC... Now

**Comment by MarceloCajueiro** [comment]
Galera, vou fechar pois está fora do escopo do projeto essa discussão. O Github já dá ferramentas suficientes para acompanhar o projeto.

**Comment by farribeiro** [comment]
Ele pediu para configurar as notificações do github para os membros, enfim...

**Comment by MarceloCajueiro** [comment]
thanks @farribeiro
