### ISSUE TITLE
Acompanhamento do status do projeto

### ISSUE THREAD

**Issue by JDias** [portabilis/i-educar#223]
Alguém saberia dizer quantas classes, métodos/funções e rotas o i-educar possui?
eu acho que poderias ser interessante fazer esse levantamento e gerar um relatório similar a este:

http://aros.sourceforge.net/documentation/developers/roadmap.php

aonde poderíamos ter uma visão melhor em relação ao que foi feito e ao que precisa ser feito. opiniões?

**Comment by JDias** [comment]
eu acredito que o doxygen/phpdoc poderá auxiliar em relação as classes (apesar de não saber se estão todas documentadas, já seria um ponto de partida.
quanto as rotas, antigamente existiam crawlers que mapeavam todos os links de um site, talvez sirva como um ponto de partida.

**Comment by MarceloCajueiro** [comment]
@JDias realmente precisamos da visão que você citou, sobre o roadmap. Em breve vamos lançar algo a respeito.

Quanto a número de classes e rotas, não é relevante, na minha opinião. Se você quiser fazer essa contagem de alguma forma, fique a vontade, mas não creio que terá alguma efetividade em algo.

**Comment by JDias** [comment]
olá @MarceloCajueiro falei da contagem pois seria uma forma de medir o andamento, o sr saberia dizer alguma outra forma de mensurar o andamento do projeto? (mas ter milestones, como as apresentadas já é uma abordagem. será 0 ou 1. o que tentei foi graduar para 0 a 100)
