### ISSUE TITLE
Anuncio para canal de suporte para instalação e off topic

### ISSUE THREAD

**Issue by farribeiro** [portabilis/i-educar#225]
Anunciar no github da portabilis canal de suporte para instalação e off topic para o projeto i-educar...

canal ##i-educar na freenode

**Comment by 50tarcisiopieroni** [comment]
@farribeiro Qual seria o objetivo de grupo?

**Comment by farribeiro** [comment]
Suporte comunidade e off topic

**Comment by farribeiro** [comment]
Deixar este canal para os devs

**Comment by JDias** [comment]
seria interessante levantar um forum? que poderia ser linkado com o canal.
se a portabilis não quiser fazer o deploy eu posso fazer em um outro host, mas no futuro seria interessante linkar o i-educar com o forum, acho.

https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md

**Comment by farribeiro** [comment]
Perdi contatos dev e users tanto para fins OT e suporte de instalação

**Comment by JDias** [comment]
ilustrando:

https://meta.discourse.org/t/using-discourse-to-host-a-knowledge-base/34036

https://meta.discourse.org/t/using-discourse-as-a-internal-knowledge-base-intranet/33857?source_topic_id=34036

**Comment by farribeiro** [comment]
Perdi contatos dev e users tanto para fins OT e suporte de instalação

**Comment by farribeiro** [comment]
https://t.me/joinchat/H0oCkwxA-GoRZ9SrNQgvkg

**Comment by eberfreitas** [comment]
@JDias o forum está nos planos, defintivamente, e deve ser o canal oficial para suporte e outras coisas. Sendo assim, por enquanto não devemos endossar oficialmente nenhum outro canal de comunicação. Confirma pra mim @MarceloCajueiro ?

**Comment by 50tarcisiopieroni** [comment]
Concordo @eberfreitas, melhor esperar para que seja possível uma forma oficial, se não desfoca.

**Comment by 50tarcisiopieroni** [comment]
@farribeiro Já existe um grupo no telegram do I-Educar, não sei qual o status.

**Comment by farribeiro** [comment]
Gentileza me redirecionar a esse usergroup

**Comment by farribeiro** [comment]
@50tarcisiopieroni Até o momento o usergrup no telegram se mostrou eficiente... reunimos 6 membros da comunidade.

Ainda acredito que o IRC é uma boa aposta.

**Comment by JDias** [comment]
Com o matrix, você pode ter todos transparente, não precisa escolher entre um ou outro, acho.

**Comment by MarceloCajueiro** [comment]
Exato @eberfreitas. A comunidade não vai ter chat de discussão oficial por enquanto. Vamos usar as issues para assuntos específicos com o objetivo de elevar o level do i-Educar.

**Comment by farribeiro** [comment]
Não me respondeu meu questionamento.

**Comment by farribeiro** [comment]
O usergroup ativo é de minha iniciativa.

**Comment by farribeiro** [comment]
Tem o canal pago, mas nada supera um usergroup!

**Comment by farribeiro** [comment]
Uma leitura rápida a respeito do papel do usergroup

https://pt.wikipedia.org/wiki/Lei_de_Linus

**Comment by 50tarcisiopieroni** [comment]
@farribeiro foi adicionado no README.md o link para o grupo do Telegram Link: t.me/ieducar

**Comment by farribeiro** [comment]
> @farribeiro foi adicionado no README.md o link para o grupo do Telegram Link:

Adentrei ao grupo... Obrigado.

**Comment by giustin** [comment]
Olá, pessoal! Tudo bem?

Obrigado pela discussão aqui. Achamos super válida a comunicação entre os membros, mas queremos trabalhar para evitar a desintegração entre todos os membros, com atuações em diferentes canais. 

Sofremos uma perda gigante de membros quando a versão do Portal do SPB foi virada de formato com Fórum para Lista de discussão. Queremos evitar problemas assim de troca de ambientes ou ambientes que não concentrem todo mundo.

Como anunciamos na live da lançamento oficial ([nestes minutos aqui](https://youtu.be/1C3473KxIeM?t=2599)), em breve teremos ferramentas melhores para nos comunicar. Nós queremos muito isso também, mas agora estamos em processo desta transição e a compreensão de vocês é muito importante para este momento que estamos passado com o projeto.

Constatei que o grupo do Telegram estava configurado para entrar apenas com convite ou por meio do link. Resolvido imediatamente e agora ele é totalmente público. Beleza galera? 

O link já foi referenciado pelo @MarceloCajueiro em [uma entrada no readme sobre comunicação.](https://github.com/portabilis/i-educar#comunicacao)

Abs!

**Comment by farribeiro** [comment]
Agora entendi por que não localizava o grupo no telegram... GRUPO FECHADO
