### ISSUE TITLE
Banco para demonstração

### ISSUE THREAD

**Issue by farribeiro** [portabilis/i-educar#226]
Por gentileza poderia nos ceder um backup de um banco já populado/seed (com dados) para demonstração?

Agradecemos
Geraldo Júnior e comunidade

**Comment by geraldorodrigues** [comment]
E se possível um tutorial para restaurá-lo no docker...

Grato

**Comment by farribeiro** [comment]
Seria o mesmo esquema se estive restaurando no metal... vc pode dar um `docker exec -it` como o comando pgrestore ou chamar um bash e executar

**Comment by MarceloCajueiro** [comment]
Vamos providenciar em breve. Ajuda muito a testar o software.

**Comment by farribeiro** [comment]
Fechando pois está desgastando a paciência

**Comment by msoares94** [comment]
@MarceloCajueiro, alguma evolução nessa solicitação?

**Comment by edersoares** [comment]
@marcosoliveirasoares94 atualmente não foi criado um banco de demonstração, internamente a Portabilis está utilizando de factories https://laravel.com/docs/eloquent-factories para criar dados randômicos.

Todas as factories estão em https://github.com/portabilis/i-educar/tree/2.8/database/factories.

Vamos fechar esta issue por hora mas se a comunidade entender que é um esforço que podem executar podemos reabri-la.

**Comment by msoares94** [comment]
@edersoares, obrigado!

Só uma dúvida, utilizando o que mencionou a Portabilis está obtendo sucesso na construção de ambientes com dados fakes, se sim, posso usar os link para montar algo para a Comunidade.

**Comment by edersoares** [comment]
@marcosoliveirasoares94 nós usamos nos cenários de testes automatizados que criamos e tem funcionado muito bem. Para demonstrações o time cria dados manualmente.

**Comment by msoares94** [comment]
Show! Entendi! Vou adicionar isso na minha lista de itens para fazer!
Atualmente estou focado na liberação da automação ansible para a versão 2.7 para a Comunidade!

**Comment by edersoares** [comment]
Solução alternativa https://github.com/portabilis/i-educar/pull/913.
