### ISSUE TITLE
Auth system

### ISSUE THREAD

**Issue by JDias** [portabilis/i-educar#228]
Bom, como a minha idéia de começar pelo framework não vingou, e a camada de autorização já está funcionando, vou direto ao que mais provavelmente me interessa: Roles.

Existe algum plano para adicionar os alunos como usuários do sistema?  (Acredito que todos devem ser users)

**Comment by farribeiro** [comment]
Parece que eles tem algo para liberar até novembro, algo interessante, não me recordo o que

**Comment by JDias** [comment]
eles devem ter algo já pronto (pois a versão non-free tinha acesso de aluno, pelo que eu saiba), talvez via API? não sei, mas são dois pontos que especificamente me interessariam. roles e API.

eles já tem o multi tenacy (multi escolas), o que é bom! :)

**Comment by MarceloCajueiro** [comment]
Olá!

O i-Educar é um sistema de gestão e não teremos login para alunos.

Vamos lançar até novembro o Diário, que tem integração com o i-Educar, mas não usa a mesma base de usuário pois o i-Educar é para gestão, o Diário é para professores. Cada um acessa um sistema.

Mas podemos pensar num modelo de usuário único com roles.

@JDias Você já trabalhou com isso? Pode contar mais?

**Comment by JDias** [comment]
Não, não trabalhei. Mas acredito mais ou menos o usuario final, que é o aluno, e todos os envolvidos, progessores, pais.

Então se uma cidade do interior utilizar o i-educar, poderá ter um local unificado de dados.

O i-educar poderia integrar com o google, usado por varias redes de educação, lms, lor.

E o próprio ecossistema da lemann como o portal qedu e uma rede que eles tem para executivos da educação... acho que tem espaço para muita coisa.

**Comment by MarceloCajueiro** [comment]
Tem sim. Você pode desenhar uma arquitetura pra gente avaliar e fazer algo em conjunto?

**Comment by JDias** [comment]
ola @MarceloCajueiro acho que falar em arquitetura nesse momento seria precipitado.
Vou começar a colocar nas issues sugestões que fiz ao longo dos últimos anos para se ter a visão geral, algumas são mais outras menos relacionadas ao i-educar.

Mas acho que o mais importante nesta issue é sedimentar o conceito foco no usuário, o maior ativo no i-educar são suas 80 escolas e não sei quantos alunos.

Você poder estar no celular do aluno aumenta e muito o "poder" do i-educar, conseguir convencer de que o aluno ter login é algo importante já valeu esta issue. eu posso elaborar, mas acho que vai ficar mais claro a medida que eu for abrindo as issues.

Vou revisitar essa issue depois, para ver se conseguimos resumir e avançar.

**Comment by eberfreitas** [comment]
Eu só não entendi essa questão do aluno. Atualmente o i-Educar não entrega nenhum valor pro aluno diretamente pelo que eu entendo. Qual seria a vantagem dele ter login hoje?

Não seria o caso de pensarmos quais os problemas dos alunos que o i-Educar poderia resolver? Também teríamos que ver se faz sentido, se está no escopo do i-Educar resolver estes problemas.

Ainda assim, nosso foco atual não está no desenvolvimento de novos recursos. Enquanto não tivermos a base modernizada, acho que não vale muito a pena tentar implementar coisas novas assim.

Ou talvez eu que não entendi a proposta dessa issue :joy:

**Comment by JDias** [comment]
olá @eberfreitas excelente colocação!
Exatamente, o i-educar não oferece nada para o usuário final, e isso é triste, eu vou colocar umas issues de problemas que o i-educar poderia resolver, e vai nos trazer ao debate que tivemos antes, sobre os problemas que o i-educar tem.

Se achar que está fora do escopo, que ao menos permita que terceiros utilizem a estrutura do i-educar, que são os registros dos aluno (API).

**Comment by eberfreitas** [comment]
"..., o i-educar não oferece nada para o usuário final..."

O i-Educar oferece **muito** pro usuário final! O usuário final do i-Educar são gestores, secretários e professores, pelo menos no momento. Neste sentido muito é oferecido. Olha só a ferramenta do censo! É incrível pro usuário final.

E é claro que podemos agregar o aluno como mais um tipo de usuário final. Agora a gente tem que se perguntar: quais são os problemas que os alunos tem e que o i-Educar poderia resolver? Isso pra mim é o principal e deveria ser a principal questão dessa discussão (eu acho).

**Comment by geraldorodrigues** [comment]
No município onde trabalho o sistema agrega tanto o login de alunos, pais, professores, supervisores etc no sistema. Os dados inerentes a alunos e pais seriam a visualização de freqüência e notas no que se refere atualmente ao sistema i-educar para conferência e acompanhamento da situação do aluno. É muito útil aos pais pois estes teriam vistas ao desempenho dos filhos etc... Ainda mais no momento atual que a conectividade está em todo local. 

Ainda sobre esse assunto, imagino que o desenvolvimento do i-educar deve abranger mais que a gestão administra da escola, deve abranger a gestão pedagógica também.

**Comment by JDias** [comment]
desculpe @eberfreitas quando me referi ao "usuario final" é pq na educação o usuário final é o aluno e o serviço é a aprendizagem.

O i-educar é a "secretaria do colégio", eu diria que o i-educar poderia fornecer serviços como:

- boletim escolar
- gestão democrática 
- gestão de grêmio (que considero parte da gestão democrática)
- um canal de aviso para qualquer informação que o aluno/pai precise receber (colocar envio de sms?)
- cantina
- biblioteca (aqui da para abrir uns 3 tipos de funcionalidades diferentes)
- acompanhamento de rota de ônibus

e não tanto relacionado:
- integração com a google (para login e agenda)
- integração com o LMS (aqui é aonde o rocknroll ocorre, então um single sign-on seria útil, mas talvez o pessoal da lemann tenha até interesse em colocar suas próprias iniciativas como o qeduprovas e o geekie)

**Comment by eberfreitas** [comment]
Pessoal, isso tudo é muito legal e realmente faz todo sentido. Acho super legal termos login pros alunos e poder mostrar boletins e conteúdos pedagógicos, etc...

Mas eu fico dividido em integrar esse tipo de coisa no i-Educar em si, e talvez a gente integre, mas olha a quantidade de coisas que teríamos que fazer pra ter todos estes recursos enquanto o i-Educar em si precisa de muitos ajustes. Acho que não dá pra gente pensar neste tipo de recurso por enquanto.

Outra coisa. Será que o i-Educar não pode ser um hub? Ao invés de implementar absolutamente todas as necessidades no que diz respeito a gestão e educação, o i-Educar pode servir de plataforma pra fomentar um ecossistema de produtos.

Acho complicado a gente tentar resolver **todos** os problemas mas acho **super** importante a gente resolver a base deles primeiro e ir construindo em cima de uma base sólida.

Novamente, sou super a favor dessa movimentação e expansão mas:

- Precisamos organizar a casa antes;
- Temos que tomar cuidado pra não construir um monstro de uma aplicação;
- Temos que pensar qual seria a melhor arquitetura pra gente integrar tudo isso. Vai ser monolítico? Ou vamos trabalhar pro i-Educar ser uma plataforma produtiva pra aplicativos educacionais?

**Comment by JDias** [comment]
@eberfreitas o sr. pegou o espírito da coisa!
São perguntas que precisam algum encaminhamento.  O que eu acho inadequado é caminhar sem levar em conta esses desafios futuros, pois corre o risco de "arrumar a casa" e depois ter que mover um piano de lugar.

**Comment by JDias** [comment]
O sr disse que esta previsto plugar e ter varias personas, não é questão de going crazy, mas do que eu saiba isso seria roles e api e o i-educar não tem nada disso, afaik, apesar do diario do professor que não conheço o codigo.

Quanto as escolas não terem nem o básico é exatamente a vantagem do projeto i-educar, já ter entrada com redes de ensino e poder catalisar a adoção de outras ferramentas (posso elaborar depois)

Sei que o trabalho que tem pela frente é grande, mas a maioria das escolas estão no atraso por motivos que não são do escopo técnico. 

Eu ficarei quieto no meu canto, mas o erudio e o sistema escolar em laravel tem as APIs e uma estrutura, afaik, mais facil para se implementar roles.

Vocês estão trabalhando com dockers, ajustes de código, testes que são coisas que não tenho como contribuir. Tenho ideias e posso codificalas, mas não tem um gancho no i-educar que eu possa aproveitar.

Se eu quiser colocar um sistema de roles eu não tenho documentação do auth (teria que olhar no source) se eu quiser fazer uma API tem uns rascunho de API feito mas que teria que implementar em cima da mesma situação.

Como eu disse do começo, talvez o ieducar não seja o que eu procure, mas não por questão de escopo.
