### ISSUE TITLE
Erro ao Matricular do Aluno

### ISSUE THREAD

**Issue by rohanbernartt** [portabilis/i-educar#229]
MENU:
Escola > Cadastros > Alunos > 

DESCRIÇÃO:
Clico no código do Aluno na Listagem > Depois em Matricular aluno.
Quando preencho os dados da Nova Matricula e clico em Salvar, o sistema redireciona para uma tela com vários erros de Código. (https://prnt.sc/ju1v8c)

OBSERVAÇÕES:
Já preenchi outros campos que não são obrigatórios no Cadastro do Aluno, mas o erro persistiu.

AMBIENTE:
Plataforma utilizada: Docker (Ubuntu Docker 17.12.0~ce on 16.04) da Digital Ocean
Sistema operacional e versão: Ubuntu 16.04
Navegador e versão: Chrome Versão 67.0.3396.79
Outros detalhes importantes:

**Comment by munizeverton** [comment]
Olá @rohanbernartt !

Parece que está faltando uma função no banco, que deveria estar nas migrações.

Já estamos trabalhando nisso

**Comment by munizeverton** [comment]
@rohanbernartt o problema foi resolvido no PR #231 

Não esqueça de rodar as migrations após atualizar seu projeto.
`ieducar/vendor/bin/phinx migrate`

**Comment by munizeverton** [comment]
Exatamente!
