### ISSUE TITLE
Sobre o Diário Online será lançado?

### ISSUE THREAD

**Issue by scsrat** [portabilis/i-educar#230]
Olá e obrigado por nos ajudar a tornar o i-Educar um projeto melhor. Não esqueça
de revisar o nosso
[guia de contribuição](https://github.com/portabilis/i-educar/blob/master/CONTRIBUTING.md)
para saber melhor como colaborar com a nossa comunidade. Você também pode usar
o template abaixo para preencher sua issue:

**CONTEXTO:**

Por que esta alteração é importante? Como você usaria isto? Como esta alteração
pode beneficiar outros usuários?

**IMPLEMENTAÇÃO:**

Não obrigatório, mas sugira uma idéia de como isto poderia ser implementado.

**Comment by scsrat** [comment]
Haverá possibilidade de existir a implantação do Diário Online para o professor nesta versão disponibilizada aqui no Github?

**Comment by farribeiro** [comment]
Não sei que funcionalidade, mas dizem que será uma grande, para novembro

**Comment by MarceloCajueiro** [comment]
Olá @scsrat! Sim, vamos liberar o módulo de diário até novembro, inclusive com app para celular.

**Comment by farribeiro** [comment]
Como eu tinha previsto

**Comment by eberfreitas** [comment]
Pergunta foi respondida certo? Fechando aqui :)
