### ISSUE TITLE
Criação de script de instalação

### ISSUE THREAD

**Issue by farribeiro** [portabilis/i-educar#232]
Gostaria de sugerir a criação de shell script de instalação semelhante ao que se usa ao docker

Exemplo: `curl  <endereço> | bash`

Atenciosamente

**Comment by MarceloCajueiro** [comment]
É boa a ideia. Em algum momento isso seria legal, mas antes temos que deixar nossa imagem docker bem funcional e testada pela galera.

**Comment by farribeiro** [comment]
Ainda estou validando os comandos... estou esbarrando no echo para um arquivo no `/etc`

**Comment by vinicelms** [comment]
Gostaria de apoiar na frente de infraestrutura como código. Scripts de instalação não são muito simples de serem geridos e garantir interoperabilidade entre distros.

Acredito que utilizando Ansible ou Puppet, seria algo mais simples de manter e mais garantido para interoperabilidade.

**Comment by farribeiro** [comment]
Também concordo, mas temos que facilitar de alguma maneira para o usuário

**Comment by junyroman** [comment]
é eu fui um dos que tiveram dificuldades pra instalar, e ainda não consegui entender a parte em que poço colocar pra rodar através direto da minha maquina ao invés de um docker.

**Comment by eberfreitas** [comment]
@junyroman só pra eu entender direitinho. O que te impede de utilizar o docker?

**Comment by farribeiro** [comment]
Quer que eu te explico? Domina-lo!

Para alguns podem ser fáceis para outros difícil. Com o docker eu levei que 2a para entende-lo, muitos conceitos que muita gente desconhece. Falta de conhecimento profundo

**Comment by farribeiro** [comment]
Atualmente eu sou o cara da infra pela comunidade, aqui...

**Comment by junyroman** [comment]
@farribeiro é porque nem sempre estou na minha sala, e ainda estamos tentando comprar equipamentos. Para usar no docker eu não vejo problema, mas se em algum momento eu não tiver no ambiente ficaria mais fácil caso a maquina desligasse sem ter como eu acessar remotamente bastando apenas liga-la. Ou como vc mesmo disse o docker é incrível e como ainda sou bem noob não conheço muito dessa ferramenta. Se tiver algum comando que ele possa executar ao iniciar o pc para que seja iniciado junto com o docker-compose up -d. Vou baixar o telegram assim que possível aqui. Obrigado a todos.

**Comment by eberfreitas** [comment]
@junyroman realmente esta é uma situação um pouco + complicada. Você pode tentar usar um process manager pra cuidar disso como o [supervisor](http://supervisord.org/). Tem mais infos sobre isso aqui:

https://docs.docker.com/config/containers/start-containers-automatically/

**Comment by junyroman** [comment]
@eberfreitas valeu Eber, vou dar uma lida aqui.

**Comment by farribeiro** [comment]
O seu problema, @junyroman não é equipamento, é treinamento, domínio ao menos da LPIC.

**Comment by junyroman** [comment]
@farribeiro é verdade, como estou vendo essas questões de implantação do i-educar. Estou bem perdido, sem saber por onde ir. Mas vou manter o foco em buscar melhorias e ir atrás das certificações. Espero que compreendam minha inexperiência .

**Comment by farribeiro** [comment]
Agora se quiser correr por fora, use o Guia Foca que já foi e ainda acredito que é o mais completo sites a respeito de GNU/Linux em PT-BR. Também tem um livro (é fonte aberta também) de docker:

**Comment by farribeiro** [comment]
Entre no usergroup https://t.me/i-educar que te passo algum aspecto de fazer um meio termo para um datacenter, o que poderia ser legal implementar em seu ambiente de trabalho.

**Comment by junyroman** [comment]
blz vou dar uma olhada @farribeiro , obrigado mesmo.

**Comment by farribeiro** [comment]
Eu tenho mais dicas de infra na mão... só me contactar naquele link que te passei

**Comment by eberfreitas** [comment]
@vinicelms gosto muito da ideia de infra como código. O Ansible, por exemplo, é super simples de utilizar, tem diversos plugins que podem nos ajudar neste processo, além de ter interoperabilidade com diversas distros.

Eu sou fã do Ansible, principalmente pq nunca consegui usar Chef e Puppet direito 😂 então ele tem meu voto partindo desse ponto ;)

**Comment by farribeiro** [comment]
Eu sei provisionar com puppet

**Comment by eberfreitas** [comment]
@farribeiro o cara fala que SSH é um "serviço de terceiro" quando vai defender o Puppet... Isso não faz sentido. De qualquer forma, entendi que as arquiteturas são diferentes. Ansible ainda me parece bem mais fácil de usar que Puppet justamente por só precisar de software que na grande maioria dos servidores já estarão préviamente instalados e dificilmente vamos encontrar uma situação onde teremos "centenas ou milhares de máquinas" pra chegar nos limites do Ansible.

Ainda assim talvez o melhor caminho aqui seja trabalhar com alternativas? O que acham da ideia de criarmos projetos (repos) que resolvam isso pra cada tipo de software ou arquitetura desejadas? Poderíamos ter algo "oficial" usando algum software em específico mas a comunidade pode colaborar com sistemas escritos em Puppet, Chef ou qualquer outro software.

Lembrando que nunca vamos chegar numa solução ideal. O i-Educar é um sistema e não uma biblioteca. Vai ser impossível cobrir todos os cenários de deploy possíveis e tudo o que podemos fazer é trabalhar com sugestões e melhores práticas.

**Comment by farribeiro** [comment]
É porque o puppet tem um agent e o ansible usa abordagem diferente.

**Comment by vinicelms** [comment]
As abordagens são diferentes realmente, só que o Puppet ou Chef, são melhores. Vou expor meu ponto de vista.

Ansible precisa de PUSH para chegar nas máquinas, ou seja, precisa ser disparado por um usuário/pessoa ou processo.

Puppet e Chef também tem a possibilidade de serem disparados da mesma forma, mas além disto, também podem atuar com uma estrutura de GET, onde buscam configuração de um servidor. Isto dá mais versatilidade ao Puppet e Chef.

A desvantagem do Ansible é que ele precisa de um fator de autenticação para que possa atuar, ou seja, credenciais SSH e dependendo das ações, que o usuário tenha permissões de Sudo para executar a ação.

Puppet utiliza a comunicação web, ou seja, mesmo que a topologia de rede passe por um proxy, não precisará de redirecionamentos. Enquanto SSH não será tão simples assim para chegar ao seu destino. Adotar o Ansible pode não ser tão transparente quanto se espera.

O Ansible é indicado devido a curva pequena de aprendizagem.

Puppet e Chef podem funcionar agentless. 

Além do mais, existem pontos de vista diferentes dentre as ferramentas. Ansible é para. provisionamento, enquanto Puppet e Chef são para gestão de configuração e provisionamento também. 

Apoiar a gestão de configuração é algo interessante. Se alguém dispor disto em seu ambiente, é possível que a comunidade disponha um módulo, onde se aplica boas práticas para se manter a aplicação.

Todas as ferramentas são boas, mas no meu ponto de vista, apoiar a gestão de configuração, é algo que garantimos a qualidade a longo prazo.

**Comment by eberfreitas** [comment]
> A desvantagem do Ansible é que ele precisa de um fator de autenticação para que possa atuar, ou seja, credenciais SSH e dependendo das ações, que o usuário tenha permissões de Sudo para executar a ação.

Eu não entendo como isso pode ser uma desvantagem se você vai precisar exatamente disso pra instalar Puppet e permitir que ele execute seja lá o que ele precisa executar no servidor. Ou ele consegue executar tudo como usuário local? Tem algum fator que eu tô desconsiderando?

**Comment by vinicelms** [comment]
Os fatores que está considerando estão corretos, mas há um porém nisto: se não houver nenhuma ferramenta para provisionamento e/ou gestão de configuração, apenas o provisionamento é suficiente, lembrando que qualquer uma das soluções mencionadas são capazes de fazer. Todas precisarão de autenticação, pois não há nada da infraestrutura para automatizar o processo.

Só que se já houver a cultura de gestão de configuração, os módulos de Puppet ou Chef, serão mais adequados. A etapa de autenticação pode não ser uma realidade. Em ambientes de gestão de configuração, nem sempre há usuários nos servidores, pois são geridos através de gestão de configuração. 

Levando em consideração que o Puppet e Chef tem tudo o que Ansible pode dispor, além de mais opções, gostaria de "subir" a régua de qualidade, ao invés de nivelar "por baixo".

**Ansible:** provisionamento sem agente
**Puppet:** provisionamento sem agente, com agente e gestão de configuração
**Chef:** provisionamento sem agente, com agente e gestão de configuração

Construir em Puppet ou Chef, nos daria mais possibilidades, pois se apenas for necessário provisionar, será possível, mas se pensar em gestão de configuração, também será possível.

**Comment by farribeiro** [comment]
Tive uma estranheza ao terminar de instalar o aplicativo no metal, ele passou em todas as etapas com alguns ajustes, porém ...

Recebo ERRO 404

**Comment by farribeiro** [comment]
Por mais que os meus scripts e Dockerfile estejam falhando em poucos lugares já foi um avanço considerável que pode ser utilizado quase sem modificações em produção e desenvolvimento. Há uma certa incompatibilidade, entre o objetivo em desenvolvimento e produção e também sobre o domínio do provisionamento em ambiente de desenvolvimento 

Acredito que um ferramenta de provisionamento, não é suficientemente boa quanto o o shell script que é capaz de provisionar sem a necessidade de uma ferramenta externa.

Precisamos de um novo debate das linhas de atuação entre `DEVELOPMENT` e `PRODUCTION`

**Comment by farribeiro** [comment]
Link #209

**Comment by fernandosjp** [comment]
Minha opinião é que essa frente é super importante para facilitar a adoção da ferramenta! O objetivo é **ter um método muito simples de subir tanto desenvolvimento quanto para um ambiente pequeno de produção**. 

1) desenvolvimento 
Docker parece ser uma solução ótima para desenvolvimento e já é usado pela mantenedor (Portabilis) o que é melhor ainda. Se já tem não vamos re inventar a roda e continuar usando

2) produção
Vi que existe a discussão de que ferramenta usar: Ansible, Puppet e Chef. Acho que já existem também os argumentos para tomar uma decisão inicial. @eberfreitas o cenário ideal seria a mantenedora dar uma pista de qual acha que irá adotar no futuro. Assim a comunidade já pode fazer os scripts e ir testando. Não precisamos ter certeza absoluta aqui. Se mais para frente testarmos e aprendermos que não deu certo mudamos a direção. 

Como ainda não seria uma ferramenta da linha principal da mantenedora, acredito que podemos fazer uma caminho `scripts/contrib/ansible`. Assim indica que não é algo que esta no escopo da portabilis. Se a Portabilis eventualmente adotar essa contribuição para operação interna pode ser movido para a raiz da pasta scripts e passa a ser algo oficial. 

Já usei ansible e acho legal mas com as infos disponiveis talvez puppet seja mais util até para a Portabilis que tem uma operação mais complexa. O que acham? @eberfreitas vcs tem um palpite?

**Comment by farribeiro** [comment]
> Minha opinião é que essa frente é super importante para facilitar a adoção da ferramenta! O objetivo é ter um método muito simples de subir tanto desenvolvimento quanto para um ambiente pequeno de produção.
>
> 1. desenvolvimento - Docker parece ser uma solução ótima para desenvolvimento e já é usado pela mantenedor (Portabilis) o que é melhor ainda. Se já tem não vamos re inventar a roda e continuar usando
> 2. produção - Vi que existe a discussão de que ferramenta usar: Ansible, Puppet e Chef. Acho que já existem também os argumentos para tomar uma decisão inicial. @eberfreitas o cenário ideal seria a mantenedora dar uma pista de qual acha que irá adotar no futuro. Assim a comunidade já pode fazer os scripts e ir testando. Não precisamos ter certeza absoluta aqui. Se mais para frente testarmos e aprendermos que não deu certo mudamos a direção.

A primeira opção e muito menos a segunda está sendo usada com as melhores técnicas, tecnologias e imagens para a ferramenta docker.

> Como ainda não seria uma ferramenta da linha principal da mantenedora, acredito que podemos fazer uma caminho scripts/contrib/ansible. Assim indica que não é algo que esta no escopo da portabilis. Se a Portabilis eventualmente adotar essa contribuição para operação interna pode ser movido para a raiz da pasta scripts e passa a ser algo oficial.

A minha linha nesta opção continua sendo ShellScript.

> Já usei ansible e acho legal mas com as infos disponiveis talvez puppet seja mais util até para a Portabilis que tem uma operação mais complexa. O que acham? @eberfreitas vcs tem um palpite?

Quando usar puppet para a finalidade, vai rachar a mente assim... https://www.youtube.com/watch?v=kyNKHbmyPsY

**Comment by fernandosjp** [comment]
@farribeiro vai ser um treco difícil de manter. Não tem problema não estar com a mas melhores técnicas agora. Aos poucos vai melhorando. O que importa é criarmos e melhorarmos o que vai ser usado. Na minha opinião shell vai dar um super trabalho de manter¹. Isso no limite não precisa nem estar dentro do projeto. Para Fundação Lemann vamos criar algum script para nos ajudar nos nossos projetos com i-Educar. 

1. https://serverfault.com/questions/504070/why-use-chef-puppet-over-shell-scripts

**Comment by eberfreitas** [comment]
Vou colocar meus 2 centavos:

Não acho que este script ou qualquer outro que possa ajudar no deploy do projeto pra produção deva estar no repositório do i-Educar. Acho que seria benéfico criarmos diversos scripts fomentados pela comunidade e explico:

Colocar o projeto em produção é algo que vai variar drásticamente de uma realidade pra outra. Podemos trabalhar alguns scripts bacanas e puppet/ansible ajudam neste sentido, mas no final das contas a pessoa implantando o sistema vai ter que conhecer suas possibilidades e limitações. Quanto mais opções tiver para escolher aquela que se adequa mais aos seus conhecimentos e realidade, melhor.

Neste sentido, podemos começar com Puppet sem problemas, ou qualquer outra ferramenta. Eu continuo votando no Ansible por ser uma ferramenta mais simples de usar. Pelo que vimos dos usuários buscando instruções sobre como instalar o projeto em seus municipios, me parece que a maioria não tem um background muito técnico e ferramentas como o Docker e Ansible, por serem mais simples, ajudariam neste processo. Nada impede de termos projetos de integração com Chef, Puppet, Ansible, shell/bash ou qualquer outro que seja.

Na Portabilis atualmente não utilizamos nenhuma ferramenta de provisionamento. Mesmo atendendo aos inúmeros clientes que atendemos, ainda não tivemos uma grande necessidade de horizontalizar nossos recursos. Acho que essa é uma info importante pra gente entender qual é a necessidade de se usar ferramenta X ou Y.

**Comment by farribeiro** [comment]
> @farribeiro vai ser um treco difícil de manter. Não tem problema não estar com a mas melhores técnicas agora. Aos poucos vai melhorando. O que importa é criarmos e melhorarmos o que vai ser usado. Na minha opinião shell vai dar um super trabalho de manter[1]. Isso no limite não precisa nem estar dentro do projeto. Para Fundação Lemann vamos criar algum script para nos ajudar nos nossos projetos com i-Educar.
>
> [1] https://serverfault.com/questions/504070/why-use-chef-puppet-over-shell-scripts

Mas é a forma mais simples de fazer um deploy, posso garantir. Sem instalar pré-requisito nenhum

**Comment by fernandosjp** [comment]
Concordo @eberfreitas! Até porque pode ser que fique pior de manter esses scripts se a mantenedora não estiver usando. Assunto encerrado. :)

**Conclusão:** Script de instalação para produção, a principio, não estará no repositório do i-Educar. Vamos provavelmente incluir na documentação links referenciando scripts que ficarão em repositórios externos de pessoas que utilizam o software. Mais para frente é possível que a Portabilis incorpore algum script. Mantemos o uso de Docker mas vou adicionar um atenção para não ser usado em produção desta forma, ok?

**Comment by farribeiro** [comment]
Feito alteração no PR... Agora os scripts se encontram em `contrib/scripts`

**Comment by farribeiro** [comment]
Até que enfim, pude entrar em sintonia com o Eber

**Comment by farribeiro** [comment]
Vide https://github.com/portabilis/i-educar/issues/209#issuecomment-399666529

**Comment by JDias** [comment]
Não sei se está é a issue adequada, mas gostaria de sugerir que independente das soluções encontradas não apaguem do repositório os códigos já existentes, dockerfile, vagrantfile etc...

Se não quiserem utilizar podem colocar em contrib/unmaintened  com um txt informativo sobre como usar e pq não esta sendo usado.

**Comment by farribeiro** [comment]
O Git já rastreia isso

**Comment by JDias** [comment]
@farribeiro acho que o sr não entendeu, não é questão de intimidade com o git, é o mínimo de racionalidade.
não tem pq simplesmente jogar fora um código que já está pronto.

uma pessoa que olha o repositorio pode querer criar um dockerfile ou um vagranfile, se ele não encontrar nada ele não vai procurar no history do git, ele vai refazer.

se colocar da forma como eu disse, ele poderá reaproveitar o que foi feito, ou caso se convença da abordagem melhor proposta utilizar o que foi proposto.

é normal ter o folder unmaintened em projetos que se encaixa justamente para esses cenarios. (um código feito em determinada época, que não é mais necessário, mas que fica guardado como referencia)

 esse aqui ainda é .unmaintened para ficar hide https://github.com/ezrec/AROS-mirror/tree/ABI_V1/AROS/arch/.unmaintained

**Comment by farribeiro** [comment]
Foi o que disse... Facilita para quem não tem intimidade em olhar o histórico, eu incluso.

**Comment by farribeiro** [comment]
Aliás vou providenciar um revert e colocar na pasta conforme sugestão é submeter

**Comment by fernandosjp** [comment]
Concordo com você @JDias! Objetivo não é tirar o Docker ou excluir outros meios de facilitar a instalação. Acho que a decisão foi por enquanto não avançar com infra como código dentro do repo `i-educar` já que os mantenedores ainda não utilizam nenhuma tecnologia especifica. Isso ainda deve entrar no projeto mais para frente.

**Comment by JDias** [comment]
olá @tembra usei um dockerfile do @farribeiro , mas ele apagou o gist. 
(acho que é isso: https://gist.github.com/JDias/9c3f9556c346c9b7857f74344c1aa0c7 )

me interessei sobre a parte do sr não ter utilizado o Toolbox. o sr estava no windows 10 home? (pelo que lí o toolbox era o recomendado).

Acho super interessante ter esse procedimento redondo no readme.

**Comment by farribeiro** [comment]
Tenho melhorias a fazer no Dockerfile e vou restaur o branch de trabalho

**Comment by farribeiro** [comment]
Branch restaurado

**Comment by farribeiro** [comment]
> Concordo com você @JDias! Objetivo não é tirar o Docker ou excluir outros meios de facilitar a instalação. Acho que a decisão foi por enquanto não avançar com infra como código dentro do repo `i-educar` já que os mantenedores ainda não utilizam nenhuma tecnologia especifica. Isso ainda deve entrar no projeto mais para frente.

Eu já expliquei para ele que ferramentas de desenvolvimento não deveria estar misturado ao projeto

**Comment by farribeiro** [comment]
Conforme entendimento desta issue... terei que fazer revert de alguns arquivos do PR #215 ? Procede?

**Comment by eberfreitas** [comment]
Existem alguns motivos pelos quais eu acho que uma pasta `unmaintained` é desnecessária:

1. Muitos projetos usavam o unmaintained antes do git, onde acompanhar o desenvolvimento e evolução do projeto era mais complicado;
2. Estamos trabalhando agora melhor com versões/tags. Se alguém quiser ver como algo era feito anteriormente, basta olhar o código de uma versão específica anterior, fica bem mais fácil fazer este tipo de consulta;
3. O motivo pelo qual este assunto ressurgiu já foi resolvido. Estabelecemos que scripts de instalação, seja vagrant, bash, ansible, puppet, etc., serão projetos separados que poderão ser referenciados na nossa documentação pra instalação em situações específicas (https://github.com/portabilis/i-educar/issues/232#issuecomment-399239749). O @farribeiro, por exemplo, tinha um script interessante pra instalação no Ubuntu 16.04 que já poderia ter sido disponibilizado como um projeto separado, mas me parece que não foi pra frente. Eu pretendo fazer algo em Ansible e imagino que o @vinicelms esteja fazendo algo em Puppet/Chef.

Em suma, a gente quer muito ver estes scripts pipocando por aí. Se alguém fizer algo, nos mande para que possamos testar e documentar.

**Comment by farribeiro** [comment]
> Existem alguns motivos pelos quais eu acho que uma pasta unmaintained é desnecessária:
>
> 1. Muitos projetos usavam o unmaintained antes do git, onde acompanhar o desenvolvimento e evolução do projeto era mais complicado;
> 2. Estamos trabalhando agora melhor com versões/tags. Se alguém quiser ver como algo era feito anteriormente, basta olhar o código de uma versão específica anterior, fica bem mais fácil fazer este tipo de consulta;
> 3. O motivo pelo qual este assunto ressurgiu já foi resolvido. Estabelecemos que scripts de instalação, seja vagrant, bash, ansible, puppet, etc., serão projetos separados que poderão ser referenciados na nossa documentação pra instalação em situações específicas (#232 (comment)). O @farribeiro, por exemplo, tinha um script interessante pra instalação no Ubuntu 16.04 que já poderia ter sido disponibilizado como um projeto separado, mas me parece que não foi pra frente. Eu pretendo fazer algo em Ansible e imagino que o @vinicelms esteja fazendo algo em Puppet/Chef.

> Em suma, a gente quer muito ver estes scripts pipocando por aí. Se alguém fizer algo, nos mande para que possamos testar e documentar.

O primeiro ponto é que pode ser fazer coleta de lixo temporariamente, digamos por ciclos. mesmo assim o `unmaintained` pode conter scripts totalmente funcionais... porém sem manutenção futura.

Segundo ponto, como discutimos anteriormente isso pode ser por conveniência em manuseio da ferramenta de versionamento que ou em ter que buscar em seu histórico.

Terceiro ponto, este script por mais que seja contribuição e sem manutenção pode servir de referencia ao projeto em ofertar provisionamento em ambiente de produção. O que acredito que estar na pasta contrib significa... sem manutenção. Porém o projeto acata a causa, ou em minha visão, que o projeto proporcione tal funcionalidade, sem projeto separado.

**PS:** Para projetos separados, há outros relatórios distintos deste projeto. que poderia entrar como `contrib`

**Comment by farribeiro** [comment]
Fechando pois está desgastando a paciência

**Comment by farribeiro** [comment]
Gentileza, o amigo está com dúvidas e posição principalmente por parte da portabilis

https://forum.ieducar.org/t/ajuda-instalar-i-educar-sem-docker-no-opensuse-leap-15/68

**Comment by farribeiro** [comment]
sobre o provisionamento, chego a conclusão que tem ser totalmente compilado, tudo. Conforme debatido com o André Machado

**Comment by farribeiro** [comment]
Link #379 #380 #381 #386 #387

**Comment by farribeiro** [comment]
Link #406

**Comment by edersoares** [comment]
A release [2.1.0](https://github.com/portabilis/i-educar/releases/tag/2.1.0) trouxe a [instalação fácil para desenvolvedores](https://github.com/portabilis/i-educar/#nova-instala%C3%A7%C3%A3o) e a [instalação em servidor](https://github.com/portabilis/i-educar#instala%C3%A7%C3%A3o-em-servidor) o que atende o tópico principal da issue.
