### ISSUE TITLE
Funcionalidades do i-educar que necessitam login do aluno

### ISSUE THREAD

**Issue by JDias** [portabilis/i-educar#238]
**CONTEXTO:**

Explicitar serviços que acredito estão no escopo do i-educar.
Este é o sistema do estado de são paulo, o alckmin deu uma melhorada boa tanto nele quanto na uab após algumas faiscas que tivemos no twitter (tenho que aproveitar o ano eleitoral :) )

**IMPLEMENTAÇÃO:**

A implementação não sei exatamente como seria mas vale destacar a importância da **roles**

https://sed.educacao.sp.gov.br/

eles não tem, ou não tinham diferenciação para o acesso dos pais e dos alunos, que ao meu ver é um erro.
(incidental: uma rede escolar ter que fazer censo é uma coisa surreal na minha cabeça)

vamos lá, acredito que tudo que não é LMS é do escopo do i-educar, o que o LMS não tem, o i-educar poderia oferecer. (depois eu vou abrir outras issues com outras possíveis funcionalidades)

o sed já demonstram algumas. opiniões?

**Comment by MarceloCajueiro** [comment]
O template da issue foi feita para ser substituída @JDias. Se não fica bem complicado de ler. Editei para você ver o jeito ideal.

**Comment by JDias** [comment]
Ok, grato! 😊
