### ISSUE TITLE
Remote work

### ISSUE THREAD

**Issue by JDias** [portabilis/i-educar#240]
```
Olá e obrigado por nos ajudar a tornar o i-Educar um projeto melhor. Não esqueça
de revisar o nosso
[guia de contribuição](https://github.com/portabilis/i-educar/blob/master/CONTRIBUTING.md)
para saber melhor como colaborar com a nossa comunidade. Você também pode usar
o template abaixo para preencher sua issue:
```

```
**CONTEXTO:**

Por que esta alteração é importante? Como você usaria isto? Como esta alteração
pode beneficiar outros usuários?
```

Como não temos forum, estou colocando aqui na issue, mas é apenas um slide que eu recebi hoje no twitter e gostaria de compartilhar pois pode ser de interesse para mais alguém na comunidade.

https://twitter.com/osantana/status/1006706724684943365

```

**IMPLEMENTAÇÃO:**

Não obrigatório, mas sugira uma idéia de como isto poderia ser implementado.
```

Não se aplica, mas eu achei interessante (e uma ideia antiga) a abordagem dos colaboradores locais trabalharem com rotinas remotas.

**Comment by eberfreitas** [comment]
Estou fechando por ser algo fora do escopo da utilizada das issues. Vamos providenciar o forum em breve. Obrigado por compartilhar @JDias :)
