### ISSUE TITLE
Ausência de relatórios nos menus

### ISSUE THREAD

**Issue by bankayo** [portabilis/i-educar#241]
**MENU:**

RELATÓRIOS presente em todos os menus.

**DESCRIÇÃO:**

Após a instalação conforme explicado na página inicial (https://github.com/portabilis/i-educar) não foi possível localizar nenhum tipo de relatório (será por serem legados?). Constatei o mesmo no ambiente de testes (https://comunidade.ieducar.com.br/)

**Comment by MarceloCajueiro** [comment]
Em breve vamos liberar vários relatórios. Assim que tivermos datas eu atualizo aqui.

**Comment by edersoares** [comment]
@bankayo verifique se o novo [pacote de relatórios](https://github.com/portabilis/i-educar-reports-package) atendeu as necessidade. 

Por hora iremos fechar a issue, qualquer problema reabra ela por favor.
