### ISSUE TITLE
Problema nas configurações gerais (layout)

### ISSUE THREAD

**Issue by bankayo** [portabilis/i-educar#242]
**MENU:**

Configurações > Configurações gerais

**DESCRIÇÃO:**

Foi colocado URL da logo para testes, porém ao remover o link e salvar a imagem não deixa de ser exibida. Também não consegui deixar em branco os rodapés e links das redes sociais.

**Comment by munizeverton** [comment]
Realmente tem bugs na classe `clsPmieducarConfiguracoesGerais` que impedem alguns campos de ficar em branco.

Acredito que não seja algo muito complicado de resolver

**Comment by edersoares** [comment]
@bankayo obrigado por reportar, o @robertoarruda fez a correção e já está na master.
