### ISSUE TITLE
Dockerfile para banco de dados

### ISSUE THREAD

**Issue by farribeiro** [portabilis/i-educar#244]
Vejo a necessidade de um Dockerfile para o banco de dados. Favor discutir a possibilidade

**Comment by eberfreitas** [comment]
Pode explicar melhor @farribeiro ?

**Comment by farribeiro** [comment]
Veja seu repositórios e tem alguma coisa que monta banco de dados?

**Comment by eberfreitas** [comment]
Sim, o docker-compose.yml levanda um container de banco de dados configurado pra ser usado na aplicação:

https://github.com/portabilis/i-educar/blob/master/docker-compose.yml#L13

**Comment by farribeiro** [comment]
@eberfreitas Posso utilizar versão do postgresql posterior a 9.5?

**Comment by williamespindola** [comment]
Para mim ainda não esta claro esta necessidade.

**Comment by farribeiro** [comment]
Preciso de você no telegram now! Gentileza atender

https://t.me/ieducar

**Comment by williamespindola** [comment]
O docker-compose sobe uma stack e algum outro script roda as migrations ou o que mais for necessário. Para rodar tudo isto justo você pode ter algum script de automação. Pode ser um shell. make ou qualquer coisa to tipo.
A instalação inteira do i-educar poderia ser instalada com este script por exemplo:

```
#!/usr/bin/env bash

docker-compose up -d

cp ieducar/configuration/ieducar.ini.sample ieducar/configuration/ieducar.ini

git clone https://github.com/portabilis/i-educar-reports-package.git ieducar/modules/Reports

docker-compose exec ieducar_1604 composer install

docker-compose exec ieducar_1604 ieducar/vendor/bin/phinx seed:run -s StartingSeed -s StartingForeignKeysSeed

docker-compose exec ieducar_1604 ieducar/vendor/bin/phinx migrate

docker-compose exec ieducar_1604 chmod +x ieducar/vendor/portabilis/jasperphp/src/JasperStarter/bin/jasperstarter

docker-compose exec ieducar_1604 chmod 777 -R ieducar/modules/Reports/ReportSources/Portabilis
```

**Comment by farribeiro** [comment]
Onde este script se encontra?

**Comment by farribeiro** [comment]
Há um erro, uma descripancia entre este script e o conteúdo do `docker-compose.yml`

**Comment by williamespindola** [comment]
estão conectado via [link](https://github.com/portabilis/i-educar/blob/master/docker-compose.yml#L10)

Quais são as suas dúvidas? Pelo que vim não é uma infra complicada.

**Comment by farribeiro** [comment]
Parece que não, mas necessito de compreender o que estou fazendo, os internals e o que acontece... não reparei que a aplicação montava o banco via link

**Comment by farribeiro** [comment]
Me explica cada comando `exec` interfere nos dois containers

**Comment by williamespindola** [comment]
Com o exec você roda um comando com em um container https://docs.docker.com/engine/reference/commandline/exec/

Exemplo: `docker-compose exec ieducar_1604 composer install`

- `docker-compose exec` comando de execução
- `ieducar_1604` container onde eu quero executar 
- `composer install` comando que estou executando

Isto é a mesma coisa de eu entrar em um servidor que esta rodando a aplicação, no diretório da aplicação e executar `composer install`
