### ISSUE TITLE
Atualização do changelog e tag

### ISSUE THREAD

**Issue by farribeiro** [portabilis/i-educar#246]
> Olá e obrigado por nos ajudar a tornar o i-Educar um projeto melhor. Não esqueça de revisar o nosso [guia de contribuição](https://github.com/portabilis/i-educar/blob/master/CONTRIBUTING.md) para saber melhor como colaborar com a nossa comunidade. Você também pode usar o template abaixo para preencher sua issue:
> 
> **CONTEXTO:** Por que esta alteração é importante? Como você usaria isto? Como esta alteração pode beneficiar outros usuários?

Solicito alteração do changelog e sua devida tag

> **IMPLEMENTAÇÃO:** Não obrigatório, mas sugira uma idéia de como isto poderia ser implementado.

**Comment by farribeiro** [comment]
Nos mais antigos projetos utilizam essa wiki num arquivo de texto igualmente o `CHANGELOG`... Dever ser o `CONTRIBUITING.md`

**Comment by MarceloCajueiro** [comment]
Apaguei a Wiki de contribuidores. O github já exibe os contribuidores: https://github.com/portabilis/i-educar/graphs/contributors

Não precisamos de mais um lugar para isso.

Sobre changelog e tag, vamos, se encaixa nessa issue: https://github.com/portabilis/i-educar/issues/199

**Comment by farribeiro** [comment]
Ainda necessitamos de `CHANGELOG`

**Comment by farribeiro** [comment]
Me recordei de uma coisa a respeito no `CREDITS` na raiz do projeto, se no futuro incerto mudarmos de ferramenta a... ou mesmo abandonarmos o git #comofica?
