### ISSUE TITLE
Roadmap e abertura total do projeto 

### ISSUE THREAD

**Issue by williamespindola** [portabilis/i-educar#250]
Vendo o PR #248 é perceptível que o projeto ainda não esta aberto. Nenhuma das implementações listadas foi divulgada para a comunidade e o pr quebra as regras proposta e aceitas que definimos no [contributing](https://github.com/portabilis/i-educar/blob/master/CONTRIBUTING.md). Estando fora do [roadmap](https://github.com/portabilis/i-educar/wiki/Planejamento-T%C3%A9cnico) isto demonstra a existência de dois roadmaps diferentes para um mesmo projeto e precisa ser sincronizado ou unificado.

Porque nenhum dos pontos que foi adicionado no pr foi criado uma issue anteriormente?
Porque foi criado este branch com este grupo de alterações, foi aceito, feito merge com o master e mais uma vez não foi gerado release? Tem uma issue que fala sobre isto #199 
Qual a release atual do projeto?
Quais são as dificuldades? 
Como posso ajudar vocês a de fato virar esta chave?

Eu quero muito contribuir com este projeto, mas vocês precisam se organizar e mudar o mindset.

**Comment by leonampd** [comment]
E sobre a inclusão de algum membro de comunidade na adm do repo do projeto? O assunto prosseguiu de alguma maneira? Eu importante q a comunidade tenha algum representante administrando o projeto também.

**Comment by farribeiro** [comment]
> E sobre a inclusão de algum membro de comunidade na adm do repo do projeto? O assunto prosseguiu de alguma maneira? Eu importante q a comunidade tenha algum representante administrando o projeto também.

A isso está em aberto... melhor abrir issue para continuar tal discussão aqui.

**Comment by eberfreitas** [comment]
@williamespindola ótimos questionamentos. A gente ainda tá buscando um formato ideal pra tudo isso e você fez colocações importantes. Vou tentar responder um pouco das suas dúvidas e a dúvida do @leonampd também.

> Porque nenhum dos pontos que foi adicionado no pr foi criado uma issue anteriormente?

O i-Educar roda em produção pra centenas de escolhas em diversos municipios através da Portabilis. Por causa disso temos um time interno que resolve diversas issues todos os dias de coisas que vão surgindo no dia a dia da utilização real da plataforma Brasil a fora. Seria um tanto quanto "opressivo" jogar todas as issues aqui **atualmente**. Acho que a ideia é irmos jogando algumas das issues pra comunidade com o tempo conforme mais pessoas vão se envolvendo e se familiarizando melhor com o projeto. Já temos algumas issues de bugs e melhorias, infelizmente com pouca atividade, mas a gente também precisa começar a colocar + coisa pra galera começar a se mexer nessa direção.

>  Porque foi criado este branch com este grupo de alterações, foi aceito, feito merge com o master e mais uma vez não foi gerado release? Tem uma issue que fala sobre isto #199.

Eu acho que precisamos fechar isso de alguma forma, principalmente tendo em vista que, do jeito como estamos trabalhando talvez não seja ideal. Como vc mesmo disse, esse PR gigante vai contra o nosso Guia mas não sei como podemos resolver este fluxo. Ideias? Isso pode nos ajudar a definir melhor como vamos lançando versões. Apesar disso, não vejo a falta atual de versionamento um impeditivo pra colaborações.

> Qual a release atual do projeto?

Vamos finalizar esta discussão lá no #199 ?

>  Quais são as dificuldades?

Esta questão ficou meio vaga então vou respondê-la de acordo com meu entendimento. A maior dificuldade é conciliar tudo o que temos pra concilicar no momento: a integração da comunidade, com a demanda constante de melhorias e fixes por parte de usuários reais espalhados pelo Brasil, com a novidade que é administrar um projeto open source da importância, dimensão e complexidade que é o i-Educar. A Portabilis pegou anos de melhorias na plataforma e jogou pra comunidade e eu espero que este esforço seja devidamente reconhecido. Agora nós precisamos ter **paciência** em encontrar os melhores caminhos pra nossa comunidade florescer.

> Como posso ajudar vocês a de fato virar esta chave?

Questionamentos como este que você colocou já são muito importantes e ajudam bastante, até pra gente esclarecer pré-concepções às vezes equivocadas. Acho que o melhor que podemos fazer agora é tentar focar no roadmap de forma mais incisiva deixando de lado discussões periféricas tirarem o nosso foco e esforço para estas ações de mais impacto. Aqui eu vejo também uma falha em apontarmos caminhos melhores, mas eu espero que isso seja resolvido muito em breve e estamos trabalhando em comunidade. Sintam-se à vontade também para propor soluções ao que foi colocado no roadmap!

> E sobre a inclusão de algum membro de comunidade na adm do repo do projeto?

Antes de tudo, eu não vejo a Portabilis como um "ente" fora da comunidade. Muito pelo contrário. A Portabilis acabou de contribuir na comunidade com mais de 10.000 commits em melhorias e bug fixes, incluindo aí o censo escolar que é revolucionário pra gestão escolar. Isso **tá na comunidade** e acho que a Portabilis mais que mereceu seu posicionamento como mantenedora do projeto.

Tendo dito isso, para termos alguém da "comunidade" como adm, precisamos identificar quem **mereça** este posicionamento (e aqui falo como alguém da comunidade e não como alguém da Portabilis). Não adianta colocar qualquer pessoa da "comunidade" (sempre entre aspas pq não existe esta divisão na real) só por colocar, por uma questão mercamente politica. Precisa ter alguém que demonstre um pouco de compromisso com o projeto em todos os seus aspectos e isso pode tomar certo tempo (ou não).

De qualquer forma, espero que o engajamento de qualquer pessoa por aqui não dependa da possibilidade de se ter títulos ou posições dentro do projeto.

**Comment by williamespindola** [comment]
Valeu por reponder @eberfreitas 

Podem ficar tranquilos que jogar todas as issues aqui não seria opressivo, na verdade seria até melhor pra vocês pois outras pessoas da comunidade ajudaria a trata-las e não ficaria fora de sincronia como aconteceu no PR. Apenas se houver alguma regra ou tratativa interna ai precisamos ver como isto seria feito. Quando mais aberto for, melhor conseguirmos manter uma sincronia e evoluir o projeto como um todo.

Vou te chamar na issue de release para evoluirmos as idéias.

A pergunta ficou meio vaga mesmo desculpe, mas a idéia foi mitigar alguma dificuldade que vocês podem estar passando com a abertura do projeto e deu para entender seu ponto. Desculpe se fui impaciente, quero organizar estes pontos logo para começar a botar a mão no código.

Quando a adição de um membro da comunidade não tenho opinião formada, fica a cargo de vocês. Mas estou disposto para tal cargo caso tenham o interesse.

Bom vou fechar esta issue pois conseguir passar a mensagem e entendi os poréns. Qualquer novidade reabrimos. Vamos em frente \o/

**Comment by MarceloCajueiro** [comment]
Ótimos pontos e ótimas respostas @eberfreitas.

O que acham da gente fazer um FAQ englobando algumas dessas questões?

**Comment by fernandosjp** [comment]
Pessoal, muito legal ver essas discussões por aqui! Lendo o README eu tive a impressão que **o roadmap apesar de estar bem definido ainda é muito amplo e não ajuda a termos foco** no que é prioridade no curto prazo. Minha contribuição para essa discussão seria tentar colocar o roadmap no tempo. Algo em alto nível mas que ajude a deixar claro para a comunidade em que a Portabilis está investindo a maioria dos esforços de curto prazo mas também o que vem pela frente.

Acham que um roadmap nesse estilo ajudaria?
https://github.com/fernandosjp/test-roadmap/projects/1

@MarceloCajueiro acho legal um FAQ. Fiz uma sugestão na #266 e caso a gnt siga com isso posso ajudar a passar o que o ótimo trabalho que o @eberfreitas tem feito por aqui para o FAQ! :+1:
