### ISSUE TITLE
Arquivos de configuração em um único diretório

### ISSUE THREAD

**Issue by farribeiro** [portabilis/i-educar#253]
> Olá e obrigado por nos ajudar a tornar o i-Educar um projeto melhor. Não esqueça de revisar o nosso [guia de contribuição](https://github.com/portabilis/i-educar/blob/master/CONTRIBUTING.md) para saber melhor como colaborar com a nossa comunidade. Você também pode usar o template abaixo para preencher sua issue:
>
> **CONTEXTO:** Por que esta alteração é importante? Como você usaria isto? Como esta alteração
pode beneficiar outros usuários?

Colocar em uma único diretório os arquivos de configuração obedecendo PSR-4. Se não possível obedecer tal especificação ~~criar na raiz do projeto um diretório chamado cfgfiles~~ Utilizar diretório `configuration`

> **IMPLEMENTAÇÃO:** Não obrigatório, mas sugira uma idéia de como isto poderia ser implementado.

**Comment by farribeiro** [comment]
> PSR-4 não determina onde você colocar arquivos de configuração.

Olha lá a condicional... Então é só é só aplicar o PR

**Comment by williamespindola** [comment]
Desculpe não entendi.

**Comment by farribeiro** [comment]
> Desculpe não entendi.

Colocar em uma único diretório os arquivos de configuração obedecendo PSR-4. **Se não** possível obedecer tal especificação ~~criar na raiz do projeto um diretório chamado cfgfiles~~ Utilizar diretório `configuration`

**Comment by farribeiro** [comment]
Burrice, pois o `composer.json` pode garantir

**Comment by JDias** [comment]
Eu sou favorável a manter o .lock

**Comment by munizeverton** [comment]
O `composer.json` pode garantir a presença das dependências mas não a versão exata delas.

Mas enfim, essa issue é sobre outro assunto

**Comment by farribeiro** [comment]
Vou apagar meu commit inicial

**Comment by farribeiro** [comment]
Algum questionamento a respeito desta Issue em particular?

**Comment by JDias** [comment]
Cara, eu clique no email o link da issue do lock, não tenho a mínima idéia de como veio parar aqui, desculpe.

**Comment by MarceloCajueiro** [comment]
Escovando bit. Não estamos resolvendo nada aqui, já que como o @williamespindola, isso não está relacionado a PSR-4.

**Comment by farribeiro** [comment]
Acreditei que estava, mas... não está errada no conceito e existência dessa Issue

**Comment by farribeiro** [comment]
Fechando pois está desgastando a paciência

**Comment by edersoares** [comment]
Trabalho em andamento na versão 2.2 no PR #524.
