### ISSUE TITLE
Remoção do composer.lock

### ISSUE THREAD

**Issue by farribeiro** [portabilis/i-educar#255]
> Olá e obrigado por nos ajudar a tornar o i-Educar um projeto melhor. Não esqueça de revisar o nosso
[guia de contribuição](https://github.com/portabilis/i-educar/blob/master/CONTRIBUTING.md) para saber melhor como colaborar com a nossa comunidade. Você também pode usar o template abaixo para preencher sua issue:
>
> **CONTEXTO:** Por que esta alteração é importante? Como você usaria isto? Como esta alteração
pode beneficiar outros usuários?

Remoção do `composer.lock`

> **IMPLEMENTAÇÃO:** Não obrigatório, mas sugira uma idéia de como isto poderia ser implementado.

**Comment by williamespindola** [comment]
Não pode remover, ele deve ser mantido pois faz cache das dependências e também garante que as versões rodando nas máquinas dos devs e nos servidores seja exatamente as mesmas.

**Comment by farribeiro** [comment]
Ao rodar o `composer install` ele é criado?

**Comment by williamespindola** [comment]
ambos npm e composer devem ser mantidos. Sim se apagar e rodar ele vai ser criado mas como não tem o lock ele vai demorar muito mais pois terá que criar novamente toda a árvore de dependência de todas as dependências recursivamente e no caso do update vai atualizar todos os patches pois não tem referência de qual foi instalado e a aplicação rodou, com isto corremos o risco de algum pacote instalado como dependência não seguir o semantic version e lançar uma versão sem retro compatibilidade e quebrar a aplicação.

**Comment by farribeiro** [comment]
Gentileza, poderia avisar o projeto https://github.com/webtorrent/webtorrent-desktop que fere a conduta?

**Comment by munizeverton** [comment]
Olá pessoal!

Estamos fechando pois, como citado pelo @williamespindola, nós precisamos garantir que todas as dependências estejam nas mesmas versões em todos os ambientes.

**Comment by farribeiro** [comment]
https://github.com/webtorrent/webtorrent-desktop/pull/1370

**Comment by munizeverton** [comment]
@farribeiro você pode dar uma olhada [nessa parte](https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control) da documentação do composer, pra entender melhor do que estamos falando.

**Comment by JDias** [comment]
Como eu disse (na issue errada) o que o munizeverton referencia, a documentação explicitamente recomenda manter o .lock

**Comment by farribeiro** [comment]
https://github.com/webtorrent/webtorrent-desktop/pull/1371#issuecomment-385843520
