### ISSUE TITLE
Vue versus React

### ISSUE THREAD

**Issue by JDias** [portabilis/i-educar#258]
**CONTEXTO:**

Tendo em vista que no planejamento consta SPA (provavelmente PWA) seria muito precipitado debater uma solução de front-end reativo?

**IMPLEMENTAÇÃO:**

Alguma ferramenta tipo https://jsonplaceholder.typicode.com/ pode ajudar o front-end ser desenvolvido  sem o back (paralelamente ao back), acho.

Eu estou olhando o vue, especificamente o https://nuxtjs.org/ , mas por que me pareceu mais fácil.

O legal de debater esse tipo de coisa é que todas as views e boa parte dos javascripts vão ficar "obsolets or deprecated", e a tarefa de separar html de javascript e de colocar o template egine ficam obsoletos, acho.

(quanto as APIs servindo json, eu comentei com a @campagnucci , do pátio digital, sobre a possibilidade de definir alguns padrões abertos, assim facilitaria a portabilidade dos fronts, bem como as próprias integrações ou mudanças [no vendor lock-in], mas não sei se seria do interesse do i-educar caminhar por aí)

c/c @eduspano 

Talvez a @ludimila tbm. possa colaborar com o debate, já que ela já esta com um projeto com react na estrada

**Comment by farribeiro** [comment]
Mais vue

**Comment by JDias** [comment]
Pela minha 1a impressão do i-educar, meu argumento está errado:

`O legal de debater esse tipo de coisa é que todas as views e boa parte dos javascripts vão ficar "obsolets or deprecated", e a tarefa de separar html de javascript e de colocar o template egine ficam obsoletos, acho.`

Como solução para administração da escola o que já tem feito não impediria de fazer a abordagem pwa (notadamente para acesso mobile)

eu vou precisar de um tempo para me familiarizar com o "novo" i-educar. e como já comentaram, senti falta de sample data.

**Comment by lbssousa** [comment]
Eu acho que essa resposta depende um pouco de como será a relação entre o front-end e o back-end no seu projeto:

* Se você pretende fazer o seu front-end totalmente desacoplado do back-end, comunicando-se com ele via AJAX ou outro protocolo de comunicação, então tanto Vue como React (e outras opções, como Angular, Ember, Aurelia, etc.) atenderão igualmente bem.

* Se você pretende fazer alguma coisa mais "acoplada" com um back-end em PHP, a combinação Laravel+Vue pode ser bem interessante

* Se você pretende reescrever o seu back-end em Node.js, você pode tirar vantagem do SSR, tanto para Vue como para React.

* Seja como for, eu considero Vue a melhor opção para web apps (incluindo PWAs), mas o React Native é melhor se você pretente implementar um app para Android ou iOS.

**Comment by fernandosjp** [comment]
@JDias Acho que sempre vale o debate mas o no curto e médio prazo (3-6 meses) o projeto vai estar focado em correr atrás do prejuízo de código legado. Seria ótimo conseguir reforços para pensar os desafios dessa frente! :)

**Comment by eberfreitas** [comment]
Fechando essa issue por enquanto. Mais à frente podemos retomar quando formos trabalhar melhor com isso. Do jeito que é a comunidade de js, quem sabe até lá vue e react já são coisas do passado :P
