### ISSUE TITLE
Arquivo .ini

### ISSUE THREAD

**Issue by JDias** [portabilis/i-educar#262]
**CONTEXTO:**

O arquivo .ini  "poluido"?

**IMPLEMENTAÇÃO:**

Não seria o caso de passar alguma dessas variáveis para o banco de dados?

**Comment by JDias** [comment]
ps: existe algum motivo para ter 2 arquivos de configuração? (.env e o .ini)

**Comment by MarceloCajueiro** [comment]
Poderia discorrer mais? Exemplificar quais campos podem ir para quais tabelas no banco?

**Comment by JDias** [comment]
Olá @Marcelocajueiro eu precisaria de um tempo para elaborar. Foi minha 1a impressão. 

Me tira uma dúvida sobre o # 3 do planejamento estratégico, se instalar o componente de router do symphony e colocar um fallback para o atual index.html ajuda?

**Comment by JDias** [comment]
composer require http-foundation
&&
composer require routing

(eu dei uma olhadinha no coreext, mas acho que se adicionar esses 2 componentes não prejudicaria, por outro lado, conseguir buscar as rotas e se não achar utilizar o uri original vai precisar de algo um pouco mais elaborado  https://stackoverflow.com/questions/21470359/symfony-routing-fallback-chain )

apesar de ser algo para "depois"(o php-fig vem antes), fiquei curioso quais seria os componentes mínimos do symphony, e como e o que ele vai substituir do core/coreext. (routing/exceptions, HttpKernel ?) e a implementação de algo nessa linha http://symfony.com/doc/current/introduction/from_flat_php_to_symfony2.html#from-flat-php-front-controller

Foram as 1as coisas que fiz após instalar (tentar visualizar o que vocês planejaram)  

(desculpe se eu estiver muito perdido, foi um pensamento mais intuitivo do que propriamente tecnico)

**Comment by JDias** [comment]
Instalando o routing ele sugere 5 pacotes interessantes, mas eu estava apenas querendo visualizar os problemas para trás, não os para frente.

**Comment by farribeiro** [comment]
Link #386
