### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by JDias** [portabilis/i-educar#263]
**CONTEXTO:**

Gostaria de dar feedback de sucesso docker/ieducar!

**IMPLEMENTAÇÃO:**

Visual novo que eu não conhecia. Bastante coisa para vasculhar.
Inclusive possibilidade de cadastrar tipo de usuário e suas permissões (visualizar,cadastrar e excluir).
Obrigado a todos que me socorreram com as issues!

**Comment by MarceloCajueiro** [comment]
Boa @JDias. Ficamos feliz que gostou.

**Comment by JDias** [comment]
sim, tem acl na área! :)
