### ISSUE TITLE
Router

### ISSUE THREAD

**Issue by JDias** [portabilis/i-educar#264]
ok, antes de eu "going crazy" tentando entender a estrutura de arquivos do i-educar, já existe alguma preferência de solução para rotas no i-educar? se sim, qual?
eu gostaria muito de poder ter um sistema de rota que funcione com o sistema atual (se a rota não estiver configurada, fallback para a estrutura de arquivo).
Assim, caminha para frente, sem quebrar o para trás.
(toda vez que eu tento entender a estrutura dos arquivos termino com dor de cabeça e sem entender)

**Comment by JDias** [comment]
Pergunta respondida, vai ser o do symphony (here we go...)

**Comment by JDias** [comment]
É por aí?

https://stackoverflow.com/questions/21470359/symfony-routing-fallback-chain

**Comment by farribeiro** [comment]
Onde foi isso?

**Comment by JDias** [comment]
vou deixar esses links aqui (acho que é isso):

https://stackoverflow.com/questions/6718418/using-symfony2-routing-component-outside-of-symfony2

apesar de ser lugar comum (uma googlada retorna) pode ser útil para alguém:

http://fabien.potencier.org/create-your-own-framework-on-top-of-the-symfony2-components-part-4.html

acredito que seja algo assim @farribeiro que será encarado para o # 3 do https://github.com/portabilis/i-educar/wiki/Planejamento-T%C3%A9cnico

(tateando ... :) )


    "require": {
        "symfony/class-loader": "2.1.*",
        "symfony/http-foundation": "2.1.*",
        "symfony/routing": "2.1.*"
    }

seguido disso:

https://www.sitepoint.com/build-php-framework-symfony-components/

acho.

**Comment by farribeiro** [comment]
Estamos precisando do router já aplicado e funcional para podermos também aplicar a #267 com mais facilidade
