### ISSUE TITLE
Desenvolver um FAQ

### ISSUE THREAD

**Issue by MarceloCajueiro** [portabilis/i-educar#266]
Pessoal, temos vistos diversas perguntas e algumas são recorrentes.

Seria interessante compilar as perguntas e respostas num FAQ (no próprio README ou num FAQ.md).

Exemplos de perguntas: https://github.com/portabilis/i-educar/issues/250

**Comment by williamespindola** [comment]
A galera deste projeto resolveu este problema criando um repo apenas para isto https://github.com/kanboard/forum
Eles flertavam com issues com feature, discussões, e bugs ai fizeram isto.

**Comment by farribeiro** [comment]
Neste caso por que não utilizar https://www.discourse.org

**Comment by williamespindola** [comment]
O discourse precisa de um server? Acho que este seria o único ponto.

**Comment by MarceloCajueiro** [comment]
Acho que o discourse é uma boa solução sim. Por enquanto as issues estão atendendo.

A ideia aqui era apenas englobar algumas perguntas já feitas e respondidas e que são interessantes termos documentadas.

**Comment by farribeiro** [comment]
@willian a idéia é fazer um FAQ, não é? Por que também não um fórum... o que poderia dispensar o Telegram?

**Comment by fernandosjp** [comment]
Pessoal, vocês acham que o Discourse poderia fazer o papel de FAQ de ser um base de conhecimentos já resolvidos? 

Ao concentrar perguntas e respostas no fórum as com maior relevância já estaria facilmente acessíveis e respondidas. No Metabase eles tem uma tag FAQ: [Discourse Metabase](http://discourse.metabase.com/c/faq). O principal ponto que precisamos pensar é se isso ajudaria a Portabilis a ter menos trabalho operacional de responder mensagens repetidas. Como o caju comentou, o Slack não da certo por gerar um dinâmica muito improdutiva para o projeto.

Caso a gente entenda que o Discourse é uma boa posso apoiar com isso para eles não terem trabalho agora no curto prazo. Planejamos uma migração no final do ano se acharmos que a ferramenta foi útil. @williamespindola

**Comment by eberfreitas** [comment]
Eu acho legal termos um faq e um forum. O forum pode ajudar a definir novas questões ou elaborar melhor alguns pontos, mas também acho bacana a gente compilar isso num lugar separado como o @MarceloCajueiro comentou no topo da issue.

Fico à disposição pra tentar definir melhor algumas questões e indicar respostas.

**Comment by fernandosjp** [comment]
@eberfreitas não vai dar mais trabalho manter dois lugares separados? Podemos deixar um link que direcione para o forum já com o filtro da tag de FAQ. Acha que isso cumpriria o objetivo?

**Comment by eberfreitas** [comment]
@fernandosjp é que eu não vejo o forum como um lugar de FAQ. Vejo como um lugar de "AQ", rsrs... Mas talvez a gente possa separar alguns tópicos específicos e destacá-los como algo a compor o FAQ e assim criar um link específico pra estas questões mais específicas. É algo que eu não tinha considerado :)

E com certeza as issues não devem ser usadas pra FAQ. Nisso estou 100% de acordo. A ideia era ter um arquivo no projeto, um FAQ.md, mas talvez a ideia de centralizar no forum seja legal mesmo pra otimizar o trabalho.

**Comment by fernandosjp** [comment]
Bati o olho nas perguntas que o @MarceloCajueiro referenciou. Agora entendi melhor e acho que faz sentido mesmo deixar um arquivo de FAQ.md. 

1) Fórum: FAQ da comunidade (sobre o produto), discussoes de como instalar a plataforma, como usar funcionalidades, suporte entre membros de comunidade
2) Github Issues: discussões de desenvolvimento, novas funcionalidades, report de bugs.
3) FAQ: perguntas frequentes sobre o projeto i-Educar e não sobre o produto!

**Encaminhamento ponto 3 (prioridade agora):**
Confirma para mim se é esse o papel do ponto 3? Sabendo isso dou uma organizada no conteudo que apareceu por ai e mando um PR! 

**Encaminhamento ponto 1 (legal mas não prioridade:**
@eberfreitas continuamos a discussão sobre Discourse para matar as conversas técnicas do Telegram?  Acho essas conversas de como subir o sistema importante para o desenvolvimento de comunidade mas não no canal Telegram que fica muito chato e vai começar a espantar o pessoal de lá.

**Comment by williamespindola** [comment]
Então o FAQ seria mais para o usuário e não para o desenvolvedor é isto?

**Comment by eberfreitas** [comment]
A sugestão do FAQ surgiu a partir dos questionamentos que o @williamespindola fez na issue #250. Então imagino que a ideia do FAQ seja responder questões mais abrangentes relacionadas à administração do projeto, governança, etc. Faz sentido @fernandosjp? É +/- a isso que você se referia no ponto 3?

Sobre o forum, continuo achando super importante. Vai ser uma ferramenta bem melhor que o Telegram pra gente organizar conhecimento! Acho o discourse uma boa. Discourse que é feito com **ember** e que deveria ser sériamente considerado tmb pro futuro 😉 (misturando assuntos, ignorem).

É isso?

**Comment by fernandosjp** [comment]
@williamespindola @farribeiro acrescentando a informação de público para termos certeza de que estamos falando a mesma coisa.

**1. Fórum (talvez Discourse):** 
- Público: comunidade inteira, ou seja, desenvolvedores e usuários finais
- Papel: FAQ da comunidade (sobre o produto), discussões de como instalar a plataforma, discussões de como usar funcionalidades, suporte entre membros de comunidade.

**2. Github Issues:** 
- Público: desenvolvedores, poucos usuários que tenham perfil mais técnico
- Papel: discussões de desenvolvimento, novas funcionalidades, report de bugs.

**3. FAQ:** 
- Público: desenvolvedores que estão tendo o primeiro contato com o projeto
- Papel: perguntas frequentes sobre o projeto i-Educar e não sobre o produto! Questões mais abrangentes relacionadas à administração do projeto, governança, etc

Conclusões:
- vou consolidar oFAQ e abrir um PR
- aparentemente Discourse parece uma boa opção mas mas ainda não temos uma decisão final. Vamos colocar em espera e voltar nisso em breve

**Comment by eberfreitas** [comment]
@fernandosjp vi que você já enviou o PR do FAQ. Tenho umas ressalvas e vou jogar lá :)

Sobre o fórum, devemos ir com o Discourse mesmo conforme proposto aqui. Assim que tivermos tudo configurado, colocamos o link por aqui e na documentação também.
