### ISSUE TITLE
Separar o HTML do PHP

### ISSUE THREAD

**Issue by williamespindola** [portabilis/i-educar#267]
Remover todo o html / css / javascript que estiver na pasta src. os assets (css/javascript), inicialmente vão pra pasta public. O HTML deve ser extraído para uma pasta chamada templates e renderizado usando o Twig.

Isso iria começar a separar a camada de template do nosso código, assim mudanças de UI não precisam ser feitas no código e nosso código para a ficar mais limpo, para que as próximas mudanças sejam mais fáceis.

**Comment by eberfreitas** [comment]
Existe um problema com relação a isto hoje... O sistema depende fortemente de um "form builder" que foi desenvolvido, que é extremamente complexo e cheio de camadas e desconsidera qualquer utilização de um sistema de templates.

Este form builder agiliza muita coisa uma vez que você entende como ele funciona (essa parte toma tempo), mas é algo totalmente fora dos padrões e é extremamente confuso.

Acho que antes de qualquer coisa a gente poderia pensar em como melhorar esta parte do sistema ou, no mínimo, levar ela em consideração na hora de extrair o HTML pra um template engine.

Alguém por aí já deu uma olhadinha nesses códigos?

**Comment by williamespindola** [comment]
@eberfreitas pode me ajudar a entender melhor como isto funciona hoje? Me de um exemplos de onde o form builder é aplicado; E como o php se comunica com o front por favor.

**Comment by farribeiro** [comment]
Queria saber qual será a FHS do ieducar

**Comment by eberfreitas** [comment]
@williamespindola pega este exemplo:

https://github.com/portabilis/i-educar/blob/master/ieducar/intranet/educar_configuracoes_labels.php

As seguintes classes estão envolvidas também:

https://github.com/portabilis/i-educar/blob/master/ieducar/intranet/include/clsBase.inc.php
https://github.com/portabilis/i-educar/blob/master/ieducar/intranet/include/clsCadastro.inc.php
https://github.com/portabilis/i-educar/blob/master/ieducar/intranet/include/clsCampos.inc.php
https://github.com/portabilis/i-educar/blob/master/ieducar/lib/Core/Controller/Page/Abstract.php

Alguns comentários no arquivo vão te ajudar a entender +/- o que tá rolando.

**Comment by farribeiro** [comment]
Como estão separando a **VISÃO** do modelo e controle, já definiram a nova estrutura de diretórios?

**Comment by farribeiro** [comment]
Ao escopo desta ISSUE... unificar os ASSETS

**Comment by JDias** [comment]
não quero ser chato, pq parece que volto a um tema que já foi decidido, mas não seria legal, sem prejudicar o que está no roadmap, ter um php router? o router do symphony é mais elaborado e vai precisar do http foundations (e ter seu proprio sistema de extensões).

então minha abordagem seria, por enquanto, antes do symphony, usar um router mais simples, dessa forma teriamos router. (vi algo como url helper em algum lugar, não sei se ajuda).

em um segundo passo, poderia criar 2 arquivos, bootstrap e middleware, para incluir no router, mas falo middleware sem necessidade inicialmente, apenas o bootstrap com os includes que inicializariam o core e permitiria acessar o i-educar.

dessa forma acho que avançariamos algo. (laravelizando eu procuraria um gerador de models eloquent do database, mas que seria um outro issue)

no caso do laravel o sistema de routing eu acho que é o lumen, e provavelmente será tão elaborado quanto o do symphony. (e descobri semana passada que ele por default serve as páginas fora do rota, que eu não sabia)

então a abordagem seria pegar um http-router desses que tem no github (teria que dar uma olhada qual serviria melhor) e basicamente tudo continuaria a funcionar exatamente igual, com a diferença de poder criar rotas inicialmente, e em um segundo momento de acessar ao core, acho.

a mi

**Comment by JDias** [comment]
eu não ia conseguir dormir sem tirar esta duvida.

existe router do laravel na versão standalone, sem querer ser tendencioso, poderia ser usado. qualquer router php generico tbm resolve, é que usar o router do symphony seria mais intrusivo, pelo que li.

só pra lembrar, por baixo do laravel tem symphony, mas tanto o router quanto o doctrine não são easy tasks, principalmente se compararmos os seus similares, o eloquent e o router.

**Comment by JDias** [comment]
em português claro, acho mais facil laravelizar o i-educar do que symphonyzar. :)
e me baseio em 2 pontos do roadmap proposto, o router e o orm.

**Comment by JDias** [comment]
olá @MarceloCajueiro eu não lembro a @ que o sr comentou quando da proposta do roadmap, mas talvez valha a pena ouvir a opinião dele. são 2 pontos específicos e práticos, eu olhei as duas abordagens em relação aos dois tópicos, e para mim (que não sou referência) me pareceu mais tranquilo a abordagem não symphony, e são pontos realmente relevantes para um planejamento do que vai acontecer. (eu não pretendia voltar a este assunto, mas fui impelido pelas circunstâncias)

**Comment by JDias** [comment]
eu vou tentar explicitar o que eu imagino:

```
<?php
require_once 'inc/bootstrap.php // inicializa o core,app, kernel ... não sei o termo
require_once 'inc/middleware.php // em um 2 momento faz as validações

Route::ideia('aqui/vai/as/rotas', meuController@crud);
```
isso estou falando das rotas, por exemplo, não pesquisei muito:

https://github.com/phpgearbox/router

e se quiser aqui tem um roadmap para um momento posterior https://github.com/mattstauffer/Torch
eu posso estar engando e ter um versão do router do symphony que não use o http foundations

<hr>

em termos de orm:

link 1: https://jenssegers.com/53/using-eloquent-without-laravel
link 2: https://medium.com/@kshitij206/use-eloquent-without-laravel-7e1c73d79977 (que é basicamente a mesma coisa do link 1)

para ter uma referência como seria com o doctrine:
link 1: https://busypeoples.github.io/post/slim-doctrine/ (com o slim)
link 2: http://doctrine-orm.readthedocs.io/en/latest/reference/configuration.html (documentação oficial)

e por ultimo, um link de forma genérica poderia tentar achar algo assim:
https://medium.com/@CristianLLanos/eloquent-models-from-my-database-5d74c632e03c

que teria no doctrine algo assim: https://symfony.com/doc/current/doctrine/reverse_engineering.html

<hr>

Resumindo:
Eu acho as 2 abordagens do laravel mais fácil que a do symphony.
Sendo principalmente as rotas, já que o doctrine daria para fazer samba tbm, mas aí entra uma coisa minha, já que o doctrine é um ilustre desconhecido para mim.

**Comment by JDias** [comment]
ps: **errei o link do router** (mas realmente tem opções a beça no github) : https://github.com/seytar/php-router

aqui tem mais: https://laracasts.com/discuss/channels/laravel/using-routing-outside-of-laravel-without-the-huge-dependency-list

o que eu achei um complicador do router do symphony foi o http foundations, e como vc pode ver o laravel tbm tem essa dependência, só que eu achei routers _a la laravel_ sem essa dependência, e não achei similar para o symphony, pode ser que exista.

**Comment by JDias** [comment]
a encrenca com syphony, https://tech.yappa.be/symfony-components-in-a-legacy-php-application

mas independente do laravel versus symphony, o que estou chamando atenção é para necessidade de router (front-controller).

então independente de qualquer coisa, se conseguir chegar a uma posição que resolva essa necessidade acho valida (nem que seja de caráter provisório). Eu não consigo colocar o router do symphony no i-educar.

**Comment by farribeiro** [comment]
Junte tudo em um único commit

**Comment by JDias** [comment]
@farribeiro eu estou repetindo o que eu já falei antes, antes de comittar alguma coisa o pessoal precisa dar sinal verde em relação a issue. O plano é symphony router, eu não vou me meter nisso.
Existem coisas mais simples que resolveriam o problema, pelo menos por enquanto. Mas não vi ngm tocar no assunto. (Desculpe varios posts, quis aproveitar a oportunidade, vamos ver se vai ter ressonância)

**Comment by farribeiro** [comment]
Onde se lê commit, entende-se comentário

**Comment by williamespindola** [comment]
@JDias você não entendeu o rumo que a discussão esta tomando e este monte de comentários seus esta apenas sujando a thread.
Em nenhum momento alguém falou em adicionar alguma sistema de rotas. E sim se existe algum implementado para entender como o comportamento atual funciona.

**Comment by JDias** [comment]
@Williamespindola me desculpe o lixo, posso apagar se quiser.

Mas acho que o sr não me entendeu.

Existe sim, planos de utilizar o router do symphony, e não tenho nada contra, estou propondo ter um front-controller mais simples, enquanto o do symphony não se materializa.

**Comment by eberfreitas** [comment]
A discussão sobre o router é necessária mas acho que ainda não é o momento, muito menos a issue certa :joy: Se vamos ter um trabalho para implementar um router em qualquer momento que seja, acho que vale mais a pena investir tempo numa solução final e não em algo temporário. Já existe uma issue sobre router não? Vamos tentar focar aqui no conteúdo desta issue :+1:

**Comment by JDias** [comment]
Oi eber, eu não tenho skills para botar o router do symphony.

Mas é que poder fazer rota adianta o lado das apis (com urls restfulls) e essas coisas que o willian falou de um form simples e tals. Eu realmente não sei como o i-educar ainda não tem, é algo bem simples e que fica transversal a tudo. (Desculpe não acompanhar vcs, mas na hora que vc descreveu a situação de pronto eu visualizei a necessidade de um front controller)

**Comment by JDias** [comment]
Vou respeitar o ritmo de vcs! Mas deixando minha opinião.  (Me surpreendi de vc não já ter chegado com um pr de front controller, vc ilustra as situações com maestria)
