### ISSUE TITLE
Utilização de ES2016+

### ISSUE THREAD

**Issue by farribeiro** [portabilis/i-educar#273]
Gostaria de propor o uso da ecmascript 2016+
em substituição do javascript do projeto

Uma boa ferramenta a utilizar é typescript

**Comment by eberfreitas** [comment]
@farribeiro a necessidade ou não da utilização outras versões de js ou transpilers vai se tornar mais clara à frente, conforme formos movendo para esta parte do sistema.

Não vejo como produtiva a discussão disso agora já que é algo que pode mudar bastante até a hora de atacarmos esta parte do sistema, uma vez que isso não é prioritário agora (vide [planejamento técnico](https://github.com/portabilis/i-educar/wiki/Planejamento-T%C3%A9cnico)). Vamos fechar aqui e reabrir quando o assunto estiver mais fresco pra discussão.

**Comment by farribeiro** [comment]
Não é versão do JS e sim especificações mais recentes e ricas
