### ISSUE TITLE
APIs

### ISSUE THREAD

**Issue by JDias** [portabilis/i-educar#275]
Desculpem fugir um pouco do roadmap, mas gostaria de um feedback.

O que acham de listar as APIs que existem hoje no i-educar (a minha ideia de olhar a rota era para facilitar expor elas) e ter um roadmap de expor todas as funcionalidades do i-educar via API.

Dessa forma, o foco sairia do código e iria para funcionalidade.

e, a partir daí, backend e frontend poderiam ser refatorados independentementes, baseado nas funcionalidades. (não chega a ser microserviços, que envolve vários outros conceitos, mas microserviços servem de inspiração para o que eu estou comentando)

faz sentido? (não é um questionamento em relação ao roadmap atual, é uma tentativa de reflexão)

**Comment by eberfreitas** [comment]
Faz sim @JDias ... Acho que fazer isso vai ser um passo importante até pra gente transformar o i-Educar num ecossistema de ferramentas de gestão escolar e serviços periféricos.

**Comment by JDias** [comment]
Legal o sr comentar algo nessa linha @eberfreitas , um grande erro dos gestores acharem que quando colocam uma solução educacional resolveu o problema, sem entender que é um ecossistema, e que as soluções precisam serem "compatíveis" entre si.

Eu acredito que já vi algo aqui sobre definir o i-educar, delimitar seu escopo, e, no meu ponto de vista, o melhor enquadramento para o i-educar é "SIS" https://en.wikipedia.org/wiki/Student_information_system

São pequenas definições que ajudam a clarear o caminho.

Aproveitando o embalo, me lembro que o sr comentou sobre a arquitetura de microserviços e sobre a ideia de hub. São conceitos que realmente agregam, junto com a ideia de interoperabilidade e integrações. Eu não tenho opinião formada, mas talvez ao se olhar o https://clever.com/ possa ilustrar melhor um exemplo de como o i-educar não é o todo, mas é, por ser um SIS, o coração do ecossistema.

e ai entra uma dúvida, se esse marketplace de integração (sso) seria do escopo do i-educar ou não.

Vou colocar alguns links, que não tem nada relevante, mas ajudam a situar, contextualizar e abstrair:

1) https://support.learning.com/maintaining-user-accounts-and-classes/sis-integration-faqs/
2) https://blog.clever.com/2016/05/clever-is-open-and-now-with-oneroster/
3) https://www.onelogin.com/connector/clever

4) https://dasycenter.org/common-education-data-standards-ceds-align-tool/ (isso aqui, CEDS, seria mais relacionado ao MEC, mas não deixa de ser uma padronização, então coloquei na lista, envolve dados abertos, learning objects metadados etc)
5) https://www.blockcerts.org/ (este, ao meu ver, é a melhor solução para INTEROPERABILIDADE entre SIS)
6) https://www.projunicorn.org/ (menos relacionado, mas um projeto novo, como é ligado ao IMS não sou muito fã por não ser padrão aberto de verdade)

e aí é um papo que transcende o i-educar, mas, se estivermos na mesma página, o i-educar está incluso.

na pratica, integrações com o google apps, um lms e com ckan ajudariam a cidades que adotam o i-educar terem coisas que por elas mesmo não teriam, o i-educar poderia ser o gancho para introduzir outras tecnologias.

meus 0.20 centavos tentando compartilhar uma visão panorâmica.

**Comment by munizeverton** [comment]
Olá @JDias ! 

Acho muito válida sua ideia de listar todas as APIs, mas só lembrando que todas a APIs existentes hoje no i-Educar estão marcadas como _deprecated_.
Um dos planos é refatorar toda essa parte

Talvez seja melhor já fazer essa lista levantando o que seriam as novas rotas

**Comment by farribeiro** [comment]
É somente para levantamento e traçar planos de ação

**Comment by JDias** [comment]
Olá @munizeverton , eu nem sabia que existia API, foi apenas algo que pensei, e que compartilhei, caso tivesse alguma serventia.

**Comment by JDias** [comment]
Reopened!

**Comment by farribeiro** [comment]
Boa... estou querendo não apenas documentá-la e sim especificá-la. Alguém poderia me dizer como posso começar este trabalho?

**Comment by farribeiro** [comment]
Revendo alguns PR que abri, poderia utilizar o branch `api-quadro-horario` para me basear nos meus empenhos

**Comment by farribeiro** [comment]
Refletindo mais um pouco, @Jdias me mostrou um arquivo de API e nota que... o que é servido por elas estão

**Comment by JDias** [comment]
Não, não foi isso que eu falei.
Eu disse, e não foi relativo a este arquivo (Este arquivo eu dei como um modelo bom), que a localização do arquivos, diretorios e suas nomeclaturas não ajudam, pois não refletem um padrão, ao menos simples.

E que 1 passo poderia ser listar todos os arquivos de api (e se possível os endpoints) para identificar padrões.

**Comment by farribeiro** [comment]
Talvez nem exista model... Há duas hipóteses, ou o ORM desempenha este papel ou ele usa qualidade de um **objeto**

**Comment by JDias** [comment]
Não sou capaz de opinar!

**Comment by farribeiro** [comment]
@munizeverton onde se encontra os models (se é MVC) do i-educar?

**Comment by munizeverton** [comment]
Olá @farribeiro !

O i-Educar não segue bem uma estrutura MVC.
Em `lib/App/Model` tem umas classes que até poderíamos forçar a barra e chamar de model.

Sobre as APIs, de fato elas estão em `modules/Api/Views`, mas como eu tinha dito antes, estão marcadas como deprecated. A nossa ideia é mudar toda essa estrutura de APIs pra uma que faça mais sentido, mas ainda não definimos qual será essa nova estrutura

**Comment by farribeiro** [comment]
Obrigado pelo apoio... A minha ideia é levantar os objetos que o i-educar possui para repensar as APIs e FHS

**Comment by JDias** [comment]
Como diz o caju, eu não vou "going crazy" tentando entender ...

https://github.com/portabilis/i-educar/blob/master/ieducar/lib/App/Model/SimNao.php

**Comment by farribeiro** [comment]
Precisamos definir os objetos, principalmente em diagramas em especial o que existe fisicamente.

**Comment by fernandosjp** [comment]
@munizeverton Mesmo estando `deprecated` acho que se o @farribeiro quiser ajudar a deixar isso organizado na documentação seria legal, não acha? Dentro da documentação de Developers seria interessante ter um espaço documentando as APIs. 

Como você mesmo disse ainda não se sabe quando serão redesenhadas. Pode ser que elas continuem assim ainda por um bom tempo e é a API que continuará sendo usada para se comunicar com aplicações fora do i-Educar (ou seja, mesmo sabendo que não são o ideal é o que temos para hoje).

**Comment by farribeiro** [comment]
Bom a interoperabilidade tá sendo um fator chave, até para substituir o i-educar, leia-se um novo sistema  feito do zero ou troca de linguagem

**Comment by fernandosjp** [comment]
@farribeiro Consegue avançar com a prova de conceito e fazer uma proposta de como documentação da API? @eberfreitas vcs não tem uma documentação que possa ser ponto de partida para o @farribeiro ?

**Comment by farribeiro** [comment]
Atualmente estou tentando elaborar um ambiente, sugestão de @JDias usando lumen... estou estudando como executar na especificação e construção da API e quando pronta subir uma instancia i-educar e tentar trocar metadados.

**Comment by JDias** [comment]
Obrigado @farribeiro , mas não foi nada disso que eu disse, eu disse que o i-educar tem bastante documentação no source, e que podia colocar essa documentação on-line (doxygen e phpdocumentor, acho)

**Comment by farribeiro** [comment]
Eu também vou me empenhar em organizar este documento para o projeto

**Comment by JDias** [comment]
Em relação ao lumen @farribeiro eu falei do jwt (no laravel o passport te dá o jwt+oauth server), mas que foi uma referência a parte.

**Comment by farribeiro** [comment]
A idéia de fazer prova conceito é para prática

**Comment by JDias** [comment]
Aí são outros 500 ...

**Comment by farribeiro** [comment]
Se for fazer logo integração LDAP, melhor com o PDC/AD do SAMBA4

**Comment by JDias** [comment]
Perceba que ele utiliza ipfs (é algo novo, nunca tinha visto alguem com essa abordagem).
1)eu não sei se vai vingar
2)eu não consigo nem imaginar os cenários de uso

**Comment by eberfreitas** [comment]
Não temos @fernandosjp infelizmente...

**Comment by fernandosjp** [comment]
Sem problemas @eberfreitas! @farribeiro vc acha que conseguiria contribuir com a documentação da API?

Não sei bem o seria legal para começarmos pequeno. Poderia ter:

- o caminho do arquivo
- rota
- parametros
- descrições (mini descrição, tipo de dado)

Gosto muito dessa referencia. https://docs.konduto.com/pt/#api-de-pedidos. Acho o importante seria ter o conteúdo da documentação. Não estaria no escopo a ferramenta de documentação.

**Comment by eberfreitas** [comment]
Eu estou levemente confuso com o que a gente tá tentando fazer aqui, rsrs... A ideia é descrever os endpoints de uma API que vamos desenvolver no futuro ou das APIs que já temos atualmente e que serão descontinuadas conforme o @munizeverton já comentou?

**Comment by JDias** [comment]
Olá @eberfreitas , pelo que estou entendendo os 2!
Tipo, o que existe é a que vai ser abandonada, e a que vai ser criada ainda não existe. Mas posso ter entendido errado 😊

**Comment by farribeiro** [comment]
> Sem problemas @eberfreitas! @farribeiro vc acha que conseguiria contribuir com a documentação da API?
>
> Não sei bem o seria legal para começarmos pequeno. Poderia ter:
>
> - o caminho do arquivo
> - rota
> - parametros
> - descrições (mini descrição, tipo de dado)
>
> Gosto muito dessa referencia. https://docs.konduto.com/pt/#api-de-pedidos. Acho o importante seria ter o conteúdo da documentação. Não estaria no escopo a ferramenta de documentação

Obrigado pelo apoio, @fernandosjp , eu não tenho **zero habilidades** para isso embora tenho a disposição de fazer acontecer. Tenho trocado muitas ideias com @JDias para achar um caminho para sua realização desta atividade

**Comment by farribeiro** [comment]
> Perceba que ele utiliza ipfs (é algo novo, nunca tinha visto alguém com essa abordagem).
>
> 1. eu não sei se vai vingar
> 2. eu não consigo nem imaginar os cenários de uso

Te responndi em PVT

**Comment by JDias** [comment]
Como eu comentei com o fabio, repito, EU colocaria um front-controller (router), é a melhor maneira, imho, de código novo conviver com código antigo.

Em outras palavras, o new (labs) vai ficar parado até implantar o router do symphony, um front controller é uma coisa simples e colocar um router enquanto o do symphony não se materializa, não atrapalharia nada, imho.

Já sei o posicionamento do pessoal, e vocês já sabem o meu.

Eu não sei quando o router do symphony vai se materializar, um router genérico acredito que em meio dia dê para colocar.

**Comment by farribeiro** [comment]
Bom independente disso tem que fazer o reconhecimento do que existe

**Comment by farribeiro** [comment]
Bom... Independente disso, tem que fazer o reconhecimento do que existe. Este está sendo a prioridade no momento

**Comment by JDias** [comment]
Hibernate  ...
