### ISSUE TITLE
Reescrita do histórico do projeto

### ISSUE THREAD

**Issue by farribeiro** [portabilis/i-educar#276]
> Olá e obrigado por nos ajudar a tornar o i-Educar um projeto melhor. Não esqueça de revisar o nosso [guia de contribuição](https://github.com/portabilis/i-educar/blob/master/CONTRIBUTING.md) para saber melhor como colaborar com a nossa comunidade. Você também pode usar o template abaixo para preencher sua issue:
>
> **CONTEXTO:** Por que esta alteração é importante? Como você usaria isto? Como esta alteração pode beneficiar outros usuários?

**TAREFA:** Reescrever histórico do projeto para melhor uso do `git log`. Resolve #199 e #246 

> **IMPLEMENTAÇÃO:** Não obrigatório, mas sugira uma idéia de como isto poderia ser implementado.

**Comment by fernandosjp** [comment]
O que você quer dizer com isso @farribeiro? Explica melhor para a gente.

**Comment by farribeiro** [comment]
Tornar o histórico mais legível, em especial aos Merge pull request que não são nada ilustrativo.

Execute este comando para refletir

**Comment by fernandosjp** [comment]
@farribeiro passado é passado. Minha opinião é que é importante corrigir para frente (o que já esta em andamento). Dois motivos pelos quais não priorizaria isso: 

i) corrigir histórico seria um esforço gigante e 
ii) gera ZERO valor para usuário

Não acha?

**Comment by farribeiro** [comment]
Mas este valor é para nós desenvolvedores... em manter o projeto coeso

**Comment by farribeiro** [comment]
Esses foram os primeiros commits deste projeto

**Comment by fernandosjp** [comment]
Minha opinião é que não acrescenta valor para os desenvolvedores para justificar o esforço de corrigir isso. Também acharia lindo se o `git log` estivesse bonitinho. Temos que resolver daqui para a frente. Passado para mim não faz sentido.

@williamespindola @leonampd acham que vale a pena esforço em reescrever histórico de commits?

**Comment by farribeiro** [comment]
Então faremos daqui para frente.
