### ISSUE TITLE
OFF-TOPIC: identificação estudantil

### ISSUE THREAD

**Issue by JDias** [portabilis/i-educar#278]
Como não existe forum, e não existe outro ambiente, compartilhando um pouco sobre identificação estudantil:

https://www.hidglobal.com/education/k-12

e esse aqui ganhou um certo momentum esses dias:

 https://k12cybersecure.com/blog/hacking-the-iste18-smart-badge/

percebam que não estou defendendo estas abordagens, apenas compartilhando o que existe.

**Comment by farribeiro** [comment]
@JDias me passou alguns sites de metadados... que sabe seja interessante:

http://vocab.e.gov.br/2011/03/vcge#sistema-educacional-avaliacao

**Comment by JDias** [comment]
olá @farribeiro , não entendi o seu crachá, mas identificação digital é um desafio atual em todo lugar do mundo.
hoje parece que certidão de nascimento já pode vir com CPF e o CPF é o identificador de fato da pessoa.
apesar dos problemas do DNI ser apenas para pessoas mais velhas, temo o login cidadão https://scp.brasilcidadao.gov.br/scp/login e pelo que eu soube um vasto sistema de identificação pelo inep_id ...

quando falamos de auth, id faz parte.

sim, os metadados é o que torna os objetos educacionais poderosos, e o vocab provavelmente é o que é usado no educacenso.

evidentemente todos esses assuntos estão fora do escopo do i-educar no momento. (e não vou entrar em definições de mvc, que assim como o laravel, só aprendi por causa do i-educar, curioso, não?)

**Comment by farribeiro** [comment]
> olá @farribeiro , não entendi o seu crachá, mas identificação digital é um desafio atual em todo lugar do mundo.

Eu falei que o meu crachá usa tecnologia HID, somente isso.

PS: @JDias comparecer ao usergroup ao menos para esclarecer umas dúvidas rápidas

**Comment by JDias** [comment]
olá @farribeiro o RCN(ICN), e o RIC (Registro de indentidade civil) agora são DNI, afaik.

pelo visto tem gente fazendo rocknroll https://github.com/transmute-industries/did-ldap-orbitdb-experiment  (experimental)

**Comment by farribeiro** [comment]
Essa de oauth para o sistema é a boa?

**Comment by JDias** [comment]
Poderia elaborar sua pergunta? O tema "identificação digital" me interessa bastante.

**Comment by farribeiro** [comment]
Atualmente, no dia de hoje, servidores e profissionais se autenticam via certificado A1/A3... Só que com solicitação da FEBRABAN em andandonar este modelo em prol de digital ou NFC.

Eu não tenho conhecimento, nem superficial da área, é apenas um exercício de reflexão dos eventos que sucedem.

**Comment by JDias** [comment]
O sistema de login do brasil cidadão tem 5 níveis de autorização, mas a parte de autorização não é o X da questão, a parte da identificação sim.

O cpf é o identificador de fato, mas temos tbm o inep_id, por exemplo, criar uma consistência para a identificação digital seria um ótimo avanço. 

Na parte de autorização, o nivel de segurança vai variar de acordo com o escopo da autorização, acho. E aí as tecnologias são as mais variadas.

**Comment by farribeiro** [comment]
O ideal é trabalhar com que é definido pela autoridades certificadoras

https://iti.org

**Comment by JDias** [comment]
"Para o i-educar se autenticar via oauth, sendo que é necessário suportar o que o governo tem como padrão obrigatório." ....

O governo não tem como padrão obrigatório, é apenas um servidor openid, que pode ser federado, afaik.

Saindo do tema geral e entrando no i-educar (ou sistemas educacionais no geral) eu precisaria de um blog post para elaborar as possibilidades  ...

**Comment by JDias** [comment]
O sr se refere a http://www.iti.gov.br ... ?

Já tive acalorados debates acerca da pki, e existe movimentações, concordo contigo que o ideal seria ter esse certificado, mas ...

http://m.convergenciadigital.com.br/cgi/cgilua.exe/sys/start.htm?UserActiveTemplate=mobile&infoid=47266&sid=11

**Comment by JDias** [comment]
Não tenho um blog para fazer o post @farribeiro , mas vc imagina que existe a carteira da une, a carteira do bilhete unico, que tem nfc, mas até um simples qr code com 2 fatores de autenticação já dá para fazer bastante coisa. Certamente existe espaço para avançar, o blockcerts não tem uma solução de identificação específica. É um tema bem interessante para elaborar (principalmente de como colocar de escanteio as safadezas que querem vender)

**Comment by JDias** [comment]
Incidental @farribeiro , caso tenha interesse 

https://robn.io/u2f-lca-2017/
