### ISSUE TITLE
Problema no campo 87 (Banda larga) do registro 10 do Educacenso

### ISSUE THREAD

**Issue by munizeverton** [portabilis/i-educar#279]
Foi identificado que o campo 87 do registro 10 do Educacenso não está sendo preenchido corretamente na exportação.

O campo em questão foi removido do sistema e é preenchido no arquivo conforme o preenchimento do campo "Possui internet". Porém seu preenchimento não está de acordo com as regras abaixo, sendo que deveria estar:

- Deve ser preenchido quando o campo 86 (Acesso à Internet) for igual a 1 (Sim).
- Deve ser nulo quando o campo 86 (Acesso à Internet) for diferente de 1 (Sim).
- Somente aceita os seguintes caracteres entre parêntesis: (0 1).
    Legenda: 0 – Não, 1 – Sim

**Sugestão de implementação**
Alterar o preenchimento do campo 87 na exportação do censo para que o seu valor fique de acordo com o campo 86.
Essa funcionalidade está em `ieducar/modules/Api/Views/EducacensoExportController.php`

**Comment by farribeiro** [comment]
O que realmente este item do censo? E sua necessidade de saber tal metadado

**Comment by Bonot** [comment]
@farribeiro, o documento usado é o **Layout de Importação e Exportação da Matrícula Inicial**, disponível para download em: http://portal.inep.gov.br/matricula-inicial.

Esse campo foi removido do sistema pois assumimos que sempre que a escola em questão utilize internet, esta é banda larga, porém no arquivo ainda está pegando informação do banco e apenas anulando quando não possui internet.

@munizeverton acredito que esse campo também deva ser removido do banco e no arquivo receber 1 quando o acesso a internet foi 1 também. E verificar como ele é utilizado na analise, pois se remover o banco terá que ser removido também da analise, caso utilize.

**Comment by farribeiro** [comment]
Irei me adentrar apara elaborar as APIs
