### ISSUE TITLE
Roadmap e labels

### ISSUE THREAD

**Issue by eberfreitas** [portabilis/i-educar#281]
Fala galera,

Em conversas (principalmente com o @fernandosjp) achamos que seria legal direcionar um pouco melhor os nossos esforços e tentar deixar todo mundo na mesma página daquilo que nós precisamos que seja feito e discutido de forma mais imediata. Assim a gente consegue focar nas prioridades e fazer a coisa acontecer.

Uma primeira iniciativa que vai ajudar a gente nesse processo é a criação de um roadmap que nos permita visualizar melhor como cada etapa se dispõe no tempo. O @fernandosjp propôs algo assim aqui:

https://github.com/fernandosjp/test-roadmap/projects/1

E eu meio que já reproduzi pra gente aqui:

https://github.com/portabilis/i-educar/projects/3

Basicamente copiei item por item, mas fiquem à vontade pra discutir se os itens ali estão corretos, se este seria o timeframe mais adequado, etc. É um primeiro passo pra gente começar então dêem seus feedbacks!

A outra iniciativa foi a de usar melhor os labels nas issues. Além de categorizar o que é bug, melhoria e recurso, a gente tá colocando uns labels de prioridade:

- P0 - Urgente
- P1 - Fazer logo (achei essa descrição meio meh, ajudem, rsrs)
- P2 - Fazer assim que possível
- P3 - Não prioritário

Eu passei pelas issues colocando os labels correspondentes (já peço desculpas pelas notificações) e é importante notar que as prioridades vão ser definidas de acordo com o que está no roadmap então a issue #265, por exemplo, está com P1 porque é algo que está na nossa coluna de "Trabalhando" do roadmap atual. Acho que deu pra entender a ideia né?

Eu também mudei o nome de alguns labels pra entrar em conformidade com algumas facilidades que o GitHub oferece quando elas são usadas. Por exemplo, `easy pick` virou `good first issue`, etc.

Então se alguém estiver com qualquer dúvida sobre o que devemos abordar e trabalhar neste momento, basta olhar os labels e checar o roadmap direitinho.

Vamos focar e fazer as coisas acontecerem :)

**Comment by fernandosjp** [comment]
Acha que ajuda bem a entender o que está sendo trabalhado! Queria fazer duas sugestões:

- Não colocaria o P3. O que não for prioritário pode ficar sem tag nenhuma até que vire prioridade. Pode ser que surja a necessidade de um tag "Won't fix" mas ai é uma discussão a parte da que estamos tendo aqui e não valeria entrar nisso
- Colocaria nomes nas tags de Priority/P0, Priority/P1, Priority/P2. De forma que seja de fácil interpretação mesmo para quem chegou pela primeira vez. A escala seria: P0 para blockers, P1 para prioritários, P2 importantes. O que acha?


 

Além disso seria legal a opinião de @farribeiro @williamespindola @JDias @nawarian

**Comment by farribeiro** [comment]
Acho que estilo sinaleiro fica interessante...  Somente três prioridades

- urgente
- importante
- e necessário.

**Comment by fernandosjp** [comment]
@farribeiro minha impressão é que usar como semáforo fica muito colorido e acaba atrapalhando. Vou explicar meu racional.

Priority/P0 = blocker, ou seja, extremamente urgente pois está impedindo o uso de funcionalidade crítica
Priority/P1 = prioridade, ou seja, o que o time esta priorizando e trabalhando no momento
Priority/P2 = importante, ou seja, issues que surgem e não podem ser esquecidas no backlog. São próximas na fila

- todos começam com `Priority` pois na hora de adicionar a label as tags ficam proximas e organizadas
- todas em cores vermelho para chamar a atenção do que é prioridade do momento

**Comment by farribeiro** [comment]
Só é três cores

**Comment by farribeiro** [comment]
> Sim @farribeiro mas é 3 cores só para as tags de prioridade. Ainda vão surgir mais:
>
> - discussões
> - novas funcionalidades
> - melhorias
> - ajuda
> - facil
> - bug
>
> Acho que não precisaria ter 3 cores para definir o que é prioridade no projeto

Para essas eu deixaria sem cor

**Comment by eberfreitas** [comment]
Tentei deixar um esquema de cores mais leve dando destaque pras prioridades:

https://github.com/portabilis/i-educar/labels

Depois me falem o que acharam :)

**Comment by farribeiro** [comment]
Está mais leve as cores, mas não gostei da prioridades

**Comment by fernandosjp** [comment]
@eberfreitas Achei que ficou bem legal! 

@farribeiro 
O papel dos labels de prioridade é quase que mostrar o que está dentro da sprint atual e no máximo próxima sprint, ou seja, que está sendo priorizado para um mês de trabalho. Mais que isso é muito difícil de prever. 

O que quero dizer é que parece ser **mais importante de distinguir issues que são prioritárias (tons de vermelho) vs outras tasks (sem vermelho)**. A distinção interna entre prioridades ajuda a ter um segundo nível de importância já que podem surgir issues urgentes mas o objetivo principal acredito que esteja cumprido!
