### ISSUE TITLE
Implementação da PSR-1

### ISSUE THREAD

**Issue by farribeiro** [portabilis/i-educar#285]
> Olá e obrigado por nos ajudar a tornar o i-Educar um projeto melhor. Não esqueça de revisar o nosso [guia de contribuição](https://github.com/portabilis/i-educar/blob/master/CONTRIBUTING.md) para saber melhor como colaborar com a nossa comunidade. Você também pode usar o template abaixo para preencher sua issue:
>
> **CONTEXTO:** Por que esta alteração é importante? Como você usaria isto? Como esta alteração pode beneficiar outros usuários?
>
> **IMPLEMENTAÇÃO:** Não obrigatório, mas sugira uma idéia de como isto poderia ser implementado.

Como teve discussão a respeito da PSR-2 e PSR-4 ... e sobre a PSR-1?

**Comment by farribeiro** [comment]
Como teve discussão a respeito da PSR-2 e PSR-4 ... e sobre a PSR-1?

**Comment by munizeverton** [comment]
Olá @farribeiro !

A PSR-1 já está contida na PSR-2 (https://www.php-fig.org/psr/psr-2/). Sendo assim, não é necessário uma issue específica.
Inclusive a #265 já prevê essas duas PSRs.

Estou fechando essa issue. Obrigado pela contribuição!
