### ISSUE TITLE
Transferência entre escolas do município não esta exibindo escola destino

### ISSUE THREAD

**Issue by munizeverton** [portabilis/i-educar#286]
**O que acontece?**
Nas transferências para escolas do município quando o usuário coloca a informação escola destino o nome da escola é salvo. Porém quando é consultado depois de alguns dias não tem mais a informação.

Esta situação ocorre, pois ao transferir um aluno, se a escola destino for da rede municipal, o sistema não está salvando esta seleção de escola. Já se for selecionado a opção "Outra" e digitado o nome da escola manualmente, o sistema salva normalmente.

**O que deveria acontecer?**
Apresentar os dados preenchidos pelo usuário no momento da transferência

**Comment by JDias** [comment]
O sr saberia dizer mais ou menos os arquivos/métodos envolvidos no problema?

**Comment by farribeiro** [comment]
Para este problema ele irá oferecer já a solução

**Comment by JDias** [comment]
O sr não achou o behaviour estranho @farribeiro , olha o bug que ele descreveu.

**Comment by farribeiro** [comment]
Não tem nada estranho... como este BUG P0 é mais para histórico que logo mais virá o PR

**Comment by JDias** [comment]
Porém quando é consultado *depois de alguns dias* não tem mais a informação.

Acha normal?

Eu fiquei curioso!

**Comment by farribeiro** [comment]
Agora, pela idade da issue... não está normal.

**Comment by edersoares** [comment]
Problema foi resolvido, basta atualizar o sistema.
