### ISSUE TITLE
Disponibilizar API para cálculo de média final

### ISSUE THREAD

**Issue by munizeverton** [portabilis/i-educar#287]
Criar uma API no i-Educar que receba a turma, suas notas de avaliação e recuperação, para então devolver os dados já calculados da média parcial, nota de recuperação e média final dos mesmos.

**Comment by farribeiro** [comment]
Quais modelos/controllers que a API tem que receber?

**Comment by JDias** [comment]
olá @munizeverton vc teria como gerar um json do post que a API tem que receber e que formula ela tem que aplicar?

**Comment by munizeverton** [comment]
Olá @JDias !

Ainda não temos o request definido.

Sobre a fórmula, já existe uma funcionalidade que faz isso em `DiarioController.php` , método `postNotas`.
A diferença é que pra esse novo endpoint ele não vai salvar a média. Somente retornar

**Comment by JDias** [comment]
Olá @munizeverton , saberia dizer qual é o impeditivo de trocar esses require_once por namespaces?

**Comment by farribeiro** [comment]
Gostaria de informações a respeito da especificação desta API
