### ISSUE TITLE
Validações no cadastro de etapas da escola

### ISSUE THREAD

**Issue by munizeverton** [portabilis/i-educar#288]
**Local da alteração:**
Escola > Cadastros > Escolas > Editar ano letivo

**Descrição:**
No cadastro de etapas de escola aplicar as seguintes validações:
- [ ] Alterar os labels **Módulo** e **Módulos** para **Etapa** e **Etapas**
- [ ] Data final não pode ser menor que data inicial
- [ ] Data inicial não pode ser maior que data final
- [ ] Data inicial da etapa seguinte, não pode ser menor que data final da etapa anterior
- [ ] Data final da etapa anterior, não pode ser maior que data inicial da etapa seguinte
- [ ] As datas não podem conflitar, independente da quantidade de etapas adicionadas deve ser considerado a ordem inserida, sendo que a primeira linha etapa 1, segunda linha etapa 2, etc.
- [ ] O campo para seleção do módulo saíra da tabela de seleção e será informado apenas uma vez
- [ ] Ao selecionar o módulo, carregar a quantidade de etapas na tabela abaixo conforme campo Quantidade de etapas e não permitir adicionar etapas a mais.
- [ ] Remover as opções adicionar novo e remover da tabela de etapas
- [ ] Validar para que não seja permitido selecionar módulos diferendes no mesmo calendário
- [ ] Só permitir ano diferente do ano letivo que está sendo editado, na data inicial e final do calendário.
- [ ] Caso não exista quantidade de etapas informados na etapa selecionada, informar o usuário que é necessário primiro o preenchimento da mesma em Cadastros > Tipos > Escolas > Tipos de etapas

**Comment by farribeiro** [comment]
Fora a correções propostas, especificar algumas constantes referente normas do MEC, não seria interessante?

**Comment by kellynvd** [comment]
@farribeiro  não entendi sua pergunta, mas as alterações propostas aqui não tem relação com normas do MEC, estamos apenas validando a inserção dos dados nos campos para evitar que o usuário insira informações erradas.

**Comment by farribeiro** [comment]
O que estava pedindo é basear o máximo em normas do MEC

**Comment by edersoares** [comment]
Algumas melhorias já foram implementadas e outras não são mais necessárias.
