### ISSUE TITLE
Erro do checkbox em séries da escola

### ISSUE THREAD

**Issue by munizeverton** [portabilis/i-educar#289]
**MENU**
Escola > Cadastro > Série da escola

**DESCRIÇÃO**
No campo de Etapas específicas quando sofre alterações. Mesmo que desmarque este e salve o registro, ao acessar novamente, ele aparece como marcado.

![image](https://user-images.githubusercontent.com/2388903/42137123-4484507e-7d3d-11e8-942f-bc30527ef6c3.png)

*OBS*
O inverso não ocorre, de marcar um check que não estava habilitado.

**Comment by farribeiro** [comment]
Como anda a tratativa deste blocker, @munizeverton ?
