### ISSUE TITLE
Sobre roadmap

### ISSUE THREAD

**Issue by JDias** [portabilis/i-educar#295]
**CONTEXTO:**

Implementação do roadmap

**IMPLEMENTAÇÃO:**

Aparentemente todos os arquivos do i-educar vão ter que ser reescritos (não é uma questão de refatorar) para se adequarem ao php-fig.

Não seria interessante detalhar a implementação dos pontos mais críticos (router e orm)?

eu não dúvido das skills da equipe, mas acreditam que conseguirão adequar os arquivos aos padrões propostos, dentro de um prazo exequível?

humildemente, sem flames, não seria melhor deixar o código legado como está (com as manutenções que forem necessárias) e focar em um novo código?

eu não fiz conta, mas não vi um arquivo que sequer estivesse próximo do psr1, e colocar como milestones separar html de php, por exemplo, pode se tornar um trabalho totalmente obsoleto se for trabalhar com front e back isolados. (como também o twig)

eu não quero colocar agua no chopp de ninguém, mas alguém aqui defende abertamente que vale a pena a refatoração desses códigos?

eu me sinto em uma situação extremamente constrangedora, mas acho bem razoável elaborar este assunto.

o roadmap é ótimo, colocar tudo no padrão php fig e usar um pouco do symphony. quem poderia criticar isso? mas acham exequivel?

a ideia de usar um framework não é utilizar um framework propriamente dito, é que o framework faça o trabalho pesado.

muitas vezes tem projetos com frases "build on shoulders of giants", é bem o espirito, não "have some nice components inside"

eu não tenho respostas prontas, mas só eu acha que vai existir um trabalho monumental para um retorno menor? do tipo a montanha parir um rato?

acho um barato construir framework, até um tempo atrás eu jamais utilizaria composer ou npm, mas os tempos são outros, e por mais entusiasta que eu seja do "faça você mesmo", será que realmente vale a pena o esforço?

eu realmente fico assombrado com o trabalho proposto no roadmap, mais uma vez nada contra, até pq não sou eu que vou fazer isso, mas como não vi ninguém se posicionando nesse sentido, pelo contrario, parece que todos estão de acordo, achei importante colocar um contraponto.

o código antigo funciona, estar preocupado com php-cs-fixer e testes em código que para se adequar vai ter que mudar da cabeça aos pés, ao invés de na mesma batida estar produzindo um código novo, ao meu ver, ao final terá o código antigo com uma nova velha roupagem. eu posso estar errado e vocês conseguirem fazer isto da noite pro dia e com os pés nas costas. eu não consigo (e nem me animaria para fazer, pelos motivos que disse)

para mim, este software teria que ser reescrito, pedaço a pedaço. refatorar o código atual, dentro do prazo que está estipulado é algo que vocês já tem parametrizado? (mais uma vez, não duvido das skills de ninguém, mas quem olha o roadmap e olha o source code percebe que não é uma questão de passeio no parque)

mais uma vez, eu não tenho as respostas. estou tentando elaborar as perguntas certas.

**Comment by farribeiro** [comment]
Isso porque a equipe ainda está focada em liberar o código restante do i-educar que será a conta gota até ao menos em Novembro

**Comment by farribeiro** [comment]
Essa discussão não poderia ir para #281 ?

**Comment by JDias** [comment]
Eu acho que vou fechar, e ver como caminha.
