### ISSUE TITLE
Site do projeto e da documentação do i-Educar

### ISSUE THREAD

**Issue by fernandosjp** [portabilis/i-educar#297]
**CONTEXTO:**

Desde de o inicio da colaboração do em IFMS, Portabilis e Fundação Lemann ([link](https://softwarepublico.gov.br/archives/thread/i-educar/alinhamento-de-esforcos-em-prol-do-i-educar-pela-portabilis-ifms-fundacao-lemann)) percebemos que seria essencial ter um site explicando o projeto do i-Educar e também um local para a documentação detalhada sobre como usar o produto. 

Durante esse período fizemos um benchmark com alguns projetos abertos que temos usado como referência ([Metabase](https://github.com/metabase/metabase), [Rocket Chat](https://github.com/RocketChat/docs)). Além disso pesquisamos ferramentas outras ferramentas que pudessem nos ajudar a resolver esse problema. Para a escolha final utilizamos os seguintes critérios:

Critérios:
1) Facilidade de uso
2) Uso por empresas/projetos abertos de referência
3) Sustentabilidade do projeto aberto

No inicio de maio deste ano, achamos que a ferramenta [Docusaurus](https://docusaurus.io/) seria a ideal para site e documentação do i-Educar! Ela atende os critérios acima pois:

- renderiza arquivos markdown para a documentação
- tem funcionalidade de versionamento de documentação
- pode ser personalizada de acordo com a identidade visual do projeto
- é usado em 23 projetos abertos do Facebook e o Metabase também pretende adotá-los (relatado por e-mail)
- não gera custo de hospedagem para o mantenedor (site estático)

Apesar de termos interagido bastante nesta frente antes de começar a trabalhar no repositório aberto, quis deixar registrado um pouco do histórico para não parecer que é algo que surgiu do nada. A partir desta primeira implementação, as interações sobre documentação e site podem ser discutidas mais amplamente por aqui e podemos contar com a contribuição de mais pessoas. :+1: 

**IMPLEMENTAÇÃO:**

- [x] Portabilis precisa disponibilizar estrutura base do Docusaurus no repo i-educar
- [x] Portabilis precisa configurar github pages usando o dominio `ieducar.org`
- [x] IFMS irá implementar novo site da comunidade e fazer um PR

Estamos de acordo @MarceloCajueiro (Portabilis) @rsdevigo (IFMS)

**Comment by rsdevigo** [comment]
Sim, estamos !
Estou com uma equipe trabalhando dentro do IFMS _Campus_ Dourados para implementar o novo site.
Vamo que vamo !

**Comment by JDias** [comment]
eu acho bem legal esta iniciativa, mas acho interessante fazer esse tipo de ressalva: http://ericholscher.com/blog/2016/mar/15/dont-use-markdown-for-technical-docs/

Eu não sei bem o que "renderiza arquivos markdown para a documentação" abrange.

**Comment by farribeiro** [comment]
Eu não recomendo markdown para esta empreitada

**Comment by rsdevigo** [comment]
Olá @JDias dei uma olhada no site sobre o Markdown não ser bom para documentação, e um dos argumentos é que a linguagem é muito simples, e essa é a beleza do Markdown para o nosso caso, isso torna fácil e rápido um colaborador escrever um manual de algum módulo do i-Educar.

Outro argumento é a falta de padrão, mas uma coisa boa para o nosso caso, podemos criar o nosso padrão de estrutura de texto para nossos documentos, já fazemos isso com os mais diversos tipos de projetos.

Mas conforme o projeto evoluir precisaremos pensar em ferramentas mais robustas para documentação, por exemplo criar referência de imagem no texto.

E por último não sei se devemos pensar em documentação em source code, uma vez que, comentários se tornam obsoleto e difícil de manter (vide Clean Code).  Sou a favor de abstrair a DSL do i-Educar em diagramas ou exemplos de uso.

**Comment by farribeiro** [comment]
> Olá @JDias dei uma olhada no site sobre o Markdown não ser bom para documentação, e um dos argumentos é que a linguagem é muito simples, e essa é a beleza do Markdown para o nosso caso, isso torna fácil e rápido um colaborador escrever um manual de algum módulo do i-Educar.

Não! Essa simplicidade custa, em não ser eficiente em fazer alguma coisa mais elaborada...  Ser simples não é sinônimo de eficiência. Para isso recomendo algo mais próximo a isso com asiicdoc

> Outro argumento é a falta de padrão, mas uma coisa boa para o nosso caso, podemos criar o nosso padrão de estrutura de texto para nossos documentos, já fazemos isso com os mais diversos tipos de projetos.

Não é a falta de padrão, padrão ele tem, é como diria... o dialetos variados.

> Mas conforme o projeto evoluir precisaremos pensar em ferramentas mais robustas para documentação, por exemplo criar referência de imagem no texto.

HTML é supermo nessa questão. suporta tag que vocês nem imaginam

> E por último não sei se devemos pensar em documentação em source code, uma vez que, comentários se tornam obsoleto e difícil de manter (vide Clean Code). Sou a favor de abstrair a DSL do i-Educar em diagramas ou exemplos de uso.

Dá para manter HTML a moda KISS

**Comment by fernandosjp** [comment]
Pessoal, acho que aos poucos vamos criar juntos alguns princípios de comunidade que vão nos ajudar nas decisões. Minha contribuição provavelmente irá na direção de manter-se simples e focar no usuário final. Por enquanto vamos de markdown pelos critérios citados acima. Esse não é o debate que irá mudar o jogo no projeto do i-Educar, certo? De qualquer forma, obrigado pela contribuição! Ela é sempre válida! :+1:

**Comment by JDias** [comment]
Eu acho que fui mal compreendido.

Fui favorável a utilizar o markdown (bem legal ter o site dentro do repositório, ao invés de externo como em uma wiki), quanto ter documentação gerado do source code, é implícito.

O problema foi algo como o doxygen ter sido completamente ignorado.

Existe algum motivo pratico para não ter esta documentação on-line?

Não vou entrar no mérito de pq uma abordagem é mais flexível que a outra, pois é fora do escopo.

Eu explicitei que tentei achar uma forma de analisar o código e gerar um markdown compatível com o docusauros, mas não encontrei, e propus um pequeno hack, gerar o html do doxygen, por exemplo, e apenas adicionar o link para o html gerado no markdown.

exatamente, aonde está o prejuízo? Se tiver doc no source, será gerado e atualizado no próprio fluxo de desenvolvimento, se não tiver, em nada vai prejudicar, acho.

Eu não tinha entrado nesse debate antes pois poderia ouvir: "baixe o código e gere a documentação", mas se documentação para desenvolvedor esta no escopo (e acho bem legal ter), não vejo pq não complementa-la com documentação gerada do source.

**Comment by farribeiro** [comment]
Interessante o ponto... Mas como é compilado estas modificações ao aplicar no master?

**Comment by JDias** [comment]
São os últimos links que mandei Fabio, dentro do próprio workflow de desenvolvimento.

**Comment by fernandosjp** [comment]
@JDias uma vez que a documentação estiver no ar acho que teste interessante o que você propôs. Se puder fazer um teste e retomar mais para frente acho que poderia ser interessante sim. Por enquanto vai ser algo bem básico./

**Comment by JDias** [comment]
Sem problemas @fernandosjp , como eu disse eu comentei apenas para constar, mas não tem mistério ou dificuldade nenhuma, é algo bem básico mesmo. (pra falar a verdade, vc consegue botar isso de pé antes de conseguir botar a documentação do docusauros, em termos de dificuldades)

**Comment by JDias** [comment]
olá @fernandosjp eu não sei bem como seria um teste, usado o doxygen wizard consegui alguma coisa (a impressão que tenho é que o código não está tão bem documentado como estava antes, mas mesmo assim tem algo) 

coloquei no ar para o sr poder visualizar  http://ieducar.sisdipe.com.br/docs/class_aluno_controller.html

**Comment by fernandosjp** [comment]
@rsdevigo, o @MarceloCajueiro já deixou no ar a estrutura do docusaurus e alterou o DNS do ieducar.org.

Agora esta tudo certo para receber a contribuição de vocês! Vamos tentar fazer um primeiro PR, mesmo que ainda em andamento, do site amanhã (06/07)?

Valeu cara!!

**Comment by fernandosjp** [comment]
@JDias sobre doxygen, achei que ficou bem confuso, né? Minha sugestão é deixar de lado por agora.

**Comment by JDias** [comment]
@fernandosjp eu não fiz nenhuma config, mas já estava decidido ficar de fora a bastante tempo :)

Abs,

**Comment by JDias** [comment]
ps: eu não gerei com suporte a busca, pois precisaria de uma hospedagem com php, mas, por mais confusa que possa parecer, a documentação ajuda! (evidente que qualquer pessoa pode gerar a documentação, mas ter ela online facilita o acesso)

onde o sr vai achar as funções agrupadas dessa forma, não são coisas intuitivas ...

http://ieducar.sisdipe.com.br/docs/class_aluno_controller.html

(bom, acho que se quisessem online, estaria online... apenas apresentei que existe, caso alguém ignorasse o fato)

**Comment by farribeiro** [comment]
@fernandosjp acho que dá para considerar como feito a última atividade, embora não configurada pois ainda dá problemas de resolução. Já está no repositório

**Comment by rsdevigo** [comment]
@fernandosjp Opa, estamos planejando realizar um PR ainda hoje com a landing page quase finalizada.

Valeu !

**Comment by fernandosjp** [comment]
Gostaria de agradecer ao @rodrigodevigo e alunos do IFMS pelo ultimo PR! O site do projeto ficou sensacional! Ficaram alguns detalhes antes de fechar a issue.

- [ ] consolidar últimos posts relacionados ao projeto i-educar
- [ ] revisar conteudo de texto e garantir que tiramos todos os "lorem ipsum"

**Comment by fernandosjp** [comment]
Vou passar esses dois ultimos pontos para issues separadas.
