### ISSUE TITLE
Integrar PHPStan

### ISSUE THREAD

**Issue by eberfreitas** [portabilis/i-educar#298]
**CONTEXTO:**

Acabei trombando com essa ferramenta:

https://github.com/phpstan/phpstan

É quase uma pré-compilação do código e com algumas mudanças pra adequação aos padrões, seria legal rodar essas ferramentas e garantir que nada está quebrando já que não temos testes.

**IMPLEMENTAÇÃO:**

https://github.com/phpstan/phpstan#installation

**Comment by farribeiro** [comment]
Será que é bacana em adicionar ao composer?

**Comment by JDias** [comment]
Fiquei curioso para saber como seria o resultado de rodar isso no i-educar @eberfreitas

(Apesar de eu achar que o problema maior do i-educar não é de código, é de design)

**Comment by farribeiro** [comment]
Acho que o mesmo efeito que olhar no scrutinizer onde ele aponta bug de código

**Comment by JDias** [comment]
@eberfreitas , pelo visto o sr se adiantou a mim.
O sr sabe dizer se o phpstan consegue gerar um lista aonde quebra para diferentes versões de php?

Ele está apontado como uma alternativa para isso nesse projeto:

https://github.com/sstalle/php7cc/blob/master/README.md

**Comment by JDias** [comment]
Esquece minha pergunta, o scrutinizer já respondeu 😊
