### ISSUE TITLE
.htaccess

### ISSUE THREAD

**Issue by JDias** [portabilis/i-educar#305]
**MENU:**

na instalação

**DESCRIÇÃO:**

o .htaccess precisa de atenção

**OBSERVAÇÕES:**

Na minha maquina local eu tinha conseguido rodar normalmente, mas assim que tentei na vps, percebi que o .htaccess está desatualizado

**AMBIENTE:**

comecei por aqui https://www.virtualmin.com/node/24753
mas em seguida percebi que o .htaccess não estava configurado para o 2.4 e sim na sintaxe 2.2

consegui fazer funcionar, mas este arquivo precisa de atenção de alguém que se sinta mais confortável que eu para fazer as alterações.

**Comment by farribeiro** [comment]
A mozilla disponibiliza um gerador de HTACCESS... estou devendo o link

**Comment by fernandosjp** [comment]
@JDias deixa o titulo da issue um pouco mais clara? "Mudar sintaxe de .htaccess para 2.4"
Seria isso?

**Comment by JDias** [comment]
Não sei @fernandojsp , se vcs estiverem trabalhando com 2.2 não dá para mudar.

Eu não tenho base nem para dizer se está errado ...
Só descobri problema por acaso, e mandei um link como, e nesse link apontam falha de segurança, mas não posso realmente confirmar.

No ambiente local passou batido esses detalhes, mas no vps não.

Eu dei um feedback, já consegui resolver minha situação, agora não tenho como dizer o que é o certo ou errado. Como deveria ser ou não.

**Comment by farribeiro** [comment]
O deploy é feito usando ubuntu 16.04 e o servidor httpd deste release é 

> ## Package: apache2 (2.4.18-2ubuntu3.8 and others) [security] 

https://packages.ubuntu.com/xenial/apache2

**Comment by fernandosjp** [comment]
@JDias eu quis dizer quanto a clareza do nome da issue. ".htaccess" esse nome não deixa claro o que você vai explicar. Vamos nos policiar para criar issues bem escritas e que evitem mal entendidos.

**Comment by eberfreitas** [comment]
@JDias o que vc fez pra resolver?

**Comment by farribeiro** [comment]
Existe esta doc... https://httpd.apache.org/docs/2.4/upgrading.html

**Comment by JDias** [comment]
@fernandosjp eu não tenho como editar, mas coloquei genérico pq eu mesmo não saberia dizer.
Seria um tipo de coisa que eu teria postado no forum antes de abrir uma issue. (Para ter um embasamento melhor)

Se eu fosse editar agora talvez eu colocasse "atenção ao .htaccess"

Como o @faribeiro falou que usam o 2.4 não entendo pq o apache funcionou.

**Comment by eberfreitas** [comment]
@JDias faltam detalhes sobre qual foi o erro em si, o que exatamente foi feito pra corrigir... Sem essas infos fica difícil a gente ajudar e ver como podemos pensar em algo melhor. Será que você consegue completar com mais dados?

**Comment by JDias** [comment]
Olá @eberfreitas não precisa me ajudar não, eu já resolvi o meu.

Os erros foram de permissão denied ... (rodando como user não como www-data)

**Comment by JDias** [comment]
mais precisamente ao problema do <IfModule !mod_php7.c> 
eu estou com php7, em teoria.

como eu disse, para mim funcionou com o Require all granted, mas está errado
 (btw, o htaccess esta em utf8?)

é isso. vou tentar ajudar com mais commits e menos cenários.
mas como o @farribeiro resolveu commitar resolvi levar a serio o arquivo  (e não apenas resolver meu problema)

**Comment by JDias** [comment]
Fechando!
