### ISSUE TITLE
Criar fórum da comunidade (Discourse)

### ISSUE THREAD

**Issue by fernandosjp** [portabilis/i-educar#308]
**CONTEXTO:**

Como discutimos no issue #266 e em outros momentos, existe a necessidade de um fórum para a comunidade i-Educar, ou seja, desenvolvedores e usuários finais. O seu papel será:

- Discussões de como instalar a plataforma
- Discussões de como usar funcionalidades
- Suporte entre membros de comunidade
- FAQ da comunidade (sobre o produto e funcionalidades)

**IMPLEMENTAÇÃO:**

A Fundação Lemann irá apoiar a comunidade i-Educar com o primeiro ano de hospedagem do fórum Discourse. Assim conseguimos garantir que temos as ferramentas necessárias para a comunidade se fortalecer neste primeiro ano. Após esse período acreditamos que temos dois possíveis caminhos:

- A mantenedora Portabilis, ou outro ator que estiver próximo poderia hospedar a versão aberta com custos de hospedagem
- Conseguir 2000 estrelas e pedir o apoio de hosting gratuito do Discourse :1st_place_medal:  [referência](https://blog.discourse.org/2016/03/free-discourse-forum-hosting-for-community-friendly-github-projects/)

Mais um incentivo para levarmos o i-Educar para mais municípios e trazer mais desenvolvedores!! :+1:

**Comment by farribeiro** [comment]
Uma meta a almejar, e nada fácil.

**Comment by fernandosjp** [comment]
Concordo @farribeiro! :) O FISL está ai para isso hehe Também acho difícil mas vamos tentar \o/

**Comment by farribeiro** [comment]
Mas @fernandosjp... talvez não seria melhor manter um servidor igual a maioria que tem phpBB? Usando domínio ieducar.org

**Comment by fernandosjp** [comment]
Pode ser uma boa ideia sim! Faremos assim apenas para começar e não precisar perder tempo com isso pois precisamos disso par o FISL em 7 dias. O pessoal está super focado em outras tarefas e seria legal ter uma estrutura que não exija manutenção. Temos um ano para decidir isso. :)

**Comment by JDias** [comment]
Uma outra opção é dizer quanto custa e pedir doações para manutenção. 
(A rimuhosting costumava ser benevolente com projetos open, mas não sei se ainda continua)

**Comment by fernandosjp** [comment]
Também gosto dessa opção @JDias! Mais para frente a comunidade poderia se estruturar para ter doações.
