### ISSUE TITLE
Base path (ieducar fora da raiz do vhost)

### ISSUE THREAD

**Issue by JDias** [portabilis/i-educar#310]
**CONTEXTO:**

Olá, eu comentei um tempo atrás com a caroline, que o i-educar não funciona fora do raiz do vhost:
http://ieducar.sisdipe.com.br/i-educar/ieducar/

**IMPLEMENTAÇÃO:**

eu alterei por alto uns 2 ou 3 includes para usar $temp_base_path = $_SERVER['DOCUMENT_ROOT'].'/i-educar/ieducar'; só para ter algo "funcionando"

eu vi um tempo atrás uma url_helper que talvez pudesse se usado (não me lembro onde se encontra).

**Comment by farribeiro** [comment]
Por gentileza, @JDias , um feedback mais detalhado da resolução deste problema

**Comment by JDias** [comment]
Search and replace @farribeiro ?
Só quis colocar essa questão para terem ciência, talvez o hackzinho do symphony  precise ter o i-educar fora da raiz, mas se for o caso eu mesmo faço esses ajustes.

**Comment by JDias** [comment]
Boa @farribeiro , usar o basepath do htaccess.

Mas não sei se vai resolver no cenário de uso que eu falei, mas valeu o toque :)

Tem 2 coisas que quero tentar:

1-é colocar o front-controller com fallback
2-é tentar fazer um wrap na api existente para uma url restfull (e depois adicionar um auth midlleware a essas rotas)

Esses são os planos.

**Comment by JDias** [comment]
eu realmente não sei o tamanho da encrenca @farribeiro 
estou pensando em usar está abordagem https://devblog.pedro.resende.biz/how-to-migrate-a-legacy-application-to-symfony--/

mas, olhando o código : 
parece que ele utiliza o legacy_app dentro do src https://github.com/pedroresende/legacy-migration-to-symfony/tree/master/src

e fica apenas o front-controller no public https://github.com/pedroresende/legacy-migration-to-symfony/tree/master/public

tenho que ver como ficaria melhor para trabalhar com o i-educar. não tenho ainda uma resposta, apenas um esboço para tentar algo nessa linha.

https://github.com/JDias/i-educar-1/blob/symphony-router/Contrib/Router/Symphony/web/front.php

mas, de pronto, o i-educar tem esta limitação (o que não é showstoper)

**Comment by JDias** [comment]
olá @farribeiro no includes/bootstrap.php parece ter algumas info interessantes, mas não sei se algums códigos existentes no i-educar não usa essas definições, até pq, isso vem antes do bootstraping  (clsBase.inc.php):

```

// Inclui arquivo de bootstrapping
require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/bootstrap.php';
```

outro arquivo interessante é o module/index.php , adivinha? é um front-controller!
