### ISSUE TITLE
Atualização do ambiente de desenvolvimento

### ISSUE THREAD

**Issue by farribeiro** [portabilis/i-educar#311]
> Olá e obrigado por nos ajudar a tornar o i-Educar um projeto melhor. Não esqueça de revisar o nosso [guia de contribuição](https://github.com/portabilis/i-educar/blob/master/CONTRIBUTING.md) para saber melhor como colaborar com a nossa comunidade. Você também pode usar o template abaixo para preencher sua issue:
>
>**CONTEXTO:** Por que esta alteração é importante? Como você usaria isto? Como esta alteração pode beneficiar outros usuários?

Precisamos discussão para atualização dos requisitos do ambiente de desenvolvimento. Alias o projeto PHP no DockerHUB é baseado nesta distribuição 

> **IMPLEMENTAÇÃO:** Não obrigatório, mas sugira uma idéia de como isto poderia ser implementado.

Validar novo ambiente de desenvolvimento

**Comment by farribeiro** [comment]
Link #369

**Comment by farribeiro** [comment]
Link #406

**Comment by edersoares** [comment]
Ambiente se encontra atualizado e controlado.
