### ISSUE TITLE
Erro de 404 caso algo não tenha sido inicializado.

### ISSUE THREAD

**Issue by JDias** [portabilis/i-educar#314]
**CONTEXTO:**

Fui tentar fazer um teste rapido do htaccess e apaguei minha instancia e criei outra, desta vez na raiz do vhost, para não precisar lidar com isso. (evidentemente esqueci do composer e do configuration/ieducar.ini)

Fiz um composer.json e preenchi provavelmente errado o ieducar.ini, recebi um belo 404, quando na verdade o erro não é 404

**IMPLEMENTAÇÃO:**

Depois eu penso em algo, mas acredito que a página de erro poderia ter uma variável mais descritiva.

perceba, em ieducar/include/clsBase.inc.php :

```
if ($GLOBALS['coreExt']['Config']->app->ambiente_inexistente){
    header("Location: /404.html");
}
```

**Comment by JDias** [comment]
A boa noticia é que meu ieducar.ini teoricamente está certo (inicialmente achei que tinha errado as credenciais do banco).

A má noticia é que 404, http://ieducar.sisdipe.com.br/

e pior, o .htaccess 

https://github.com/JDias/i-educar-1/blob/htaccess/ieducar/.htaccess

na linha 53 o certo seria " Require all denied" mas eu usando o php7 ele precisa do "Require all granted" para passar.

ou seja, não só estou com problema no htaccess (já que o que deveria funcionar não funciona), como agora achei um misterioso erro de não inicializar o ambiente! :)

**Comment by JDias** [comment]
eu vou amar aprender o includes/bootstrap.php :)

mas não era o motivo dessa issue. (apesar de agora ter se tornado, mas não tenho como me aprofundar nisso no momento)

essa issue era relativa ao https://github.com/portabilis/i-educar/issues/305

**Comment by JDias** [comment]
eu não sei exatamente ainda pq, mas meu problema é aqui:

```
// tenta carregar as configurações da seção especifica do tenant,
// ex: ao acessar http://tenant.ieducar.com.br será carregado a seção tenant.ieducar.com.br caso exista
if ($coreExt['Config']->hasEnviromentSection($tenantEnv)) {
    $coreExt['Config']->changeEnviroment($tenantEnv);
} else if (!$coreExt['Config']->hasEnviromentSection($tenantEnv) && CORE_EXT_CONFIGURATION_ENV !== "development"){
    $coreExt['Config']->app->ambiente_inexistente = true;
}

```

estou caindo no else if ...

**Comment by farribeiro** [comment]
@DaniloRodrigo o que o @JDias fala é uma melhoria para o arquivo de configuração do servidor web mas enfim o seu problemas se encontra mais errar algum passo da instalação.

Como eu retirei o meu Docker, em favor de um novo sistema de container... Estou quase de mão atadas, acredito que ele consiga executar o compose

**Comment by edersoares** [comment]
@DaniloRodrigo por favor verifique o arquivo `ieducar.ini` que é específico do seu ambiente e veja se o domínio `localhost` ou outro qualquer onde você tenha instalado o i-Educar está presente desta forma:

```ini
...

[localhost : production]
app.database.dbname = ieducar

...
```

Faça este teste por favor, acredito que irá resolver.

**Comment by DaniloRodrigo** [comment]
Olá @edersoares ele não está exatamente assim. Está desse jeito:
...

[production]
app.database.dbname = ieducar

...

Quando tentei colocar o localhost o PHP lançou esse erro: 

Fatal error:  Uncaught Exception: N\xc3\xa3o foi poss\xc3\xadvel estender localhost.

**Comment by edersoares** [comment]
Acho que você colocou o contrário, `[production : localhost]`, o correto é `[localhost : production].

**Comment by DaniloRodrigo** [comment]
Obrigado @edersoares, eu adionei [<ip_da_maquina_virtual> : production] e consegui acessar pelo host. Eu criei uma máquina virtual com ubuntu server e acessei o sistema de fora dessa máquina.

**Comment by farribeiro** [comment]
Isso realmente ficou fora de tópico

**Comment by mizaelmontenegro** [comment]
Este problema ainda persiste na versao 2.8. Fiz a instalação via docker e obtive o 404. A sugestão do @edersoares parece não se aplicar, pois não existe esse arquivo .ini. Alguem mais conseguiu resolver este problema?
