### ISSUE TITLE
Documentação e ORM

### ISSUE THREAD

**Issue by JDias** [portabilis/i-educar#318]
Acho um ponto interessante saber se tem documentação em relação ao ORM atual.

Se pretendem usar o doctrine, existe algum documento pq o doctrine é mais interessante que o eloquent, por exemplo?

(No pano de fundo tem o debate sobre datamapper versus activerecords, acho)

**Comment by eberfreitas** [comment]
Existem conversas de usarmos o DataMapper que o i-Educar já possui mas usa muito pouco:

https://github.com/portabilis/i-educar/blob/master/ieducar/lib/CoreExt/DataMapper.php

A grande maioria das interações com o banco não acontecem via ORM atualmente.

**Comment by JDias** [comment]
Seria interessante que essas conversas fossem públicas @eberfreitas , a um tempo atrás eu seria um grande entusiasta de se manter um framework próprio, hoje eu acho um desperdício dispender energia para isso. (E eu poderia listar meus argumentos se desejar)

E acho que esse debate seria realmente proveitoso conforme o @farribeiro já levantou a bola aqui 
 https://github.com/portabilis/i-educar/issues/291

Heavylift !

E em outra issue ele comenta acerca de outro ponto, que é o código que virá até novembro.

No roadmap está escrito utilizar o doctrine.

Sei que projetos abertos cada um tem a liberdade de fazer o que quiser, mas se tiver um debate aberto é vantajoso pois a pessoa vai saber os pros, contras e eventuais dificuldades de certas abordagens. (E evita ter de responder varias vezes a mesma questão, acho)

**Comment by eberfreitas** [comment]
@JDias quando chegar o memomento de atacar este problema com mais força certamente iremos debater melhor. Por enquanto nossos esforços estão em resolver as pendências priorizadas pelo roadmap.

Sobre usarmos o DataMapper, é algo que já esta pronto. Não haverá novo desenvolvimento. É uma forma de usar algo que o sistema já utiliza em algumas áreas sem precisa readaptar tudo e acho isso super válido, mas confesso que pessoalmente ainda não me envolvi com o DataMapper pra avaliar suas vantagens ou desvantagens.

Fique à vontade pra dar uma olhada no código e traçar estes paralelos. Vai nos ajudar a avaliar melhor como podemos prosseguir :)

**Comment by JDias** [comment]
Ok @eberfreitas , mas se pretendem usar o datamapper do i-educar talvez fosse interessante colocar o datamapper no roadmap ao invés do doctrine?

Sim, ainda tenho muito a aprender sobre o i-educar  😊

**Comment by farribeiro** [comment]
Então utilizar `datamapper` até segunda rodada de discussão

**Comment by JDias** [comment]
eu pretende não descer até o orm... (espero)

**Comment by eberfreitas** [comment]
@JDias como disse, tudo está aberto para discussão. Vamos vendo como as coisas vão rolar até chegarmos nesse ponto. Como disse, pra mim ainda é prematuro discutir sobre o assunto já que falta muito do PSR-2 para finalizarmos, mas fiquem à vontade para buscarem informações tecnicas que nos ajudem a decidir ;)

**Comment by JDias** [comment]
Ok @eberfreitas , como eu disse eu pretendo evitar descer até o orm. Mas concordo, essa me parece ser a discussão, do que ao meu ver, é a mais difícil do roadmap.

**Comment by farribeiro** [comment]
Sim, no que se disseram para mim na #285
