### ISSUE TITLE
o recente PR sobre validação e o roadmap

### ISSUE THREAD

**Issue by JDias** [portabilis/i-educar#321]
Olá @eberfreitas , acho que o PR https://github.com/portabilis/i-educar/pull/292#discussion_r201111572 (que por sinal quase eu ia quebrar a cara ao dizer que o solid é em nível de classe, não de método), ilustra um pouco do que eu quis dizer em https://github.com/portabilis/i-educar/issues/295

Sem prejuízo da abordagem que querem, de tudo ao mesmo tempo agora, não seria interessante abordar as coisas a medida que elas vão acontecendo @farribeiro ?

Ou seja, como previsto no roadmap, o que for refatorado (código novo) ir para a pasta src?

então de forma pratica adicionar namespace ao https://github.com/portabilis/i-educar/blob/master/ieducar/lib/Portabilis/Utils/Validation.php e mover (e/ou copiar) para pasta src (prevista no roadmap) 

(ou algo assim, de forma que possamos distinguir o que é "novo", e inclusive podendo aproveitar as oportunidades do que ficou TODO, como no caso dessa classe o require do user. "pensando alto")

isso não prejudicaria o foco de vocês nas prioridades e permitiria separar o que já foi feito. (e se quiser, apenas copiar, ao invés de mover, não quebraria nada, acho)

**Comment by eberfreitas** [comment]
Oi @JDias acredito que mover as pastas acarretaria num monte de pequenas mudanças em todo o sistema onde ocorrem requires, etc., e pode ficar confuso e complicado de validar tudo. Isso será tratado quando começarmos a trabalhar na migração para PSR-4 em breve. Nosso foco agora está em adequar nosso código de acordo com o PSR-2 e depois partimos pra isso. Acredito que um passo de cada vez seja mais fácil da gente prosseguir sem colocar a carroça na frente dos bois. É fácil a gente tentar fazer de tudo e acabar com pouca coisa feita ou um sistema com mto mais problemas do que antes.

**Comment by JDias** [comment]
Ok @eberfreitas , vocês comandam o show! 😎

**Comment by farribeiro** [comment]
> Sem prejuízo da abordagem que querem, de tudo ao mesmo tempo agora, não seria interessante abordar as coisas a medida que elas vão acontecendo @farribeiro ?

Como a discussão está muito fragmentada, não tenho muita habilidades para te responder. Mas em princípio é """"Não necessariamente"""". 

Já é possível elaborar o ROADMAP para a `v3` (alphas e betas, alike v3.0.0-alpha) desde já, não necessita esperar o fechamento do ciclo `v2` (EoL). Assim que lançar a stable da `v3` podemos já (até antes rascunhar/pensar) o ROADMAP da `v4`.

> Ou seja, como previsto no roadmap, o que for refatorado (código novo) ir para a pasta src?

Este ROADMAP é apenas para clico `v2`.

> ...
>
> isso não prejudicaria o foco de vocês nas prioridades e permitiria separar o que já foi feito. (e se quiser, apenas copiar, ao invés de mover, não quebraria nada, acho)

Não prejudica em já elaborar e aplicar alterações do próximo ROADMAP. Cria-se um branch separado chamado `v3.0.0` assim chegada hora aplica no master e cria-se uma tag

Mas vou pedir ajuda aos universitários @williamespindola !

**Comment by JDias** [comment]
Essa sua sugestão é ainda mais elaborada que a minha @farribeiro 👍
