### ISSUE TITLE
Website no celular

### ISSUE THREAD

**Issue by MarceloCajueiro** [portabilis/i-educar#327]
Precisamos de um MVP que funcione bem no celular. Não precisa ser necessariamente responsivo numa versão inicial, importante é ficar organizado.

**Comment by JDias** [comment]
De pronto eu imagino aumentar a altura do navbar e tirar a parte das "redes associadas" para baixo do sidebar e colocar no footer

**Comment by rsdevigo** [comment]
@JDias O layout passado para a equipe do IFMS possuía uma versão mobile, mas por motivos de tempo tivemos que optar por uma versão desktop, uma vez que, a customização das páginas do Docusaurus é um pouco engessada em certos pontos, por exemplo criação de temas ou inclusão de Libs ou Frameworks CSS.

Mas estamos trabalhando para deixar uma versão mobile e responsivo.

Ps1. A nova versão do Docusaurus prevê uma separação melhor da lógica e da criação de temas e layouts do site.

ps2. Sobre as pastas, o Docusaurus por padrão usa essa pasta en, e por enquanto nos preocupamos em aplicar o layout e não voltado com a internacionalização do site.

**Comment by rsdevigo** [comment]
@JDias Que isso man, não precisa pedir desculpas :), era só para manter as repostas sincronizadas.

**Comment by rsdevigo** [comment]
Sim teremos páginas responsivas :).
O layout continuará o mesmo.

ps: sério que isso é de salvador ? :)

**Comment by JDias** [comment]
Olá @rsdevigo na verdade é uma gíria gringa (Califórnia), mas disseminou em salvador (notadamente villas do Atlântico), meus maiores amigos utilizavam.  O sr resgatou do fundo do baú :)

**Comment by farribeiro** [comment]
Mas como ficou essa issue?
