### ISSUE TITLE
Consolidar últimos posts do blog relacionados ao projeto i-educar

### ISSUE THREAD

**Issue by fernandosjp** [portabilis/i-educar#328]
**CONTEXTO:**

Temos um novo blog e gostaríamos de agrupar as comunicações relacionadas ao projeto desde o final do ano passado por aqui..

**IMPLEMENTAÇÃO:**

Os textos a serem colocados no blog são:

1) [Em 2018, queremos o i-Educar por todo o Brasil](http://webcache.googleusercontent.com/search?q=cache:CtC2lFsoMfYJ:https://softwarepublico.gov.br/social/i-educar/blog/em-2018-queremos-o-i-educar-por-todo-o-brasil&num=1&hl=it&gl=br&strip=1&vwsrc=0)
2) [i-Educar por todo o Brasil: Portabilis e Fundação Lemann](https://webcache.googleusercontent.com/search?q=cache:6d69CXSxbp0J:https://softwarepublico.gov.br/archives/thread/i-educar/i-educar-por-todo-o-brasil-portabilis-e-fundacao-lemann+&cd=3&hl=it&ct=clnk&gl=br)

**Comment by giustin** [comment]
Oi @fernandosjp 

Feito! https://github.com/portabilis/i-educar/pull/331
