### ISSUE TITLE
Publicar site Docusaurus através de ferramenta de CI

### ISSUE THREAD

**Issue by fernandosjp** [portabilis/i-educar#329]
**CONTEXTO:**

Toda vez que adicionamos algum conteúdo ao site precisamos rodar o comando de publicação do Docusaurus para que a mudança seja refletida no site. Para facilitar esse processo sugiro que a gente deixe uma automação em alguma ferramenta de CI.

**IMPLEMENTAÇÃO:**

Para implementação precisamos entender se esta no plano do projeto adotar alguma ferramenta de CI (Travis, Circle CI, ect) e então seguir as instruções do propostas na própria documentação do Docusaurus.
https://docusaurus.io/docs/en/publishing.html#automating-deployments-using-continuous-integration

**Comment by edersoares** [comment]
Pessoal, acho que podemos criar um repositório isolado para a documentação.

Não faz sentido deixar website junto a aplicação, pois mesmo tratando-se da mesma ferramenta, são assuntos, colaboradores, processos e ferramentas distintas.

O que acham?

**Comment by tembra** [comment]
Eu particularmente concordo.
Inclusive é assim que grandes projetos trabalham.

**Comment by fernandosjp** [comment]
@edersoares @tembra, sei que não é um tema que tem uma resposta certa. Olhamos vários projetos abertos de sucesso para entender como começar. Existem projeto das duas maneiras. Usamos como referência Metabase e Prettier que fazem a documentação no mesmo repositório do projeto.

A princípio, o Caju concordou em seguir assim pois com Docusaurus o repositório fica organizado. São criados apenas dois diretórios: `docs`, `website`.

Pessoalmente, acho que existem algumas vantagens de deixar assim. Algumas delas são:

- facilitar sincronização de release do software e documentação
- facilitar integração com Repositório do software público
- gerenciar issues em um único repositório
- facilitar entendimento de novos contribuidores que podem ser mais leigos com github e repositórios

Acham que vale a pena abrirmos um debate sobre isso por aqui ou no fórum? 

A minha ideia com a issue era garantir que o site/docs se manterão atualizados a cada release no master sem a necessidade de comando local mas concordo que pode ficar confuso.

**Comment by rsdevigo** [comment]
Olá pessoal, 
Tudo bem ?

Então sobre essa issue, estamos trabalhando sobre ela, mas para que dê certo precisamos que alguém da portabilis ou que tem acesso ao repositório vincule o repositório ao Travis, seguindo esse mini-tutorial:

1. Go to https://github.com/settings/tokens and generate a new personal access token
2. Using your GitHub account, add the Travis CI app to the repository you want to activate.
3. Open your Travis CI dashboard. The URL looks like https://travis-ci.com/USERNAME/REPO, and navigate to the More options > Setting > Environment Variables section of your repository.
4. Create a new environment variable named GH_TOKEN with your newly generated token as its value, then GH_EMAIL (your email address) and GH_NAME (your GitHub username).

Finalizado isso, podemos criar o arquivo .travis.xml que irá criar uma build do site.

**Comment by vinicelms** [comment]
Bom dia!

Acho importante o que o @rsdevigo pediu, pois hoje ficamos dependentes de um processo de alguém com permissões no repositório **gh-pages** para que o site fique disponível.

Após a aprovação do PR na branch **master** o Travis já poderia providenciar a disponibilização do site na branch correta, tirando dependências humanas do processo.

@edersoares, poderia nos apoiar nisto quando possível?

**Comment by edersoares** [comment]
@vinicelms estou estudando uma maneira de usarmos as credenciais da própria conta da Portabilis para fazer esta integração, assim não depende de token de desenvolvedor. Assim que encontrar eu aviso aqui.

**Comment by edersoares** [comment]
@vinicelms e @rsdevigo tentei encontrar outra forma de fazer a publicação sem informar um token de usuário mas não obtive sucesso.

Criei o PR #370 com o arquivo `.travis.yml` conforme a documentação do Docusaurus e fiz as devidas configurações no repositório da Portabilis no Travis CI.

Peço que verifiquem se está OK. Obrigado.

**Comment by vinicelms** [comment]
Se as variáveis de ambiente foram configuradas, está tudo certo. Pode mandar ver!

**Comment by edersoares** [comment]
Somente pra fins de conhecimento, a publicação da documentação através de CI já está funcionando, assim que um PR for aceito e feito merge, a publicação da documentação será realizada.
