### ISSUE TITLE
alguma orientação

### ISSUE THREAD

**Issue by JDias** [portabilis/i-educar#345]
eu gostaria de alguma orientação.

de acordo com meu "ide" a entrada category do dockblock está deprecated, está realmente deprecated? posso remove-la?

comecei a dar uma olhada no /module/index.php e novamente de acordo com meu "ide" alguns requires dá para ser substituídos por use (nem todos), substitui? e no caso do, por exemplo, require_once 'App/Model/IedFinder.php' , se eu substituo por use App_Model_IedFinder; , meu "ide" me alerta que a classe é importada mas não é usada, remove?

eu vou parar por aqui, por falta de norte, sul, leste e oeste.

eu coloquei um plugin no meu "ide" para listar os TODOs e no ApiExternaController.php tem #TODO ajustar para funcionar com magic getters e setters, mas vi que eles esta utilizando o cURL, e me questiono se seria mais interessante usar algo como http://docs.guzzlephp.org/en/latest/index.html ?

o guzzle parece ser querido por quem usa:
https://stackoverflow.com/questions/36548005/php-why-use-guzzle-instead-of-curl

e parece que o calipher-php está seguindo tbm a tendência:
https://gist.github.com/sloanlance/d070599150ce6633630bfe9730b0e32b

não sei se seria um caso de uso.

**Comment by eberfreitas** [comment]
@JDias recomendo ignorar as notificações do seu IDE a não ser que você esteja buscando oferecer uma contribuição neste sentido. E aí ao invés de simplesmente seguir o que o IDE diz, seria interessante realizar as alterações e testar cada aspecto para ver se realmente não existem efeitos colaterais.

Sobre os docblocks, no momento estamos removendo todos. Isso entra nos ajustes do PSR-2 que estamos fazendo. Posteriormente vamos melhorar este aspecto.

Sobre trocar o curl pelo guzzle, não vejo motivos no momento. Usa curl pode ser um pouco + verboso e repetitito, mas não é algo que está trazendo problemas então podemos avaliar sua adoção mais pro futuro. No mais, estamos ansiosos pra finalizar os ajustes do PSR-2. Qualquer contribuição neste sentido seria maravilhosa.

**Comment by JDias** [comment]
Ok, orientado ....

**Comment by JDias** [comment]
@eberfreitas não sei se interessa, mas compartilhando https://medium.com/@brad_brothers/build-a-better-api-client-with-guzzle-middleware-2ace56868dc7
