### ISSUE TITLE
[Proposta]: Formatação padrão de queries

### ISSUE THREAD

**Issue by eberfreitas** [portabilis/i-educar#347]
Trabalhando nos ajustes para PSR-2 me deparei com vários arquivos que utilizam queries diretamente no código, o que nós devemos melhorar com o futuro, mas que enquanto não acontece, acho que pode ser melhorado.

No geral as queries são "jogadas" no código quebrando contextos e complicando o entendimento do fluxo do programa e dificultando a adaptação para os PSR's.

Tenho então uma proposta de formatação que tenta tratar as queries mais como código mesmo que algo separado pra gente conseguir estruturar e manter os contextos etc. A ideia seria +/- assim. Sintam-se à vontade pra dizer que não presta ou o que poderia ser diferente:

```sql
SELECT
    column1,
    column2
FROM
    table1
INNER JOIN table2 ON (TRUE
    AND table2.table1_id = table1.id)
INNER JOIN table 3 ON (TRUE
    AND table3.table2_id = table2.id
    AND table3.status = table1.status)
WHERE TRUE
    AND table1.name = 'John Doe'
    AND table2.id <> 2
```

Algumas ideias:

- A gente mantem a indentação similar à do código: quando existe um novo contexto a gente indenta com os 4 espaços ao invés de tentar alinhar os comandos;
- A gente usa `TRUE` no início de um `WHERE` ou de um `ON` para: permitir uma consistência visual na lista de condições e permitir ligar e desligar condições facilmente com um comentário, basta colocar `--` na frente da linha e a query não deve quebrar por causa disso. Facilita a debugar;
- Esta formatação deixa mais claro quais são as colunas e tabelas sendo trabalhadas. É só bater o olho e ver em cada linha o que está sendo puxado;
- A gente tem um controle maior do contexto das coisas. Se tivermos uma sub-query por exemplo, podemos fazer assim:

```sql
SELECT
    column1,
    (
        SELECT
            column2
        FROM
            table5
        WHERE TRUE
            AND column2 = 'John Doe'
    ) AS fake_column
FROM
    table1
WHERE TRUE
    column3 = 'Jane Doe'
```

É difícil especificar todos os casos mas as regras principais seriam:

- Utilizar indentação padrão como no código evitando alinhamentos;
- Sempre separar os contextos de forma que cada parte seja facilmente identificável;
- Permitir modificações na query facilmente;
- Permitir debug fácil na query;
- Integração natural ao código em volta da query.

Fica ai a ideia. Boa parte do que foi proposto foi copiado daqui:

https://kvz.io/blog/2009/03/04/sql-formatting/

**Comment by edersoares** [comment]
Excelente iniciativa!

Apenas deixo minha sugestão de utilizar parênteses somente quando houver uma subquery, no caso do exemplo, o `INNER JOIN` poderia ser:

```
..
INNER JOIN table2 ON TRUE
    AND table2.table1_id = table1.id
INNER JOIN table 3 ON TRUE
    AND table3.table2_id = table2.id
    AND table3.status = table1.status
..
```

E usar parênteses apenas se houver uma subquery em sua condição `AND`.

Top!

**Comment by eberfreitas** [comment]
Acho que a regra do parêntesis pode ser de sempre definir um novo contexto ou qualquer instrução que possa tomar + de uma linha como `CASE` ou uma função mais complexa como um substring que pode ficar verboso... Coisas assim... Eu acho que no teu exemplo tá perfeito de tirar...

**Comment by tembra** [comment]
Gostaria de dar minha contribuição quanto as colunas selecionadas.

Recomendo que seja utilizado a `,` (vírgula) antes do nome da coluna, assim se torna _fácil_ adicionar uma nova coluna, pois geralmente as mesmas são adicionadas após a última, onde muitas vezes é esquecido de colocar a vírgula na coluna anterior causando erro na execução da query. Alguns chegam a demorar minutos para encontrar o erro, atrasando o desenvolvimento.

Nesta nova proposta a primeira coluna ficaria identada com 5 caracteres. Claro que o mesmo erro ainda poderia acontecer se adicionado uma nova coluna na primeira posição, mas como disse, isso é pouquíssimo provável, geralmente novas colunas são adicionadas no final, ou ainda, no meio (para organização).

Exemplo com a proposta atual, que irá gerar erro na query:
```sql
SELECT
    column1,
    column2 -- erro aqui pois faltou a vírgula
    new_column -- dev não se atentou e somente adicionou esta linha
FROM
    table1
INNER JOIN table2 ON TRUE
    AND table2.table1_id = table1.id
INNER JOIN table3 ON TRUE
    AND table3.table2_id = table2.id
    AND table3.status = table1.status
WHERE TRUE
    AND table1.name = 'John Doe'
    AND table2.id <> 2
```

Exemplo com a nova proposta:
```sql
SELECT
     column1
    ,column2
    ,new_column
FROM
    table1
INNER JOIN table2 ON TRUE
    AND table2.table1_id = table1.id
INNER JOIN table3 ON TRUE
    AND table3.table2_id = table2.id
    AND table3.status = table1.status
WHERE TRUE
    AND table1.name = 'John Doe'
    AND table2.id <> 2
```

**Comment by farribeiro** [comment]
Amigo @tembra estou adorando suas contribuições, não esquentar muito com isso... das SQL pois vai ser tudo via ORM mais adiante.

**Comment by tembra** [comment]
@farribeiro Huhauhua valeu! Estou ciente sobre o ORM. Li algumas semanas atrás em outra issue. Mas enquanto isso não ocorre, este novo padrão pode ser utilizado para os novos PRs. Ou seja, claro que não vamos converter as queries já existentes, pois seria somente trabalho desnecessário :+1:

**Comment by edersoares** [comment]
Sugestão de padrão para `WHERE` e `CASE` complexo:

```sql
WHERE instituicao.cod_instituicao = $P{instituicao}
    AND escola.cod_escola = $P{escola}
    AND curso.cod_curso = $P{curso}
    AND serie.cod_serie = $P{serie}
    AND turma.cod_turma = $P{turma}
    AND matricula.ano = $P{ano}
    AND view_situacao.cod_situacao = $P{situacao}
    AND NOT EXISTS 
    (
        SELECT 1
        FROM pmieducar.dispensa_disciplina dd
        INNER JOIN pmieducar.dispensa_etapa de 
            ON de.ref_cod_dispensa = dd.cod_dispensa
        WHERE dd.ref_cod_matricula = matricula.cod_matricula
            AND dd.ref_cod_disciplina = $P{ref_cod_componente_curricular}
            AND de.etapa = $P{etapa}
            AND 
            (
                CASE 
                    WHEN 0 = $P{etapa} THEN 
                        TRUE 
                    ELSE 
                        de.etapa = $P{etapa} 
                END
            )
            AND $P{buscar_disciplina}
    )
ORDER BY turma.cod_turma, sequencial_fechamento, nome_aluno_ordena
```

Retirado de um relatório.

**Comment by farribeiro** [comment]
Será que o POSTGRES não tem uma convenção?

**Comment by eberfreitas** [comment]
O SQL Style Guide é um guia de estilos que, ao meu ver, não leva em consideração código SQL que será inserido dentro de outro código como é o caso de 99% das queries que temos no projeto hoje.

Elas podem funcionar muito bem em arquivos .sql stand-alone, mas no momento que você coloca ela como uma string no meio do código PHP, é comum acabar com:

- um bloco confuso de texto onde indentações perdem o significado;
- fica complicado alinhar tudo constantemente (o que acaba causando a falta de alinhamento em algumas partes);
- modificação das queries costuma gerar desalinhamentos que não são corrigidos;
- fica complicado acompanhar quem são os atores envolvidos na query, entender a regra da consulta rapidamente, etc...

**Comment by farribeiro** [comment]
Uma questão, será soft ou hard tabs?

**Comment by farribeiro** [comment]
Tem alguma task para colocar no ORM isso?
