### ISSUE TITLE
Acrescentar todos itens do planejamento técnico ao PROJECTS

### ISSUE THREAD

**Issue by farribeiro** [portabilis/i-educar#350]
> Olá e obrigado por nos ajudar a tornar o i-Educar um projeto melhor. Não esqueça de revisar o nosso [guia de contribuição](https://github.com/portabilis/i-educar/blob/master/CONTRIBUTING.md) para saber melhor como colaborar com a nossa comunidade. Você também pode usar o template abaixo para preencher sua issue:
>
> **CONTEXTO:** Por que esta alteração é importante? Como você usaria isto? Como esta alteração pode beneficiar outros usuários?
>
> **IMPLEMENTAÇÃO:** Não obrigatório, mas sugira uma idéia de como isto poderia ser implementado.

Acrescentar todos itens do planejamento técnico ao ROADMAP (PROJECTS). E também inicio das demais atividades ali relacionadas.

**Comment by farribeiro** [comment]
@jdias e @tembra solicitem um tema do ROADMAP para início imediato

**Comment by JDias** [comment]
Bom, acho que sei pq o @farribeiro abriu essa issue.

Eu falei antes, e vou falar de novo para uma nova tentativa de reflexão.

Não lembro em que issue eu comentei sobre um branch/fork (sem objetivo de merge back), mas não é necessário.

Na minha tentativa de um setup minimalista do front-controller/router do symfony percebi que o composer tem a seguinte entrada:

```
  "autoload": {
    "psr-4": {
      "iEducar\\": "src"
     }
```
mas o diretório src não existe, e ele poderia servir para o intuito inicial de se ter um branch/fork, que é separar o código antigo do código novo, sem quebrar nada.

Então, a minha proposta era colocar no repositório, incorporar o https://github.com/JDias/i-educar-1/tree/symphony-router/Contrib/Router/Symphony , e é exatamente o que já tem no planejamento técnico, a saber:

- router do symfony
- pasta src
- psr4

é um forma de se dar um direcionamento operacional para o que vai ser, sem conflitar com o que existe.

eu estava conversando com o @farribeiro que minha ideia era começar por aí, notadamente fazer um ou dois wrappers para a API que vão ser deprecated, e ir evoluindo, tentando realmente fazer a API no lugar do wrapper, adicionando o bootstrap, o exception, aí tem bastante pela frente.

mas seria uma forma de adiantar, sem atrapalhar, ao mesmo tempo, que ao meu ver, facilitaria.
como eu comentei com o @farribeiro que o @fernandosjp havia concordado que diminuir o escopo das tarefas facilitaria acompanhar o andamento mas ele não se pronunciou sobre essa abordagem, que nada mais é do que plantar sementes para o que já está previsto no planejamento técnico, mas que estava bloqueado pois a prioridade era finalizar primeiramente as tasks que estavam abertas, e acredito que por isso o @farribeiro tenha aberto esta issue.

e com este movimento vai emergir questões como, pq o vendor está na pasta public?  a pasta src tbm não precisa estar na pasta public, e são medida que vão aumentar a segurança, acho.

o @eberfreitas me falou da preferência do pessoal em utilizar o curl ao guzzle, tbm. não vejo motivo pq serem excludentes. Ter o guzzle disponível vai apenas permitir que quem der um "use" nele, ele esteja no ar, não é uma obrigação usar, é uma possibilidade.

Então apesar de ser tudo muito incipiente,minimalista, semente, são movimentos na direção apontada que em nada prejudicaria o que já existe ou o que está sendo trabalhado. e nem tem nada para quebrar a cabeça. vai apenas passar a ter uma pasta src, que poderá receber o código psr4, e um router que poderá utilizar esse código. (eu tentei fazer o bootstrap do i-educar, mas não consegui, mas mesmo sem o bootstrap, é um avanço. tímido, mas avanço)

**Comment by farribeiro** [comment]
Será que podemos dar início ao front controller/symfony + PSR-4?

**Comment by JDias** [comment]
só para complementar, apesar da iniciativa do @farribeiro de importar o skeleton do symfony ter sido rejeitada, eu acredito que para melhor utilização do symfony seria adequado utilizar a estrutura de arquivos recomendada aqui https://symfony.com/doc/current/setup/flex.html

mas que não tem nada a ver com o que falei anteriormente. (são 2 coisas independentes)
