### ISSUE TITLE
Erro ao executar o comando para montar a estrutura do banco

### ISSUE THREAD

**Issue by munizeverton** [portabilis/i-educar#358]
**DESCRIÇÃO:**

Seguindo o tutorial de instalação do projeto, ao executar o passo das seeds, o processo é interrompido pelo erro abaixo:

```
SQLSTATE[42710]: Duplicate object: 7 ERROR: role “ieducar” already exists
```

**OBSERVAÇÕES:**

Verificar a possibilidade de remover a parte do script que tenta criar a role `ieducar`, em `/ieducar/misc/database/seeds/start.sql` linha 7, visto que essa role já é criada no build do container

**Comment by farribeiro** [comment]
Então foi aquela ultima alteração que foi feita?

**Comment by edersoares** [comment]
Como o @farribeiro citou, encontrei o mesmo problema @munizeverton, o PR #348 resolve no meu caso, faça testes para verificar.

Abraço.

**Comment by farribeiro** [comment]
Acredito que a solução do @munziverton esteja mais interessante por retirar redundância

**Comment by munizeverton** [comment]
É isso mesmo @edersoares ! Lembre que você tinha feito mas não achei o PR. 
Pode fazer o merge

**Comment by farribeiro** [comment]
Só digo uma coisa... REMENDO!
