### ISSUE TITLE
Usuário/Role não encontrado

### ISSUE THREAD

**Issue by farribeiro** [portabilis/i-educar#360]
> Olá e obrigado por nos ajudar a tornar o i-Educar um projeto mais estável. Para reportar seu bug use o template abaixo:
>
> **MENU:** Nesta seção deve ser apontado qual o menu no sistema deve ser realizada a alteração.

Phinx

> **DESCRIÇÃO:** Nesta seção deve ser colocado uma descrição do problema ou necessidade.

Rodando o Phinx

> ## OBSERVAÇÕES:
>
>Observações em geral sobre o problema apontado.
>
> ### AMBIENTE:
>
> - Plataforma utilizada (p.ex. Docker, instalação direta): Especialmente Direta
> - Sistema operacional e versão (p.ex. Ubuntu 16.04, Windows 7): openSUSE LEAP 15.0
> - Navegador e versão (p.ex. Chrome 35.9.9.9): ND
> - Outros detalhes importantes:

Ao tentar provisionar tanto dentro quanto fora do docker estou recebendo a seguinte mensagem:
 
```terminal
ieducar@linux-sc16:/srv/www/i-educar> ieducar/vendor/bin/phinx seed:run -s StartingSeed -s StartingForeignKeysSeed
Phinx by Rob Morgan - https://phinx.org. 0.8.1

using config file ./phinx.php
using config parser php
using migration paths 
 - /srv/www/i-educar/ieducar/misc/database/migrations
using seed paths 
 - /srv/www/i-educar/ieducar/misc/database/seeds
warning no environment specified, defaulting to: development
using adapter pgsql
using database ieducar_test

 == StartingSeed: seeding

In PostgresAdapter.php line 72:
                                                                                                                                  
  There was a problem connecting to the database: SQLSTATE[08006] [7] FATAL:  Ident authentication failed for user "scrutinizer"  
                                                                                                                                  

seed:run [-c|--configuration CONFIGURATION] [-p|--parser PARSER] [-e|--environment ENVIRONMENT] [-s|--seed SEED]
```

Por gentileza verificar se está correto o código... certificar

**Comment by edersoares** [comment]
Você deve estar rodando com o ambiente em `testing`, isto irá usar as configurações do Scrutinizer.

**Comment by farribeiro** [comment]
Como corrigir tal problema?

**Comment by edersoares** [comment]
Seu problema está no arquivo `phinx.php`, você deve configurá-lo conforme seu ambiente. 

O arquivo `phinx.php.sample` está configurado para rodar no Scrutinizer.

**Comment by farribeiro** [comment]
Estanho pois eu também alterei e não surtiu efeito

**Comment by munizeverton** [comment]
O PR https://github.com/portabilis/i-educar/pull/361 deve resolver isso.
Eu criei um `phinx.php` só pra uso do scrutinizer. O `phinx.php.sample` já está com as configurações default do banco, para rodar as migrations por dentro do container
