### ISSUE TITLE
warning por uso incorreto de função do PHP

### ISSUE THREAD

**Issue by vitormattos** [portabilis/i-educar#382]
**DESCRIÇÃO:**

no arquivo [clsControlador.inc.php](https://github.com/portabilis/i-educar/blob/master/ieducar/intranet/include/clsControlador.inc.php#L386) linha 386 tem uma chamada para a função strftime que não está correta:
```php
$tempoEmEspera       = abs(time() - strftime("now") - strtotime($user['data_login'])) / 60;
```
Pela lógica, o correto seria apenas `time() - strtotime($user['data_login'])`.

Este problema gera um warning que passa despercebido durante o processo de login.

**AMBIENTE:**

- Docker
- Ubuntu 18.04

**Comment by edersoares** [comment]
Fechado após PR #383.
