### ISSUE TITLE
Extrair o website para um repositório próprio

### ISSUE THREAD

**Issue by eberfreitas** [portabilis/i-educar#394]
Queria colocar pra discussão aqui a possibilidade de removermos o website deste repositório. Eu, particularmente, acho que seria produtivo termos um repositório separado para o website por alguns motivos:

- não me parece existir uma vantagem clara de que o conteúdo do website estando no repositório original vá trazer qualquer benefício imediato pra quem estiver consumindo o i-educar;
- embora exista uma documentação ali, existem tantas outras coisas que não estão diretamente relacionadas com o projeto em si, do ponto de vista de programação, como o blog;
- mexer no website gera um movimento produtivo do ponto de vista de conteúdo mas não agrega valor ao projeto em si na parte de desenvolvimento (tirando algumas documentações importantes);

Eu entendo até certo ponto, que é bem legal termos a documentação do projeto junto com o código, mas não é este exatamente o caso. O website é mais do que a documentação e me parece ser algo que faz mais sentido fora deste repositório.

Enfim, o que vocês acham? Quais seriam bons motivos pra manter? Bons motivos pra tirar?

**Comment by vinicelms** [comment]
Eu fui um defensor de ter tudo no mesmo repositório, pois são apenas dois diretórios que não atrapalham em organização.

Pontos que acredito que ajudem:
- **Stars**: Não temos muitas e segmentar as coisas, poderia atrapalhar caso alguém queira contribuir apenas com a documentação e/ou website. Lembrando que precisamos de 2K para manter o Discourse free como projeto Community.
- **Issues**: Centralização de issues no mesmo repositório, facilitando a gestão de um único repositório
- **Organização**: Documentação também faz parte de um projeto e ter que direcionar para outro repositório para falar da documentação, não me parece muito prático. Concordo que o ter um website não é muito bem o objetivo, mas a vantagem é que o Docusaurus garante a organização e um ecossistema integrado para organizar um pouco as coisas.

**Comment by edersoares** [comment]
@vinicelms concordo no sentido de que podemos segmentar as **starts** do projeto, mas acredito que podemos adicionar no repositório da documentação um lembrete para curtir o repositório do código fonte também.

A questão de issues centralizadas eu discordo, hoje não temos um grande movimento, mas em breve quando mais contribuidores surgirem, serão mais issues tanto para a aplicação quanto para a documentação, sendo que ao meu ver os assuntos são distintos e geralmente os contribuidores não serão os mesmos nos dois repositórios.

A questão organizacional não é um problema, o Docusaurus fica "escondidinho" nas sua pasta.

Porém como os projetos estão no mesmo repositório, corremos o risco que alguém faça um PR de documentação, que dificilmente um dev irá olhar, com o código fonte desatualizado, o PR poderá conter esses arquivos que serão mesclados a `master` quebrando a aplicação.

Também se torna possível acrescentar membros exclusivos ao repositório de documentação, elegendo líderes que tenham permissão para mesclar conteúdo a `master`, não necessitando assim, aguardar um desenvolvedor aceitar as alterações.

O repositório da aplicação ficará menor em termos de espaço, log e arquivos, facilitando assim as consultas ao histórico do Git pelos desenvolvedores. Acredito que para contribuidores de documentação também será útil esta parte.

E por último, poderemos versionar e criar releases individuais para a documentação.

Eu acho que é boa a ideia que o @eberfreitas propôs 😄

**Comment by vinicelms** [comment]
Concordo com praticamente todos os seus pontos, mas a ideia seria que a aplicação seguisse o mesmo fluxo da documentação: Atualizou ou lançou uma feature nova, isso também deveria ser refletido na doc.

Meu receio é este outro repositório ficar esquecido, pois como não faz parte da release, começaria a entrar no esquecimento. Documentação não é fácil organizar, manter e garantir compreensão de todos, então é um tema complexo para se manter.

Se sair do repo oficial e cair no esquecimento, nunca mais volta e se tornará lenda. Não deixando isso acontecer, o lugar é o de menos.

**Comment by farribeiro** [comment]
Eu apoio a saída e a manutenção

Ambos @vinicelms e @eberfreitas tem uma verdade, mas é um dilema. Documentação faz parte do projeto mas não é legal manter as issues relacionada a documentação no mesmo.

Pode assim fazer um sub-modulo.

**Comment by vitormattos** [comment]
o caminho talvez seja ter uma organização chamada `i-educar` com 2 projetos: `i-educar` e `site`.

Em relação a issues não vejo qual a importância de estar tudo no mesmo repo, pra mim é até prejudicial pois junta issue do site com issue do projeto.

**Comment by farribeiro** [comment]
Então, a minha recomendação é deixar os documentos neste projeto como SUB MODULO

**Comment by edersoares** [comment]
Boa ideia esta do @farribeiro, assim podemos mantê-los juntos, mesmo estão separados.

E eu acredito que os contribuidores que irão ajudar na documentação terão mais autonomia para definir processos, issues, pull request em um repositório a parte.

**Comment by farribeiro** [comment]
@edersoares dá para fazer com iReports tb

**Comment by vinicelms** [comment]
Chegamos a qual definição da documentação? Considero interessante ter a documentação no mesmo repositório, pois pensamos em ter uma documentação simples apenas com a criação de dois diretórios. Mesmo não estando no mesmo repositório, precisamos finalizar issues uma issue que já foi discutida.

**Comment by farribeiro** [comment]
@vinicelms solicite definição e alteração do ROADMAP para esta questão.
