### ISSUE TITLE
Remover pasta `vendors` do histórico do git

### ISSUE THREAD

**Issue by eberfreitas** [portabilis/i-educar#395]
Antigamente a pasta `vendors` era comitada em conjunto com o projeto. Isso fez com que o histórico ficasse demasiadamente grande. Quando a gente faz um clone do projeto podemos sentir o quanto demora, em parte, por causa destes arquivos que não estão mais presentes mas são carregados no histórico.

Se não me engano foi o @vitormattos que sugeriu fazermos isso. Podemos usar o próprio git ou o bfg. Seria necessário analisar os impactos das mudanças dos hashes em commits antigos.

**Comment by vitormattos** [comment]
Isto resolve:

https://dalibornasevic.com/posts/2-permanently-remove-files-and-folders-from-a-git-repository

O impacto é que é removido qualquer referência a pasta vendor no log, nada mais é impactado além disto.

**Comment by edersoares** [comment]
Muito bacana, vamos limpar a casa!

**Comment by farribeiro** [comment]
BFG tb atende a necessidade, como relatado anteriormente pelo @eberfreitas / @edersoares

**Comment by eberfreitas** [comment]
@vitormattos se não me engano, justamente por remover as referências, o cálculo do sha1 é modificado então você perde referência de commits antigos. Na documentação do filter-branch tem uma notificação sobre isso:

> WARNING! The rewritten history will have different object names for all the objects and will not converge with the original branch. You will not be able to easily push and distribute the rewritten branch on top of the original branch. Please do not use this command if you do not know the full implications, and avoid using it anyway, if a simple single commit would suffice to fix your problem. (See the "RECOVERING FROM UPSTREAM REBASE" section in git-rebase[1] for further information about rewriting published history.)

https://git-scm.com/docs/git-filter-branch

**Comment by farribeiro** [comment]
Melhor chamar ajuda dos universitários:

https://t.me/GitBrasil

**Comment by vitormattos** [comment]
@eberfreitas o código atual não se perderá.

**Comment by vitormattos** [comment]
Executei este comando antes:

```bash
du -h
```
total: `162M`

Executei em seguida a remoçao total da vendor e arquivos phar no projeto:
```bash
git filter-branch --force --index-filter 'git rm -rf --cached --ignore-unmatch *.phar' --prune-empty --tag-name-filter cat -- --all
git filter-branch --force --index-filter 'git rm -rf --cached --ignore-unmatch vendor' --prune-empty --tag-name-filter cat -- --all
git filter-branch --force --index-filter 'git rm -rf --cached --ignore-unmatch ieducar/vendor' --prune-empty --tag-name-filter cat -- --all
git for-each-ref --format='delete %(refname)' refs/original | git update-ref --stdin
git reflog expire --expire=now --all
git gc --prune=now
```

E o resultado depois:
Total: `116M`

**Comment by edersoares** [comment]
Bacana o comando @vitormattos, vamos testar e executar no repositório interno e neste aqui a fim de limparmos em ambos e mantermos sincronizados.

Iremos atualizar aqui após feito.

**Comment by farribeiro** [comment]
Eu acho que o BFG é safe nesse aspecto.

**Comment by farribeiro** [comment]
@vitormattos deve haver mais referências sem ser esta pasta por que infla
