### ISSUE TITLE
Instalação sem docker

### ISSUE THREAD

**Issue by DaniloRodrigo** [portabilis/i-educar#406]
pessoal, como agora o projeto esta sendo mantido aqui o tutorial de instalação ainda funciona do mesmo jeito caso eu não queira usar o docker? Percebi que a pasta scripts foi removida e na pagina antiga ela era usada no processo. Como devo fazer agora?

Agradeço desde já.

**Comment by eberfreitas** [comment]
@DaniloRodrigo dá uma olhada nos arquivos Dockerfile que dão uma ideia bem clara dos passos necessários pra realizar a instalação sem o Docker. Não é um script nem um tutorial tranquilo mas é um primeiro passo. Estamos vendo outras formas de instalar mas espero que isso ajude ;)

**Comment by farribeiro** [comment]
Repostando... https://forum.ieducar.org/t/onde-encontrar-um-manual-de-instalacao/157/7?u=farribeiro

>Eu realmente tentei atualizar um manual de instalação... e devido a muitos erros e complicações deixei como **DEPRECATED** e não fiz um novo tutorial pois seria inviável. Melhor o time da Portabilis atualizar os requisitos mínimos ( Issue [#311](https://github.com/portabilis/i-educar/issues/311) ) para a aplicação. Atualmente requer **PHP v7.0.x** e **PostgreSQL 9.5** e as distribuições atualmente não empacota por padrão estes requisitos.
>
> Eu tinha sugerido anteriormente em fazer como a aplicação nvm/rvm, pois aplicaria já as dependências da pilha LAPP ( Issue [#232](https://github.com/portabilis/i-educar/issues/232) ) e o próprio aplicativo ao estilo ( PR [#379](https://github.com/portabilis/i-educar/pull/379) ) :
>
> ```
> curl <URL> | bash
> ```
>
> Estão elaborando um Wizard ( Issue [#386](https://github.com/portabilis/i-educar/issues/386) ) e/ou usar ansible ( Issue [#232](https://github.com/portabilis/i-educar/issues/232) ) para instalação (leia-se deploy) das dependencias. E infelizmente acho inviável.
>
> E a configuração (leia-se personalização) da aplicação estilo wordpress.

**Comment by DaniloRodrigo** [comment]
Valeu @eberfreitas e @farribeiro, ajudaram demais sim, vou analisar direito e tentar rodar sem o docker pra ver a possibilidade de implantação em um ambiente real.
Agradeço demais a ajuda.
