### ISSUE TITLE
Login para pais e alunos (e api gateway)

### ISSUE THREAD

**Issue by JDias** [portabilis/i-educar#407]
Alguém tem interesse no tema?
Alguém tem opinião acerca da abordagem de api gateway?
 **edited**
Como agora tem suporte laravel, a pergunta poderia ser : "como permitir utilizar o passport/socialite" com o ieducar, acho.

Basicamente, acho, que se resume ao model "users", e qual a visão de vocês em relação a ele.

**Comment by farribeiro** [comment]
Eu tenho, até porque fazer webservices e federação é umas das metas que gostaria no projeto

**Comment by farribeiro** [comment]
## TEMA ACESSO EXTERNO

Tem que ter muita cautela que aluno ou pais terem acesso, pode ocorrer fraude em disponibilizar tais informações.  Classificando informações relevantes e de baixo impacto/fraude.

**Comment by JDias** [comment]
Fabio,
Me refiro no momento exclusivamente a uma coisa: user/auth .

Acredito que ter um model user definido é importante e talvez a api gateway seja a melhor forma para se ter uma "padronização" user/auth.

Foi SÓ a isso que me referi.

**Comment by farribeiro** [comment]
O auth ideal pro i-Educar é utilizar o sistema de identificação digital brasileiro, nada de oAuth

**Comment by JDias** [comment]
Kkkk, pergunto se tem algo nesse sentido, seja qual for a específicação.

De que forma posso identificar e autorizar um aluno? Se é que alguém pensa sobre este assunto.
