### ISSUE TITLE
Implementar testes marcados como skipped em SituacaoTest.php

### ISSUE THREAD

**Issue by eberfreitas** [portabilis/i-educar#414]
Alguns testes antigos do projeto não estavam passando, por vários motivos. Esses testes foram marcados como skipped.

A idéia desta issue é ajustar ou reescrever esses testes, para que eles passem.

Referente ao arquivo `ieducar/tests/Unit/Modules/Service/SituacaoTest.php`.

**Comment by DaniloBenevides** [comment]
Olá, como está o andamento desta issue ? Posso trabalhar nela ?

**Comment by edersoares** [comment]
@DaniloBenevides o @vitormattos fez alguma coisa referente a isso, mas a gente chegou em um impasse quando a regra de negócio e ainda não foi definido.

Mas em todo caso, temos diversos testes marcados como skipped, então pode se aventurar em qualquer um.
