### ISSUE TITLE
Aplicar PSR-2

### ISSUE THREAD

**Issue by munizeverton** [portabilis/i-educar#424]
No momento, temos muitos arquivos sem padrão de código. Queremos por meio dessa issue, aplicar as regras de estilo contidas na [PSR-2](https://www.php-fig.org/psr/psr-2/) e remover alguns comentários antigos e desnecessários

Para trabalhar nisso, siga os passos abaixo:
 - Escolha um arquivo ou diretório para trabalhar e comente aqui nessa issue. Isso vai nos ajudar a organizar o trabalho.
 - Rode a ferramenta `php-cs-fixer` (`ieducar/vendor/bin/php-cs-fixer fix CaminhoDoArquivo.php`)
 - Verifique se os ajustes foram aplicados corretamente. Nem sempre o php-cs-fixer ajusta tudo da melhor forma
 - Abra o arquivo e remova os blocos de comentários desnecessários. Eles estão localizados no topo dos arquivos, e normalmente tratam da licença do software
 - Ofereça um Pull Request referenciando essa issue

**Update**
O PRS-2 já foi aplicado em alguns diretórios. Lembre-se se escolher um com uma quantidade significativa de arquivos para trabalhar

**Comment by jashk** [comment]
Oi,

Eu fiz um pull request com correção no src /, eu gostaria de saber o que outros diretórios gostaria de rever para aplicar a correção

abs.

**Comment by farribeiro** [comment]
Conforme disse na #427 tem que já aplicando a PSR-2

**Comment by farribeiro** [comment]
@munizeverton mudou o estilo da tarefa? Conforme iamos fazendo, por exemplo na #282?

**Comment by farribeiro** [comment]
Uma outra coisa que quero que atente... https://github.com/portabilis/i-educar/projects/2

**Comment by victorhsanjos** [comment]
Olá,

Vou contribuir com o diretório `modules/Docente`.

**Comment by farribeiro** [comment]
#hacktoberfest

**Comment by eberfreitas** [comment]
@jashk mandei uma mensagem no seu PR sobre outras pastas que precisam de ajustes :) Obrigado por participar!

**Comment by jashk** [comment]
Hola @eberfreitas 
Entendi, 
vou fazer ajustes para fazer um update no ieducar/lib/Utils

Obrigado pelo feedback

**Comment by eberfreitas** [comment]
@victorhsanjos me parece que o @jashk já está atacando essa pasta. Poderia escolher alguma similar? Vlw!

**Comment by victorhsanjos** [comment]
> @victorhsanjos me parece que o @jashk já está atacando essa pasta. Poderia escolher alguma similar? Vlw!

Observei agora que ele estava fazendo! Acabei de terminar e enviar a PR. Vou fazer de outra. 
Posso me basear por aqui [link](https://github.com/portabilis/i-educar/projects/2)?

**Comment by eberfreitas** [comment]
Caramba, acabei de ver que vc mandou o PR :( @jashk vc já começou?

Pode usar o link sim @victorhsanjos :) Só dá uma olhadinha antes na pasta pra ver se já não tem mta coisa ajustada e tente pegar pastas com menos arquivos pra gente conseguir fazer o review mais tranquilamente :) Valeu pelo help!

**Comment by jashk** [comment]
Envíe  un PR con ieducar/lib/Portabilis/

**Comment by jashk** [comment]
estou ttabalhando na ruta i-educar/lib/Core/

**Comment by leonampd** [comment]
Fala pessoal, tudo bem?

Vou atuar na `i-educar/ieducar/modules/Biblioteca`, `i-educar/ieducar/modules/ComponenteCurricular`, `i-educar/ieducar/modules/Configuração` e `i-educar/ieducar/modules/Docente`

**Comment by robertoarruda** [comment]
Instalar o [StyleCI](https://styleci.io) no CI, é uma maneira de forçar o dev sempre ajustar o estilo do código alterado no PR. E também evita as alterações fora de padrão.

**Comment by thiagobfiorenza** [comment]
Para conhecimento de todos, PSR-2 foi descontinuada e agora PSR-12 é recomendada: https://www.php-fig.org/psr/psr-2/

> Deprecated - As of 2019-08-10 PSR-2 has been marked as deprecated. PSR-12 is now recommended as an alternative.

**Comment by vicentimartins** [comment]
Aparentemente esta issue foi resolvida e merge feito. Existe algum motivo para esta issue permanecer aberta? Algum path que ainda necessita destes ajustes?

**Comment by edersoares** [comment]
@vicentimartins ainda existem inúmeros arquivos que a devem ser aplicados style code, por hora não há ninguém trabalhando.

**Comment by vicentimartins** [comment]
Ok @edersoares vou trabalhar sobre essa issue.

**Comment by edersoares** [comment]
Fechando por inatividade.
