### ISSUE TITLE
Aplicação da marca nova i-Educar (restrito a elementos visuais e logo)

### ISSUE THREAD

**Issue by MarceloCajueiro** [portabilis/i-educar#455]
Foi feito a identidade visual da marca i-Educar, agora como uma versão inicial, queremos aplicar a nova paleta de cores no i-educar.

## Ações:
- [ ] Prototipar e validar na comunidade
- [ ] Desenvolver

**Comment by jrbarros** [comment]
Esse ponto deixou de ser prioridade e algumas mudanças foram feitas ao longo do tempo e esquecidas de mencionar aqui.
