### ISSUE TITLE
Comportamento estranho ao pegar situação de componente curricular

### ISSUE THREAD

**Issue by vitormattos** [portabilis/i-educar#475]
**DESCRIÇÃO:**

Achei dois comportamentos esquisitos na classe Boletim.

1 - o método [getSituacaoComponentesCurriculares](https://github.com/portabilis/i-educar/blob/master/ieducar/modules/Avaliacao/Service/Boletim.php#L1824) passou por refactor e a situação geral não é atualizada no refactor que sofreu faz alguns anos.

Comportamento esperado nos testes que estão marcados como skipped pois estão quebrando:

- Caso a matrícula seja, por exemplo, reprovada e 1 componente curricular apenas e aprovada em todos os outros, o status geral deveria ser de reprovado. Hoje o método está retornando sempre aprovado.

Na linha [1827](https://github.com/portabilis/i-educar/blob/master/ieducar/modules/Avaliacao/Service/Boletim.php#L1827) é definido a situação porém atualmente esta situação não é alterada durante a execução do método.

Proposta de solução:

![image](https://user-images.githubusercontent.com/1079143/50516064-b2ed2d80-0a8f-11e9-87f4-f671820cc841.png)

2 - o método [getSituacaoNotas](https://github.com/portabilis/i-educar/blob/master/ieducar/modules/Avaliacao/Service/Boletim.php#L1395) também passou por refactor e ao invés de gerar a situação individual por componente curricular, se a matrícula X for aprovada em todos os componentes curriculares exceto em um, todos os outros componentes curriculares estão recebendo situação de reprovados.

Comportamento esperado nos testes que estão marcados como skipped pois estão quebrando:

- Caso as notas da matrícula no componente curricular A sejam de reprovação e nos componentes curriculares B, C e D sejam de aprovação, deveria retornar estas situações nos componentes curriculares ao invés de aplicar situação de reprovação para todos os componentes curriculares.

Não realizei proposta de solução para este método pois o esforço seria maior e achei melhor antes trazer para que outras pessoas possam auxiliar na análise do caso.

**AMBIENTE:**

- Docker

**Comment by edersoares** [comment]
@vitormattos vamos analisar internamente esta questão, provavelmente o comportamento mudou, e muito do código está "sobrando". Comunico aqui assim que conseguir, obrigado!

**Comment by edersoares** [comment]
Em resposta ao conteúdo, estamos reestruturando a documentação do sistema de faltas e notas para determinar as funcionalidades atendidas a fim de corrigir possíveis problemas como este, não temos como determinar um prazo, mas o trabalho está em andamento e assim que tivermos a análise concluída iremos divulgá-la.

**Comment by vitormattos** [comment]
Excelente. Pode associar esta issue as issues que se derivarem da reestruturação da documentação do sistema de faltas e encerrá-la assim que estas questões forem sanadas.
