### ISSUE TITLE
Erro ao tentar lançar uma nota

### ISSUE THREAD

**Issue by seducflores** [portabilis/i-educar#481]
**MENU:**

Escola->Lançamento->Faltas e Notas

**DESCRIÇÃO:**

ao tentar inserir qualquer nota o sistema dispara a exceção:

Exception: Erro ao executar uma ação no banco de dados: SQL invalido: INSERT INTO modules.nota_componente_curricular_media (nota_aluno_id, componente_curricular_id, media, media_arredondada, etapa) VALUES ('3', '3', '2,5', '2,5', '1') RETURNING nota_aluno_id,componente_curricular_id

**OBSERVAÇÕES:**

os valores numéricos estão com vírgulas

**AMBIENTE:**

- Plataforma utilizada: instalação direta
- Sistema operacional e versão: Ubuntu 16.04 (VirtualBox)
- Navegador e versão: Chromium Versão 71.0.3578.98

**Comment by edersoares** [comment]
@seducflores parece problema de locale do servidor. Qual versão do i-Educar você está utilizando?

**Comment by edersoares** [comment]
@seducflores conseguiu resolver o problema?
