### ISSUE TITLE
Adicionar suporte ao Apache

### ISSUE THREAD

**Issue by eberfreitas** [portabilis/i-educar#484]
Atualmente iremos dar suporte apenas ao nginx. 
É interessante termos os ajustes necessários pro sistema funcionar facilmente no Apache também.

**Comment by twisterbr** [comment]
Bom dia pessoal!
Alguma novidade sobre suporte ao apache?

**Comment by edersoares** [comment]
@twisterbr foi feito no PR https://github.com/portabilis/i-educar/pull/592 a adição do suporte ao Apache, consegue fazer o teste?
