### ISSUE TITLE
Modulo de controle Orçamentário

### ISSUE THREAD

**Issue by marcosjmfilho** [portabilis/i-educar#493]
Para controle de recursos dos programas PDE e PDDE.
Junto com as prefeituras estaremos realizando o levantamento de requisitos.
Está marcado uma call com @vitormattos dia 26/03/2019 as 20:00

**Comment by edersoares** [comment]
@marcosjmfilho houve e/ou haverá algum progresso deste tópico?

**Comment by marcosjmfilho** [comment]
@edersoares Não descartamos a implementação, mas não é prioridade para esse ano.
Retornarei essa atividade no próximo período letivo.

**Comment by Ertonilson** [comment]
Sugiro que seja incluso na página de instalação do Ieducar, os módulos que o usuário deseja usar, incluindo os já existentes: Biblioteca e Transporte escolar e os possíveis como o do exemplo (controle orçamentário) e ainda o da Alimentação escolar. Sendo estes optativos para o usuário. Assim, cada membro da comunidade poderia ter liberdade de criar um módulo para deixá-lo disponível no momento da instalação bem como dar suporte ao mesmo.

**Comment by edersoares** [comment]
Fechando por inatividade.
