### ISSUE TITLE
Setor do cadastro de funcionário

### ISSUE THREAD

**Issue by edersoares** [portabilis/i-educar#502]
**CONTEXTO:**

Após o estudo e remoção do schema `pmidrh` no PR #501, foi identificado que a tabela `pmidrh`.`setor` era referenciada pela coluna `ref_cod_setor_new` da tabela `portal.funcionario`. Será preciso prever uma migração ou a remoção desta coluna antes de fazer o upgrade da versão `2.1` para a `2.2`.

**IMPLEMENTAÇÃO:**

É interessante criar um novo cadastro de setores para melhor organizar os servidores (funcionários) caso haja necessidade.

**Comment by jrbarros** [comment]
PR que ajusta essa issue foi resolvido  https://github.com/portabilis/i-educar/pull/501 😄
