### ISSUE TITLE
[2.2] Converter migrations de `inserts` em `seeders`

### ISSUE THREAD

**Issue by edersoares** [portabilis/i-educar#538]
**CONTEXTO:**

Estamos trabalhando na reestruturação do banco de dados do i-Educar e para melhorá-lo precisamos converter todas as migrations de "inserts" em "seeder".

Isso irá permitir migrar toda a estrutura do banco de dados sem se preocupar com os dados em si, muito útil em testes automatizados e poderemos semeá-los a qualquer momento, na instalação da aplicação ou até mesmo em um teste.

**IMPLEMENTAÇÃO:**

Analisar e converter todas as migrations que o nome inicia em `2019_01_01_7*******` para seeder do Laravel.

```bash
# Exemplo para a migration 2019_01_01_700001_insert_acesso_sistema_table
php artisan make:seeder DefaultAcessoSistemaTableSeeder
```

**Comment by DaniloBenevides** [comment]
Olá Éder, tudo bem? Posso trabalhar nessa issue?

**Comment by edersoares** [comment]
Olá, Danilo, pode sim!

Lembre-se apenas utilizar a branch [2.2](https://github.com/portabilis/i-educar/tree/2.2) como basee ao abrir o pull request apontar para ela também.

Bom trabalho!

**Comment by garaujodev** [comment]
Essa issue já foi concluida?

**Comment by DaniloBenevides** [comment]
Ola @garaujodev, creio que estou finalizando essa semana.

**Comment by garaujodev** [comment]
Ah sim, show de bola! Vou procurar alguma outra task que eu possa trabalhar então. Bom trabalho.

**Comment by edersoares** [comment]
Obrigado @DaniloBenevides 😄
