### ISSUE TITLE
Erro ao tentar matricular aluno com dependência

### ISSUE THREAD

**Issue by robson-alcantara** [portabilis/i-educar#548]
**MENU:**

Escola -> Cadastro -> Alunos -> < seleciona aluno > -> Nova matrícula

**DESCRIÇÃO:**

Ao tentar cadastrar um aluno com dependência o sistema informa que ultrapassou a quantidade com dependência, porém não informa na tela qual é essa quantidade. 

Na linha 976 do arquivo i-educar/ieducar/intranet/educar_matricula_cad.php contêm o seguinte código que informa a quantidade máxima de alunos com dependência:

SELECT regra_avaliacao.qtd_matriculas_dependencia
FROM pmieducar.serie
INNER JOIN modules.regra_avaliacao ON regra_avaliacao.id = serie.regra_avaliacao_id)
WHERE serie.cod_serie = {$this->ref_cod_serie};

Porém serie.regra_avaliacao_id é vazio. Um usuário do forúm informou que esta coluna é obsoleta.

**AMBIENTE:**

- Instalação direta
- Sistema operacional: Lubuntu 16.04
- Navegador: Chrome

**Comment by edersoares** [comment]
@robson-alcantara foi feita uma correção para este problema, é possível você atualizar o sistema e validar o funcionamento novamente?

**Comment by robson-alcantara** [comment]
Oi @edersoares , no momento não é possível atualizar o sistema, já que por enquanto estamos apenas com a versão de produção e operando. No momento certo atualizaremos o sistema e averíguo a correção. Obrigado. Irei fechar a 'issue' e se ainda houver problema, reabro.
