### ISSUE TITLE
Relatórios não são exibidos após atualização para versão 2.1.11 em diante

### ISSUE THREAD

**Issue by josafa2018** [portabilis/i-educar#575]
**MENU:**

Todos os menus que contém relatórios.

**DESCRIÇÃO:**

Após atualização para versão 2.1.11 os relatórios deixaram de ser exibidos no browser.  

**OBSERVAÇÕES:**

Configurei o browser pra não exibir o pdf, o que fez com que o arquivo fosse baixado, ao abrir o arquivo com notepad++ notei que o mesmo estava corrompido, havia um código html no inicio do arquivo e mais em baixo o código pdf.

Não sei se essa é a solução mais adequada, mas consegui resolver da seguinte maneira:
- Editei o arquivo ieducar/lib/Portabilis/Controller/ReportCoreController.php, e após a linha 132, inseri uma linha com o código:
<code>$result = ob_get_contents();</code>
com isso os relatório voltaram a funcionar normalmente.

**AMBIENTE:**

- Plataforma utilizada (Docker):
- Sistema operacional e versão (Debian 9):
- Navegador e versão (Chrome 74.0.3729, Edge 42.17134, Chromium 73.0.3683):

**Comment by edersoares** [comment]
@josafa2018 foi feita uma correção, é possível você atualizar o sistema e validar se o funcionamento está correto agora?

**Comment by josafa2018** [comment]
@edersoares, sim atualizei o sistema e o erro foi corrigido, os relatórios estão sendo exibindo corretamente, porém a atualização acredito que na branch permissoes, fez que somente usuários de nível poli-institucional conseguissem acesso aos relátorios, mesmo setando todas as permissões, ao selecionar qualquer relatório para imprimir, volta pra tela inicial do sistema, não exibindo nem mesmo a tela de filtro dos relatórios

**Comment by edersoares** [comment]
@josafa2018 veja se atualizou também a branch de relatórios e se o tipo de usuário tem permissão de acesso em Configurações > Usuários > Tipos de usuário.

**Comment by josafa2018** [comment]
Na release 2.1.14 os relatórios não estão atualizados com a branch de relatórios o que resolvi fazendo o clone o repositório dos relatórios.

**Comment by edersoares** [comment]
@josafa2018 o build da release 2.1.14 foi refeito, se você puder, faça o teste para nós encerrarmos a issue.

Obrigado.

**Comment by josafa2018** [comment]
Agora sim, tudo ok!
