### ISSUE TITLE
Upgrade de 1.1.0 para 2.1. É possível?

### ISSUE THREAD

**Issue by twisterbr** [portabilis/i-educar#581]
Estou precisando atualizar o servidor para PHP7 e como o ieducar 1.1 não é suportado nessa versão, gostaria de saber se é possível atualizá-lo para 2.1. Não encontrei documentações sobre este upgrade em lugar algum.
Obrigado.

**Comment by edersoares** [comment]
@twisterbr a versão 2.0 foi construída pela Portabilis em cima da 1.0, porém muitas melhorias foram feitas e não existe hoje um migrador automático, o caso teria que ser estudado, já que existem também vários forks da versão 1.0.

**Comment by edersoares** [comment]
@twisterbr encontrou uma solução para resolver a migração?

**Comment by Bonot** [comment]
Devido a falta de mais informações essa issue estará sendo encerrada.
