### ISSUE TITLE
Erro ao realizar deploy

### ISSUE THREAD

**Issue by arlenmendes** [portabilis/i-educar#589]
**DESCRIÇÃO:**

Estou tentando realizar a instalação/deploy do sistema. Todos os passos do `/install.php` estão ok. Mas no 3 passo (criando usuário admin) ele da um alert de erro e pede para verificar os logs. A tela atualiza e fala que minha instalação está concluída. Mas não consigo logar nem nada.

Segue o erro de log. Que ocorre quando tenta atualizar a senha do usuário admin.

`[2019-06-06 19:16:00] production.ERROR: SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(32) (SQL: UPDATE portal.funcionario SET senha = $2y$10$sgSpDRIYTbXYWFuDsd4nA.wS4aypz5pAFgChKGb1ZoreDi2tTbgZ. WHERE matricula = admin) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 22001): SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(32) (SQL: UPDATE portal.funcionario SET senha = $2y$10$sgSpDRIYTbXYWFuDsd4nA.wS4aypz5pAFgChKGb1ZoreDi2tTbgZ. WHERE matricula = admin) at /home/ubuntu/ieducar-2.1.14/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(32) at /home/ubuntu/ieducar-2.1.14/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119, PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(32) at /home/ubuntu/ieducar-2.1.14/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)`

**AMBIENTE:**

- Plataforma utilizada: nstalação direta
- Sistema operacional e versão: Ubuntu 18.04

**Comment by edersoares** [comment]
@arlenmendes todas as migrations foram rodadas? Parece que o campo `senha` aceita apenas 32 caracteres, sendo que o necessário é no mínimo 60.

**Comment by arlenmendes** [comment]
> @arlenmendes todas as migrations foram rodadas? Parece que o campo `senha` aceita apenas 32 caracteres, sendo que o necessário é no mínimo 60.

Eu acredito que sim, pois ele passa pelo 'Configurando banco de dados'. Só da erro na operação seguinte, que é essa do admin. Tentei na versão 9.5 e 11 do postgres. E continuou o erro no mesmo local.

**Comment by arlenmendes** [comment]
@edersoares Boa tarde amigo. Atualizei a versão para 0 2.1.15, e continuei com o mesmo erro :(

[2019-06-17 14:10:29] production.ERROR: SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(32) (SQL: UPDATE portal.funcionario SET senha = $2y$10$BU7B8BpV8nbz7uHzMopXfeu4bh/3D44m10gEVkQkKJ9bu.6Dq9BVK WHERE matricula = admin) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 22001): SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(32) (SQL: UPDATE portal.funcionario SET senha = $2y$10$BU7B8BpV8nbz7uHzMopXfeu4bh/3D44m10gEVkQkKJ9bu.6Dq9BVK WHERE matricula = admin) at /home/ubuntu/ieducar-2.1.15/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(32) at /home/ubuntu/ieducar-2.1.15/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119, PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(32) at /home/ubuntu/ieducar-2.1.15/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)

**Comment by arlenmendes** [comment]
Acabei de ver que você subiu a 2.1.16, rs... atualizei a acabei tendo o mesmo problema.

**Comment by edersoares** [comment]
@arlenmendes este erro já foi corrigido, na versão 2.1.15, você  consegue fazer uma instalação do zero em outro ambiente para testar?

Em todo caso, caso você queira prosseguir, basta entrar no banco de dados e alterar o tamanho da coluna `senha` da tabela `portal.funcionario` para o tamanho de 191 caracteres.

**Comment by arlenmendes** [comment]
@edersoares eu reinstalei e tudo. Mas era cash do meu navegador pois o dns era o mesmo... kkk. Desculpa e muito obrigado!! Agora esta funcionando 100%...  valeu de mais

**Comment by robson-alcantara** [comment]
Estou com esse problema na versão 2.1.16 e 2.1.17, como alterar o tamanho da tabela se o erro ocorre durante a criação da tabela? Mesmo inserindo a senha pelo banco de dados, a instalação não foi concluída.

**Comment by edersoares** [comment]
@robson-alcantara não sei o que pode estar acontecendo com teu ambiente para que o erro persista, mas veja se existe o registro `2019_03_28_000000_alter_columns_length` na tabela `public.migrations`, se existir, remova-o e então rode as migrations novamente.

**Comment by robson-alcantara** [comment]
Encontrei o problema. Era a variável 'app.locale.timezone' do arquivo 'ieducar.ini' que estava configurada de forma incorreta
