### ISSUE TITLE
Erro no boletim

### ISSUE THREAD

**Issue by robson-alcantara** [portabilis/i-educar#598]
**MENU:**

Documentos -> Boletins -> Boletim escolar

**DESCRIÇÃO:**

Para algumas turmas, o boletim está sendo gerado de forma incorreta, com várias linhas da mesma disciplina.

**AMBIENTE:**

- Plataforma: instalação direta
- Sistema operacional e versão: Lubuntu 16.04
- Navegador e versão: Chrome e Firefox
- Outros detalhes importantes: i-Educar 2.1.3
[boletim-erro.pdf.pdf](https://github.com/portabilis/i-educar/files/3297146/boletim-erro.pdf.pdf)

**Comment by edersoares** [comment]
@robson-alcantara este é um erro conhecido que foi corrigido na versão 2.1.12. Sugiro que atualize a versão do seu i-Educar.

**Comment by robson-alcantara** [comment]
Muito obrigado @edersoares , irei trabalhar na atualização
