### ISSUE TITLE
Corrigir a funcionalidade da Enturmação em lote que não conclui o procedimento após a seleção da turma de origem.

### ISSUE THREAD

**Issue by Ertonilson** [portabilis/i-educar#599]
**MENU:**
Menu <Escola><Movimentações/Matrícula em lote>.

**DESCRIÇÃO:**
Corrigir a funcionalidade da **Enturmação em lote** que não conclui o procedimento após a seleção da turma de origem.

**OBSERVAÇÕES:**
Este recurso, disponibilizado em todas as versões do Ieducar, não está permitindo concluir a migração coletiva das matrículas do ano anterior para o ano recém criado.

**AMBIENTE:**
- Plataforma utilizada: instalação direta
- Sistema operacional e versão: Ubuntu Server 18.04.02

**Comment by edersoares** [comment]
@Ertonilson a tela de "Enturmação em lote" é apenas para enturmar alunos já matriculado no ano corrente, ela não faz a matrícula de um ano para outro.

Para isso, você deve utilizar a tela de "Rematrícula automática".

**Comment by Ertonilson** [comment]
@edersoares pelo que entendi, esta funcionalidade seria uma complementação da "Rematrícula automática". Até aí, tudo bem. Gostaria então de sugerir um outro nome para a Label, algo como: "Remanejamento". Me pareceu redundante, haja visto que, a exemplo do **_Educacenso_** (do Inep), com a qual, a maioria dos operadores do Ieducar já tem familiaridade, essas duas funcionalidade são compostas em uma só: O operador seleciona uma turma do ano anterior; o sistema carrega um formulário listando cada aluno daquela turma e, ao lado de cada nome, um checkbox para se habilitar caso o mesmo deva ser remanejado. Para concluir, um botão "Remanejar" disponível ao final do formulário indica a finalização do processo. Abraço.
