### ISSUE TITLE
Erro ao gerar Boletim

### ISSUE THREAD

**Issue by arlenmendes** [portabilis/i-educar#615]
Olá e obrigado por nos ajudar a tornar o i-Educar um projeto mais estável. Para
reportar seu bug use o template abaixo:

**MENU:**

Escola / Alunos / Boletim escolar

**DESCRIÇÃO:**

Ao adicionar os filtros, como solicitados obrigatoriamente, e clicar em exibir. Retorna o seguinte erro em um Alert.
![Captura de tela de 2019-07-02 17-23-25](https://user-images.githubusercontent.com/13527376/60544001-277a8080-9cee-11e9-93fb-6eed38d346d8.png)

**AMBIENTE:**

- Plataforma utilizada (p.ex. Docker, instalação direta):
- Sistema operacional e versão: Ubuntu 18.04:
- Navegador: Chrome:

**Comment by edersoares** [comment]
@arlenmendes o problema está com a configuração `report.source_path` do arquivo `.ini`.

Você deve colocar o caminho absoluto para a pasta `ieducar/modules/Reports/ReportSource/`.

**Comment by arlenmendes** [comment]
@edersoares este arquivo fica onde?

**Comment by arlenmendes** [comment]
> @edersoares este arquivo fica onde?

Encontrei. É aquele que iniciamos quando instalamos.
