### ISSUE TITLE
Dificuldades com a instalação

### ISSUE THREAD

**Issue by leonardogoncalvesmartins** [portabilis/i-educar#623]
Boa tarde,

Estou há alguns dias tentando instalar o sistema e preciso de ajuda.

**PROBLEMA:**
Li e reli a descrição do site e ainda não consegui instalar.
https://github.com/portabilis/i-educar#nova-instala%C3%A7%C3%A3o

1 - Primeiro segui o passo-a-passo:
Nova instalação
Clone o repositório:
git clone https://github.com/portabilis/i-educar.git && cd i-educar
docker-compose up -d --build
docker-compose exec php composer new-install
docker-compose port nginx 80
Funcionou uma vez. No dia seguinte deu erro. Após varias tentativas formatei o servidor e comecei novamente do zero e aí dois problemas acontecem:
 1.1 - Erro no build
Ao executar docker-compose up -d --build retorna o erro:
ERROR: Service 'php' failed to build: The command '/bin/sh -c apt-get install -y openjdk-8-jre' returned a non-zero code: 100

1.2 - Erro de instalação
Ao executar docker-compose exec php composer new-install retorna o erro:
ERROR: No container found for php_1

Já fui em vários foruns e não consegui avançar

2 - Segundo tentei instalação em servidor (essa seria minha preferência de instalação)
Novamente segui o passo-a-passo e fiz várias modificações ao longo dos dias:
Mudei para Postgres9.5.9;
versão 2.1.18 para 2.1.19;
comentei a linha wget que baixa o ieducar.backu (não está baixando o arquivo)
tentei tanto com apache (default no script) como nginx (minha preferência)
E mesmo assim não funcionou. Bem, dito isto 
**OBSERVAÇÕES:**
Consegui avançar até o ponto: http://[MEU IP]/install.php mas apresenta o seguinte erro:
Fatal error: Uncaught Error: Class 'iEducar\Support\Installer' not found in /var/www/ieducar/public/install.php:16 Stack trace: #0 {main} thrown in /var/www/ieducar/public/install.php on line 16

OBS: index.htm e info.php funcionam! 

**AMBIENTE:**
-Plataforma: **Docker E instalação direta**
- Sistema operacional e versão Ubuntu Serve 16.04, 16GB RAM, HD 1T.
- Outros detalhes importantes: Observei que era necessário alterar o PHP para versão 7.3
- Navegador e versão (Chrome  75.0.3770.142):

Obrigado pela atenção!

**Comment by edersoares** [comment]
Olá, @leonardogoncalvesmartins, estaremos verificando, pode ser um problema com o build da imagem Docker por ter algum pacote desatualizado.

**Comment by paulopadiilha** [comment]
Estou com o mesmo erro no momento da instalação! 

Segue o problema:

E: Unable to locate package openjdk-8-jre
ERROR: Service 'php' failed to build: The command '/bin/sh -c apt-get install -y openjdk-8-jre' returned a non-zero code: 100

Espero uma ajuda!

**Comment by edersoares** [comment]
@paulopadiilha e @leonardogoncalvesmartins está estranho, pois este erro não acontece aqui, parece ser algo relacionado a atualização dos `sources` das distros que vocês estão utilizando.

Neste tópico do fórum https://forum.ieducar.org/t/command-new-install-is-not-defined/666/13 foi sugerido modificar a imagem do container PHP.

https://github.com/portabilis/i-educar/blob/09219fbcf93b63c0d695d678eab68a91565a2bb3/docker/php/Dockerfile#L1

Substituir por `php:7.2.19-fpm`.

Façam o ajuste e vejam se funciona por favor.

**Comment by paulopadiilha** [comment]
Como fazer isso em numa VPS? Estava tentanto instalar, justamente nessa penúltima etapa aconteceu este erro!

**Comment by edersoares** [comment]
Você está utilizando Docker na VPS, então basta entrar no arquivo `docker/php/Dockerfile` e fazer o ajuste solicitado.

**Comment by leonardogoncalvesmartins** [comment]
Consegui avançar. Obrigado.

Quando acesso http://[MEU IP]/install.php aparece o seguinte erro:

Fatal error: Uncaught Error: Class 'iEducar\Support\Installer' not found in /var/www/html/install.php:16 Stack trace: #0 {main} thrown in /var/www/html/install.php on line 16

**Comment by paulopadiilha** [comment]
Eu ainda não entendi, se mandasse um passo a passo do que eu preciso fazer sobre cada comando seria melhor.

**Comment by edersoares** [comment]
@leonardogoncalvesmartins o seu problema está na configuração do `root` do seu servidor Nginx, ele precisa ser:

```
root /var/www/html/public
```

No arquivo de configuração que você copiou: https://github.com/portabilis/i-educar/blob/master/docker/nginx/default.conf

@paulopadiilha o passo a passo é este https://github.com/portabilis/i-educar#instala%C3%A7%C3%A3o-em-servidor basta apenas ajustar o que lhe informei acima.

**Comment by leonardogoncalvesmartins** [comment]
@paulopadiilha Suas dicas foram perfeitas. Consegui...
Quer dizer, falta um detalhe. 

Após digitar MEUIP/install.php apareceram várias informações. 
Mudei tudo que foi pedido mas...
Apesar de mudar a opção abaixo continua aparecendo a mensagem:

" Conexão com o banco de dados
Não foi possível estabelecer comunicação com o banco de dados. Verifique se os parâmetros abaixo estão configurados corretamente no seu arquivo .env:

DB_CONNECTION=pgsql
DB_HOST=postgres
DB_PORT=5432
DB_DATABASE=ieducar
DB_USERNAME=ieducar
DB_PASSWORD=ieducar"

No arquivo .env está igual, mas a mensagem persiste. Deve desinstalar o Postgresql e começar de novo?

**Comment by edersoares** [comment]
@leonardogoncalvesmartins se você está usando instalação direta, deve alterar as informações de conexão com o seu banco.

Por exemplo, `DB_HOST=postgres` deve ser `DB_HOST=localhost`, pois você está conectando ao Postgres local do seu servidor e não ao container Docker.

Você deve criar o banco de dados, geralmente a pode ser algo como `createdb ieducar` na linha de comando do servidor, e deve colocar o usuário, senha e porta conforme sua configuração.

**Comment by edersoares** [comment]
@leonardogoncalvesmartins @paulopadiilha obtiveram sucesso?

**Comment by leonardogoncalvesmartins** [comment]
Boa noite @edersoares

Sim. Hoje parti deu uma instalação limpa. Formatei o servidor e instalei o Ubuntu 16.04 server.
Após testar vários modos de instalação e pegar as dicas contigo, criei um script de instalação novo. (está mais para um roteiro).

Ainda estou tentando descobrir o porquê a página de login aparece perfeita apenas em um dos navegadores (Avast Securit Browser).

Na segunda, quando retornar à escola, refarei todo o processo e espero, de fato, criar um script de instalação que possa ajudar a fazer a instalação mais rápida e fácil. Isto é, para quem quiser instalar o sistema localmente.

Espero ter boas notícias na segunda.

Obrigado,

**Comment by edersoares** [comment]
@leonardogoncalvesmartins tudo certo? Rolaram as boas notícias?

**Comment by leonardogoncalvesmartins** [comment]
Tudo funcionando, perfeitamente.

Obrigado.

Em seg, 2 de set de 2019 às 10:27, Eder Soares <notifications@github.com>
escreveu:

**Comment by diegopassoscosta** [comment]
Olá senhores!

Estou usando a Versão: 2.7.3

Tive o **"mesmo issue"** que o @leonardogoncalvesmartins e o @paulopadiilha. Só que antes é dado duas mensagem de alerta que vem ocasionar a falha.

Warning: include(/var/www/html/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/html/public/install.php on line 11

Warning: include(): Failed opening '/var/www/html/vendor/autoload.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/public/install.php on line 11

Fatal error: Uncaught Error: Class "iEducar\Support\Installer" not found in /var/www/html/public/install.php:16 Stack trace: #0 {main} thrown in /var/www/html/public/install.php on line 16

dentro do install.php na linha 11 há a referência para o arquivo:
$rootDir = realpath(__DIR__ . '/../');
include $rootDir . '/vendor/autoload.php';

**Nota:** dentro do diretório /vendor/ não existe o fonte autoload.php
https://github.com/portabilis/i-educar/tree/2.8/public/vendor



[]'s
Diego Passos

**Comment by edersoares** [comment]
@diegopassoscosta esta forma de instalação direta em servidor não está disponível na versão 2.7 e possivelmente será removida da versão 2.8. Acaba sendo trabalhosa a organização e teste da mesma e como cada vez mais o projeto está se aproximando para a estrutura do framework Laravel, há documentação o suficiente para fazer uma instalação usando Git e seguindo os passos descritos no readme.

Há outros trabalhos na comunidade como a instalação via Ansible https://github.com/marcosoliveirasoares94/i-educar-ansible-install que ajudam a fazer a configuração do sistema.

**Comment by diegopassoscosta** [comment]
@edersoares Muito obrigado pelo retorno!
Vou ler a documentação e efetuar a instalação.
[]'s

**Comment by diegopassoscosta** [comment]
@edersoares,Lendo o README, vi que a instalação do Docker não está aconselhada para ambientes de produção, neste caso em particular, houve mudança? Caso não, qual a tua recomendação para um ambiente de produção.

Aproveitando o ensejo, existe alguma estimativa de quando sairá a nova versão 2.8 já com o Laravel?

[]'s

**Comment by edersoares** [comment]
Ambientes de produção sempre devem ser configurados usando boas práticas, então basicamente é configurar um servidor Nginx, PHP, firewall e os acessos. O i-Educar já roda com Laravel.

**Comment by diegopassoscosta** [comment]
@edersoares 

Não fiz a instalação via Docker em ambiente de produção em virtude da mensagem que encontrei no link https://github.com/portabilis/i-educar#nova-instala%C3%A7%C3%A3o:

"ATENÇÃO: Essa forma de instalação tem o objetivo de facilitar demonstrações e desenvolvimento. Não é recomendado para ambientes de produção!"

Daí minha dúvida: Se a instalação do Docker já estiver ok, eu sigo a do Docker. Caso contrário eu tento efetuar a instalação via Ansible mesmo.

**Comment by edersoares** [comment]
A instalação vai funcionar, mas não é aconselhável devido a não estar otimizada para produção.

**Comment by diegopassoscosta** [comment]
@edersoares Obrigado, perfeito. Mas esta otimização é referente basicamente ao desempenho?
E neste caso, qual seria a instalação adequada para ambiente de produção? A via Ansible? 

Por hora, vou  estar dando início a instalação via Docker para ir atuando no sistema.

[]'s

**Comment by diegopassoscosta** [comment]
@edersoares, Tudo jóia? Tentamos efetuar a instalação pelo Docker e também não tivemos sucesso. Houve um retorno 
Nota: o yarn, estava instalado, bem como o npm.

![erroDocker](https://user-images.githubusercontent.com/2180083/182492982-16396a70-8cfe-4d48-88c8-f4eba67feb9b.png)

De qualquer ficaria grato se pudesse fornecer o apoio e orientar sobre qual instalação devemos usar para um ambiente de produção e qual instalação devemos seguir seguir para um ambiente de produção.

[]'s
Diego Passos

**Comment by edersoares** [comment]
@diegopassoscosta olhei aqui e o `yarn` não está na imagem Docker, deve ser isso, você pode adicionar e abrir um PR ou simplesmente ignorar. O Yarn só é utilizado caso você for ativar o serviço de notificações.

Este último passo não gera problemas na instalação, o i-Educar já deve estar funcionando normalmente.

**Comment by diegopassoscosta** [comment]
@edersoares Tentei de novo, só que quando rodo docker-compose port nginx 80
informa o endereço 0.0.0.0. e Não abre página de instalação alguma.
Alguma ideia?

[]'s
Diego Passos

**Comment by edersoares** [comment]
@diegopassoscosta substitua o `0.0.0.0` por `localhost` apenas copie a porta, que deve ser 4 números aleatórios

**Comment by lamonifal** [comment]
Bom dia! Estou com problema no Endereçamento! Na página inicial, ao clicar em endereçamento ele mandar para página escola. Estou conseguindo acessar o Endereçamento na Pesquisa Rápida, porém quando tento cadastrar um múnicipio ele manda de volta para o menu Escola. @edersoares

**Comment by edersoares** [comment]
@lamonifal estamos usando o módulo de Endereçamento para testar uma nova arquitetura para o i-Educar, visando construir um frontend desacoplado do backend, por isso ainda não fechamos a release da 2.8.

Basicamente para voltar o comportamento passado, faça revert desse commit https://github.com/portabilis/i-educar/commit/c84174e650c04d60aad8f7c28c36e648fd155408.

**Comment by lamonifal** [comment]
@edersoares acabei de ligar a maquina, dei o git revert no commit sugerido, mas ainda persite, não estou conseguindo acessar o Endereçamento e nem consigo cadastrar, pois quando tento ele me leva ao menu da escola. @edersoares

**Comment by edersoares** [comment]
@lamonifal você precisará acessar as telas diretamente ou fazer rollback desta migration https://github.com/portabilis/i-educar/blob/04d8a63e23b1a25917bcac8ffd91585e827345e7/database/migrations/2022_09_20_175041_update_menus_addressing.php
