### ISSUE TITLE
Campos do cadastro de escolas não exportados para Educacenso

### ISSUE THREAD

**Issue by josafa2018** [portabilis/i-educar#626]
MENU:

Educacenso -> Exportações -> 1ª fase - Matrícula inicial

DESCRIÇÃO:

O arquivo exporta normalmente, porém quando importado no educacenso percebe-se que os dados preenchidos no ieducar no cadastro da escola na aba <Dados do ensino> os campos <Forma(s) de organização do ensino> e <Instrumentos, materiais socioculturais e/ou pedagógicos em uso na escola para o desenvolvimento de atividades de ensino aprendizagem> aparecem no educacenso não preenchidos.

AMBIENTE:

Instalação direta
Sistema operacional: Debian 9
Navegador: Chrome 75

**Comment by edersoares** [comment]
@Bonot e @munizeverton podem verificar por favor.

**Comment by Bonot** [comment]
@edersoares cc @josafa2018 

De acordo com os testes que eu realizei, o iEducar está exportando todas as opções desses dois campos como 0, independente do que foi informado no cadastro de escola. Por isso no Censo escolar esses campos não estão vindo preenchidos.

Adicionei a label de bug à essa issue.

**Comment by MuriloSGomes** [comment]
Bom dia, gostaria de saber como vocês fazem no ano seguinte quando campos novos são adicionados no layout, altera direto no código?

**Comment by Bonot** [comment]
Problema resolvido a partir de: https://github.com/portabilis/i-educar/pull/629
