### ISSUE TITLE
Erro ao tentar mudar o mês na tela do calendário

### ISSUE THREAD

**Issue by robson-alcantara** [portabilis/i-educar#647]
Nas versões 2.1.17 e 2.1.21 não consigo mudar o mês de um calendário já criado. Mudar para inserir informações de feriados ou anotações, só consigo no mês corrente. Na versão 2.1.3 consigo normalmente.

Caminho: Escola -> Cadastros -> Calendários.

**Comment by Bonot** [comment]
Esse problema foi resolvido a partir da versão 2.2 (https://github.com/portabilis/i-educar/pull/675). Para trabalhar com as melhorias, aplicar as atualizações.
