### ISSUE TITLE
Atestado de frequência - Falta coluna

### ISSUE THREAD

**Issue by rsdevigo** [portabilis/i-educar#661]
**MENU:**

Documentos/Atestado de Frequência

**DESCRIÇÃO:**

Durante a geração do documento, aparece a mensagem "Erro no preenchimento do formulário.
" 
Como se eu não tivesse selecionado os argumentos mínimos para a geração de relatório.

**OBSERVAÇÕES:**

Fiz uma busca mais profunda, parece que o SQL do report retorna esse erro: 

```
ERROR:  column matricula.turno_id does not exist
Linha 2: ...FROM pmieducar.turma_turno WHERE id = COALESCE(matricula....
```

**AMBIENTE:**

- Instalação direta
- Debian
- Chrome

**Comment by rsdevigo** [comment]
Se quiser, me dar um pequeno histórico dessa coluna para talvez alterar o relatório, eu posso arrumar o bug.

**Comment by edersoares** [comment]
@rsdevigo exato! Este problema está sendo ocasionado por isso, a coluna `turno_id` está na tabela `matricula_turma`.

Deixar contigo essa issue, obrigado o/

**Comment by rsdevigo** [comment]
Vlw, vou subir a correção.
