### ISSUE TITLE
Erro ao carregar os 4 tipos de atestados (Matrícula, Frequência, Vaga, Transferência)

### ISSUE THREAD

**Issue by rsdevigo** [portabilis/i-educar#662]
**MENU:**

Escola > Documentos > Atestados [Matrícula, Frequência, Vaga, Transferência]

**DESCRIÇÃO:**

Ao tentar acessar o formulário para a geração do documento ele aparece a mensagem
"Desculpe, mas ocorreu um erro inesperado"

**OBSERVAÇÕES:**

Rodei o i-Educar pelo Docker e identifiquei que o erro está no método titulo() da View do Report, que usa o Model Menu realiza a busca do título da seção do site, mas faltou chamar o método first() para retornar a tupla e não a coleção de Menu.

**AMBIENTE:**

- Ambos
- Ubuntu 16.04 e Docker
- Chrome

**Comment by edersoares** [comment]
@rsdevigo corrido no seu PR https://github.com/portabilis/i-educar-reports-package/pull/68. Obrigado!
