### ISSUE TITLE
HISTÓRICO DO EJA NÃO FUNCIONA

### ISSUE THREAD

**Issue by ieducarcda** [portabilis/i-educar#668]
Olá e obrigado por nos ajudar a tornar o i-Educar um projeto mais estável. Não esqueça de revisar o nosso
[guia de contribuição](https://github.com/portabilis/i-educar/blob/master/contributing.md) para saber melhor como colaborar com a nossa comunidade. Para reportar seu bug use o template abaixo:

**MENU:**

Nesta seção deve ser apontado qual o menu no sistema deve ser realizada a alteração.

**DESCRIÇÃO:**

Nesta seção deve ser colocado uma descrição do problema ou necessidade.

**OBSERVAÇÕES:**

Observações em geral sobre o problema apontado.

**AMBIENTE:**

- Plataforma utilizada (Docker, instalação direta)
- Sistema operacional e versão (Ubuntu 16.04, Windows 7)
- Navegador e versão (Chrome 75)
- Outros detalhes importantes

**Comment by ieducarcda** [comment]
Desde que instalei o ieducar pela primeira vez em 2018, não gera o histórico escolar do EJA, isto ta dificultando a utilização dele em meu município, peco a equipe de TI responsável que tente uma solução para o problema por favor.

**Comment by Bonot** [comment]
Olá, @ieducarcda, conforme comentado em outra issue sua referente à problemas com históricos de EJA, está disponível na versão mais recente (2.3) um outro modelo que atende essa questão.

Para mais detalhes do modelo acesse o pull request: https://github.com/portabilis/i-educar-reports-package/pull/75
