### ISSUE TITLE
Parecer descritivo de 1 ao 5 ano

### ISSUE THREAD

**Issue by ieducarcda** [portabilis/i-educar#669]
No i-educar, tem o campo para lançar o parecer descritivo individual, porem não tem uma saída dele em PDF pra visualização e impressão, ficando assim complicado o sistema. Peco desenvolvimento dessa saída pela equipe de desenvolvimento, por favor. Porque já estou usando o i-educar como teste e esta sendo muito bom. Obrigado pela atenção.

**Comment by Bonot** [comment]
Olá, @ieducarcda!

Agora a comunidade possui 2 modelos de boletins para quem trabalha com pareceres:

- Parecer descritivo por componente;
- Parecer descritivo geral;

Espero que ajudem :smile:
