### ISSUE TITLE
Erro na instalação com o Docker

### ISSUE THREAD

**Issue by saninaimayer** [portabilis/i-educar#674]
Bom dia,

Fiz a instalação do ambiente de teste com o docker conforme instruções, porém, ao tentar acessar a página de cadastro de turma ela apresenta um erro na linha 508:

508 - require_once 'Reports/Tipos/TipoBoletim.php';

Ao verificar, de fato o arquivo não existe.

![Captura de Tela 2019-10-28 às 10 05 31](https://user-images.githubusercontent.com/11694458/67680896-ff80ee00-f96a-11e9-8441-a3795775a4c5.png)

**Comment by edersoares** [comment]
Olá @saninaimayer, por hora, existe a dependência do pacote de relatórios https://github.com/portabilis/i-educar-reports-package, faça sua instalação e este problema será resolvido.
