### ISSUE TITLE
Distribuir como AppImage

### ISSUE THREAD

**Issue by sudo-give-me-coffee** [portabilis/i-educar#676]
Olá, atualmente arquivos .tar.gz não são mais o melhor jeito de distribuir aplicações os AppImages são a melhor tecnologia existente

**CONTEXTO:**
Essa alteração é importante pois facilitaria muito a implantação do software. Mesmo usuários sem conhecimentos técnicos poderiam implantar o software

**IMPLEMENTAÇÃO:**

Nesse repositório existe uma ferramenta que pode facilitar esse processo:

https://github.com/AppImage/pkg2appimage

**Comment by edersoares** [comment]
Sem planos para o momento.
