### ISSUE TITLE
Erro ao tentar editar cadastro de turma

### ISSUE THREAD

**Issue by robson-alcantara** [portabilis/i-educar#679]
**MENU:**

Escola -> Cadastro -> Turma

**DESCRIÇÃO:**

Caros, atualizei o sistema da versão 2.1.3 para a versão 2.1.17. Fui tentar editar o cadastro de uma turma e o sistema disparou o seguinte erro: "Existem enturmações ou professores atrelados a esta turma em turnos diferentes do especificado."

E não permite salvar, como corrigir?

**AMBIENTE:**

- Plataforma utilizada: instalação direta
- Sistema operacional e versão: qualquer
- Navegador e versão: qualquer

**Comment by edersoares** [comment]
@robson-alcantara você precisa excluir os vínculos de alunos e professores da turma para poder realizar a exclusão, pois há registros pendentes.

**Comment by robson-alcantara** [comment]
Que tipo de pendência? Não posso remover os vínculos de alunos, é um sistema em produção

**Comment by robson-alcantara** [comment]
No i-Diario, algumas professores aparecem no período 1 (manhã) e outros no período 2 (tarde), a turma é do turno da tarde

**Comment by edersoares** [comment]
Veja o código: 

https://github.com/portabilis/i-educar-portabilis/blob/2.2/ieducar/intranet/educar_turma_cad.php#L1208

Os relacionamentos com aquelas tabelas devem ser removidos, pois existem inconsistência, apenas valide antes de fazer a remoção.

**Comment by robson-alcantara** [comment]
O link correto seria esse: https://github.com/portabilis/i-educar/blob/2.2/ieducar/intranet/educar_turma_cad.php#L1208 ?

**Comment by robson-alcantara** [comment]
Obrigado pela dica, averiguarei as tabelas

**Comment by robson-alcantara** [comment]
Corrigindo os dados na tabela modules.professor_turma, o problema foi sanado. Obrigado pelo suporte
