### ISSUE TITLE
Declaração de conclusão de curso não emite texto com acentos nas observações

### ISSUE THREAD

**Issue by robson-alcantara** [portabilis/i-educar#681]
**MENU:**

Escola -> Documentos -> Atestados -> Declaração de conclusão de curso

**DESCRIÇÃO:**

O texto inserido no campo de observações é emitido com caracteres inválidos no documento.

**OBSERVAÇÕES:**

Problema de codificação de caracteres.

**AMBIENTE:**

- Plataforma utilizada: instalação direta
- Sistema operacional e versão: qualquer
- Navegador e versão: qualquer
[declaração.pdf](https://github.com/portabilis/i-educar/files/3864035/declaracao.pdf)
![declaração](https://user-images.githubusercontent.com/20538912/69151467-736d6c80-0ab9-11ea-8327-43fdb2c304af.png)

**Comment by jrbarros** [comment]
@robson-alcantara erro esta relacionado a falta da fonte `DejaVu Sans` no sistema operacional. Testamos aqui e esta tudo certo.
