### ISSUE TITLE
Erro ao acessar relatórios

### ISSUE THREAD

**Issue by saninaimayer** [portabilis/i-educar#683]
Bom dia,

Estou tendo problemas ao tentar acessar os relatórios do iEducar. Segue o print do erro.

Att

Sani Naimayer
![Captura de Tela 2019-11-21 às 09 17 50](https://user-images.githubusercontent.com/11694458/69337716-4a2b1880-0c40-11ea-9051-34fa23dfc684.png)

**Comment by edersoares** [comment]
@saninaimayer mais informações, como versão do i-Educar e tipo de instalação são necessárias.

**Comment by Bonot** [comment]
@saninaimayer devido a falta de mais informações essa issue estará sendo encerrada. Caso você ainda esteja passando por esse problema, peço que leve para o [Fórum do i-Educar](https://forum.ieducar.org/).

Obrigada!
