### ISSUE TITLE
Notas finais incorretas no boletim do professor

### ISSUE THREAD

**Issue by robson-alcantara** [portabilis/i-educar#690]
**MENU:**

Documentos -> Boletins -> Boletim do professor

**DESCRIÇÃO:**

As médias finais estão incorretas, está sendo repetida as médias do 4º bimestre
[TeacherReportCard.pdf](https://github.com/portabilis/i-educar/files/3967697/TeacherReportCard.pdf)

**OBSERVAÇÕES:**

Outro problema é que quando o componente curricular não é selecionado, as notas ficam incorretas

**AMBIENTE:**

- Plataforma utilizada: instalação direta
- Sistema operacional e versão: qualquer
- Navegador e versão: qualquer
- Outros detalhes importantes: i-Educar 2.1.17

**Comment by munizeverton** [comment]
@robson-alcantara bug ajustado no PR https://github.com/portabilis/i-educar-reports-package/pull/71

**Comment by kesllan** [comment]
@munizeverton @edersoares Percebi uma coisa. Apesar de ja ter corrigido o erro do Boletim do professor nessa issue, o mesmo apresenta erro quando nao seleciona o Componente Curricular pra gerar de todos de uma vez. Acontece que todos os componetes apresentam todos as mesmas notas além de não apresentar as notas corretas.

**Comment by robertfsousa** [comment]
> @munizeverton @edersoares Percebi uma coisa. Apesar de ja ter corrigido o erro do Boletim do professor nessa issue, o mesmo apresenta erro quando nao seleciona o Componente Curricular pra gerar de todos de uma vez. Acontece que todos os componetes apresentam todos as mesmas notas além de não apresentar as notas corretas.

Fiz os testes com o filtro desmarcado e apresentou as disciplinas com notas corretas e diferentes. 
Poderia verificar se:

- O projeto i-educar e o i-educar-reports-package estão atualizados;

Executa depois os comandos:
```
composer plug-and-play:update
php artisan community:reports:link
php artisan reports:install
php artisan vendor:publish --tag=reports-assets
```
