### ISSUE TITLE
Erro ao tentar inserir documentação padrão

### ISSUE THREAD

**Issue by robson-alcantara** [portabilis/i-educar#696]
**MENU:**

Escola -> Documentos -> Documentação Padrão

**DESCRIÇÃO:**

Ao selecionar a instituição, a campo relatórios exibe a mensagem 'Carregando relatórios'.

**OBSERVAÇÕES:**

Erro já era exibido antes de configurar a aplicação a partir do link: https://github.com/portabilis/i-educar/wiki/Sistema-de-upload-de-arquivos

**AMBIENTE:**

- Plataforma utilizada: instalação direta
- Sistema operacional e versão: quaisquer
- Navegador e versão: quaisquer
- Outros detalhes importantes: versão do i-Educar - 2.1.17

![2020-01-15-104922_1366x768_scrot](https://user-images.githubusercontent.com/20538912/72439245-508fc980-3785-11ea-9b7e-c43e6cc64015.png)

**Comment by Bonot** [comment]
Olá, @robson-alcantara, esse problema acontece quando não existe nenhuma documentação adicionada para a instituição. Você pode inserir esses documentos em Escola > Cadastros > Instituição > Botão **Documentação padrão**:

![image](https://user-images.githubusercontent.com/5911217/81612518-5b650e80-93b3-11ea-8483-f60a2de825d0.png)

Espero que isso resolva seu caso, a issue continuará aberta para corrigir a mensagem em casos que não há documentações informadas.

**Comment by robson-alcantara** [comment]
Oi @Bonot 

    Eu soube que a versão 2.1.18 ou 2.1.19 dá suporte a envio de arquivos de forma local.
