### ISSUE TITLE
Gerando chave da aplicação

### ISSUE THREAD

**Issue by sigridslima** [portabilis/i-educar#700]
Ola amigos, estou tentando instalar o ieducar no windows 7 64, fiz a instalação dos recursos necessários, porem quando vou instalar fica somente na tela "Gerando chave da aplicação", o checklist estão todos ok.

Obs. estou usando a porta do php: localhost:8080/

php 7.2
pgAdmin 4.18

arquivo .env

APP_NAME=i-Educar
APP_ENV=production
APP_KEY=
APP_DEBUG=false
APP_URL=http://localhost
APP_TIMEZONE=America/Sao_Paulo
APP_TRACK_ERROR=false
APP_DEFAULT_HOST=ieducar.com.br

API_ACCESS_KEY=
API_SECRET_KEY=

LEGACY_CODE=true
LEGACY_DISPLAY_ERRORS=false
LEGACY_PATH=ieducar

LOG_CHANNEL=stack

TELESCOPE_ENABLED=false
DEBUGBAR_ENABLED=false

DB_CONNECTION=pgsql
DB_HOST=localhost
DB_PORT=5432
DB_DATABASE=itaranti_ieducar
DB_USERNAME=itaranti_itarantim
DB_PASSWORD=itarantim147258369

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

REDIS_HOST=redis
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

HONEYBADGER_API_KEY=

GOOGLE_TAG_MANAGER=

FILESYSTEM_DRIVER=local

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=
AWS_BUCKET=

![image](https://user-images.githubusercontent.com/21263061/75118545-cc6d1380-5659-11ea-9ed8-84dbfc8e3180.png)

Aguardo

**Comment by edersoares** [comment]
@sigridslima aponte o Document Root do servidor para a pasta `/public` para um melhor uso.

Você tem que garantir que o arquivo `.env` tenha permissão de escrita, mas veja o log da aplicação `storage/logs/` para saber mais sobre o erro.

**Comment by sigridslima** [comment]
Document Root onde encontro ele? é no arquivo .env.
Seria assim: 
APP_NAME=i-Educar
APP_ENV=production
APP_KEY=
APP_DEBUG=false
//aqui
APP_URL=http://localhost:8080/public/
//
APP_TIMEZONE=America/Sao_Paulo
APP_TRACK_ERROR=false
APP_DEFAULT_HOST=ieducar.com.br

**Comment by edersoares** [comment]
@sigridslima é uma configuração do seu Wamp.

Vi que fez uma instalação direta no Windows, hoje não suportamos instalações em Windows, apenas em Linux e Docker.

É possível fazer a instalação em Windows, porém são necessários inúmeros ajustes, eu aconselho utilizar a instalação via Docker.

**Comment by sigridslima** [comment]
Certo, fiz o mesmo procedimento em um hospedagem da HOMEHOST, apresenta o mesmo caso, fica so na tela Gerando Chave, entrei em contato do suporte e eles informaram que o serviço atende as exigências do Ieducar

**Comment by sigridslima** [comment]
> @sigridslima é uma configuração do seu Wamp.
> 
> Vi que fez uma instalação direta no Windows, hoje não suportamos instalações em Windows, apenas em Linux e Docker.
> 
> É possível fazer a instalação em Windows, porém são necessários inúmeros ajustes, eu aconselho utilizar a instalação via Docker.

Ola, amigo, conseguir instalar com sucesso em um SO Ubutun, obrigado, verifiquei que nao tinha instalado o Docker. Enquanto hospedar o Ieducar em meu plano de hospedagem, eles informaram que tenho que contratar um VPS. Obrigado
