### ISSUE TITLE
Problemas no quadro de horários

### ISSUE THREAD

**Issue by robson-alcantara** [portabilis/i-educar#701]
**MENU:**

Servidores -> Cadastro -> Quadro de horários

**DESCRIÇÃO:**

Para alguns professores, o sistema não permite adicionar horários após algumas aulas já alocadas para este professor

**OBSERVAÇÕES:**

Aumentando a carga horária na alocação do servidor, o problema é resolvido ou diminuído. Para alguns casos, só é possível montar o horário reduzindo o tempo de aula

**AMBIENTE:**

- Plataforma utilizada: instalação direta
- Sistema operacional e versão: qualquer
- Navegador e versão: qualquer
- Outros detalhes importantes: i-Educar 2.1.17

**Comment by Bonot** [comment]
Olá, @robson-alcantara, não é possível alocar horas que excedem o limite de carga horária definido para o servidor. Ou seja, um servidor que possua 10 horas de carga horária definida, só pode ter 10 horas alocadas no quadro.

Se no seu caso não é exatamente isso, peço que dê mais detalhes sobre seu problema.

**Comment by robson-alcantara** [comment]
Não é bem este caso. O sistema impede de alocar mais horário para o professor antes mesmo de atingir o limite de carga horária.

**Comment by Bonot** [comment]
Entendo, são professores de Educação Infantil? Ou talvez séries iniciais? Que trabalham com inúmeras disciplinas.

**Comment by jrbarros** [comment]
@robson-alcantara estamos fechando por entender que essa demanda já foi resolvida.
