### ISSUE TITLE
Campo para informar acesso à Internet pelo aluno

### ISSUE THREAD

**Issue by robson-alcantara** [portabilis/i-educar#705]
Seria interessante ter campos no cadastro do aluno - aba moradia sobre Internet Banda Larga, Internet por Rede Celular, Smartphone etc, devido a essa pandemia as autoridades estão solicitando um raio-x da infraestrutura das famílias. Se não nesse nível de detalhe, mas pelo menos um campo que informe que o aluno tem acesso à Internet.

**Comment by Bonot** [comment]
Olá, @robson-alcantara, o iEducar já possui um campo assim no cadastro de alunos na aba de moradia:

![image](https://user-images.githubusercontent.com/5911217/100656699-d9770b80-332b-11eb-9508-4f8524e88707.png)
