### ISSUE TITLE
Problema ao atualizar da versão intermediária 2.2.21 para release 2.3.0

### ISSUE THREAD

**Issue by josafa2018** [portabilis/i-educar#709]
**MENU:**

Atualizar instalação no script install.php

**DESCRIÇÃO:**

Ao atualizar da versão 2.2.0 para a intermediária 2.2.21, o processo ocorre normalmente finalizando com a mensagem atualizado com sucesso. Porém após substituir os arquivos para a versão 2.3.0 o processo não conclui devido ao erro SQLSTATE[42P06]: Duplicate schema: ERROR: schema "cadastro" already exists.

**AMBIENTE:**

- Plataforma utilizada (instalação direta)
- Sistema operacional e versão (Debian 10.03)
- Navegador e versão (Chrome 83)
- Outros detalhes importantes

**Comment by edersoares** [comment]
@josafa2018 tu tens certeza que a migration https://github.com/portabilis/i-educar/blob/2.2-upgrade/database/migrations/2020_06_01_000000_upgrade.php foi executada?

Pois este erro ocorre quando a migration que consolida o banco de dados não foi executada.

**Comment by rsdevigo** [comment]
Opa, @josafa2018 se você pegou o release do 2.2.21-upgrade, ele possui um erro nessa migração, colocando um "\n" no final do INSERT na tabela de migrações.

Altera a migração colocando o conteúdo do link que o @edersoares postou.

@edersoares talvez valha a pena criar outro release com esses dois commits na migração que vc colocou o trim no nome da migração.

**Comment by josafa2018** [comment]
> @josafa2018 tu tens certeza que a migration https://github.com/portabilis/i-educar/blob/2.2-upgrade/database/migrations/2020_06_01_000000_upgrade.php foi executada?
> 
> Pois este erro ocorre quando a migration que consolida o banco de dados não foi executada.

fiz o procedimento baixando a release 2.2.21-upgrade, como retornou que havia processado com exito, baixei a release 2.3.0, ao atualizar com ele ocorreu o erro.
Mas, pelo que o @rsdevigo informo o problema estava na release 2.2.21-upgrade.
Como substitui os arquivos da 2.2.21-upgrade pelos arquivos da 2.3.0, colocar esse na pasta migrations da 2.3.0 que funciona?

**Comment by rsdevigo** [comment]
Não, faz o seguinte:

- Faz o backup da pasta "database" da 2.3.0, e coloca a pasta "database" da 2.2.21-upgrade com esse arquivo do link.
- Executa "php artisan migrate" no terminal
- Apaga a pasta database da 2.2.21-upgrade e volta a pasta database 2.3.0
- Executa o "php artisan migrate" no terminal

**Comment by rsdevigo** [comment]
Ou talvez, funcione se vc colocar esse arquivo com outro nome, 2018_01_01_000000_upgrade.php.

**Comment by josafa2018** [comment]
Nada, nem uma das duas opções funcionou

**Comment by josafa2018** [comment]
Resolvido!
Precisei instalar o sistema 2.2 em uma base vazia, copiei a tabela migrations dessa base vazia para minha base de produção, na minha base de produção atualizei novamente para a 2.2.21-upgrade, só que substituindo o arquivo 2018_01_01_000000_upgrade.php, comentei todas as migrations somente o conteúdo da função up (em cada arquivo de migrations), para que elas fossem registradas na tabela migrations sem alterar o banco de dados, depois atualizei pra 2.3.0, sem erro, em seguida pra 2.3.1 também sem erro. Infelizmente nas tentativas anteriores de corrigir acabou duplicando registros na tabela public.menus, no caso os relatórios(que resolvi excluindo pelo banco), e também a tabela recém criada public.districts acabou sendo populada com 11.799 registros todos iguais, mas como só temos um distrito aqui no município estou testando o sistema para ter segurança em apagar os registros no banco de dados.
Obrigado @rsdevigo e @edersoares pela ajuda.
PS: Reforço a sugestão do @rsdevigo para que a release 2.2.21-upgrade seja corrigida, para evitar que aconteça o mesmo com outros que atualizem via release.

**Comment by edersoares** [comment]
Legal @josafa2018! Vamos criar uma nova release de upgrade, valeu por postar aqui. Abraço!
