### ISSUE TITLE
Erros nos Atestados [Matrícula, Vaga, Transferência] e Declaração de Conclusão de Curso

### ISSUE THREAD

**Issue by rsdevigo** [portabilis/i-educar#715]
Olá e obrigado por nos ajudar a tornar o i-Educar um projeto mais estável. Não esqueça de revisar o nosso
[guia de contribuição](https://github.com/portabilis/i-educar/blob/master/contributing.md) para saber melhor como colaborar com a nossa comunidade. Para reportar seu bug use o template abaixo:

**MENU:**

Escolas->Documentos->Atestados->Atestado de [Matrícula, Vaga e Transferência] // Declaração de Conclusão de Curso

**DESCRIÇÃO:**

O erro ocorre quando ao final do preenchimento do formulário para a geração do atestado, aparece a msg: Erro no preenchimento do formulário.

**OBSERVAÇÕES:**

**AMBIENTE:**

- Plataforma utilizada: Instalação Direta
- Sistema operacional e versão: Debian Stretch
- Navegador e versão (Chrome 75): Chrome

**Comment by rsdevigo** [comment]
Pesquisando melhor, parece que o erro está no SQL dos relatórios.

Para tentar resolver o bug:

-  Fiz com que método ``getSqlMainReport`` da classe do Relatórios que herda do ``Portabilis_Report_ReportCore``mostrasse o SQL que está sendo executado antes de gerar o PDF, usando var_dump e die no método.
- Após isso peguei o SQL e executei no PSQL (Client do Postgres).

E apareceu alguns erros de conversões de tipo de dados:

- substring(logradouro.idtlog from 1 for 1)) || lower(substring(logradouro.idtlog, 2))
  * Na documentação do Postgresql, informa que o substring recebe como parâmetro apenas dados do tipo text, e ``logradouro.idtlog`` é ``int``, logo o erro acontece como não existindo uma função substring.
- (SELECT COALESCE((SELECT COALESCE((SELECT endereco_pessoa.numero
         FROM cadastro.endereco_pessoa,
              cadastro.juridica
        WHERE juridica.idpes = endereco_pessoa.idpes AND
              juridica.idpes = escola.ref_idpes),(SELECT endereco_externo.numero FROM cadastro.endereco_externo WHERE endereco_externo.idpes = escola.ref_idpes))),(SELECT numero FROM pmieducar.escola_complemento where ref_cod_escola = escola.cod_escola))) AS numero,
  * Nesse caso o primeiro COALESCE está comparando um campo varchar com um campo inteiro da tabela ``pmieducar.escola_complemento``, e isso também dá erro.
- to_char(endereco_pessoa.cep, '99999-999')
  * Aqui o erro é que to_char não aceita varchar como parâmetro e sim apenas numeric e o endereco_pessoa.cep é  varchar na tabela places.

Esses erros acontecem nos quatro arquivos dos Atestados e da Declaração.

Estou escrevendo um código para corrigir esses erros no repositório dos relatórios.

**Comment by edersoares** [comment]
@rsdevigo obrigado pela issue e pelo PR, acabou que a @Bonot fez este ajuste internamente e publico no PR https://github.com/portabilis/i-educar-reports-package/pull/74 na branch `2.3`, se puder averiguar se o funcionamento está correto, agradecemos!
