### ISSUE TITLE
Duplicidade nos menus de relatórios após atualização da versão 2.2.20 para a 2.3 

### ISSUE THREAD

**Issue by flavio2209** [portabilis/i-educar#717]
Conseguir fazer a migração do 2.2.20 para o 2.3.3, porém os menus dos relatórios estão aparecendo duplicados, como mostra os prints na postagem de fórum .

Para conseguir atualizar, refiz a instalação do 2.2.20, e fiz a recomendação que tem no git para 2.2.22-upgrade e depois para 2.3.3, 2.34 e 2.3.5 e problema continua

https://forum.ieducar.org/t/erro-de-layout-ao-informar-o-educacenso-2020/1015/22

**Comment by edersoares** [comment]
@flavio2209 você alterou a branch do repositório de relatórios para a `2.2-upgrade` ao fazer o processo?

Em todo caso, se for possível você testar em um ambiente que não seja produção, rode o seguinte comando na raiz do projeto i-Educar, onde ficam os arquivos `composer.json`, `composer.lock`:

```bash
# Remove todos os menus de relatórios
php artisan migrate:rollback --path=ieducar/modules/Reports/database/migrations/

# Adiciona novamente os menus dos relatórios
php artisan migrate --path=ieducar/modules/Reports/database/migrations/
```

Não pude testar aqui, mas em tese isso irá solucionar seu problema de duplicidade.

Deixe o resultado aqui depois. Abraço!

**Comment by flavio2209** [comment]
Boa noite @edersoares fiz o procedimento, porém o problema continua, segue a saída dos comandos:

master@srv02:/var/www/html/ieducar$ php artisan migrate:rollback --path=ieducar/modules/Reports/database/migrations/
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Rolling back: 2020_06_19_152923_recreate_view_dados_escola
Rolled back:  2020_06_19_152923_recreate_view_dados_escola (0.03 seconds)
master@srv02:/var/www/html/ieducar$ php artisan migrate --path=ieducar/modules/Reports/database/migrations/
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Migrating: 2020_06_19_152923_recreate_view_dados_escola
Migrated:  2020_06_19_152923_recreate_view_dados_escola (0.08 seconds)

**Comment by edersoares** [comment]
@flavio2209 faça o processo de _rollback_ até exibir a mensagem: "Nothing to migrate."

```
php artisan migrate:rollback --path=ieducar/modules/Reports/database/migrations/
```

**Comment by flavio2209** [comment]
@edersoares na segunda vez que rodo o comando aparece a mensagem abaixo e não resolveu ainda.

/var/www/html/ieducar$ php artisan migrate:rollback --path=ieducar/modules/Reports/database/migrations/
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Migration not found: 2020_07_03_154832_alter_funcion_get_date_in_year
Migration not found: 2020_06_12_100000_add_educacenso_consult_menu
Migration not found: 2020_04_13_150000_create_educacenso_record60_view
Migration not found: 2020_04_13_150000_create_educacenso_record50_view
Migration not found: 2020_04_13_150000_create_educacenso_record40_view
Migration not found: 2020_04_13_150000_create_educacenso_record20_view

**Comment by edersoares** [comment]
@flavio2209 qual versão (branch) do i-Educar você está usando? E qual versão (branch) do repositório de relatórios?

**Comment by flavio2209** [comment]
bom dia @edersoares  todos os dois nas ultimas versões, i-educar 2.3.5, atualizei a repositório do relatórios hoje mesmo e  o problema continua.  

Minha base em produção ainda continua na 2.2.20, to fazendo os testes em outra base.

**Comment by edersoares** [comment]
@flavio2209 o único erro que posso imaginar que possa ter acontecido é que no momento de fazer o upgrade o repositório dos relatórios não estavam na branch `2.2-upgrade`, você atualizou via instalador ou via comandos no terminal?

Em todo caso, fiz este script que acredito que irá solucionar o problema com a duplicidade de todos os menus:

```sql

delete from pmieducar.menu_tipo_usuario 
where menu_id in (
	select id 
	from (
		select 
			id,
			process,
			row_number() over (partition by process) as seq
		from public.menus m 
		where process is not null 
		order by process
	) as tmp 
	where tmp.seq > 1
);

delete from public.menus 
where id in (
	select id 
	from (
		select 
			id,
			process,
			row_number() over (partition by process) as seq
		from public.menus m 
		where process is not null 
		order by process
	) as tmp 
	where tmp.seq > 1
);
```

Poste o resultado se possível, obrigado.

**Comment by flavio2209** [comment]
@edersoares deu certo com o script, muito obrigado pela atenção.

PROBLEMA RESOLVIDO !!!!!

**Comment by edersoares** [comment]
@flavio2209 valeu, vou fechar a issue. Abraço.
