### ISSUE TITLE
Erro ao tentar gerar histórico escolar

### ISSUE THREAD

**Issue by robson-alcantara** [portabilis/i-educar#728]
**MENU:**

Escola -> Documento -> Históricos -> Histórico Escolar

**DESCRIÇÃO:**

Ao tentar gerar um histórico, o sistema exibe a mensagem: "Erro no preenchimento do formulário"

**OBSERVAÇÕES:**

A arquivo ieducar/modules/Reports/Queries/SchoolHistorySeriesYearsTrait.php exige a view relatorio.view_historico_series_anos vhsa que não está disponível na versão do i-Educar que utilizei.

A seguintes view está disponível no arquivo https://github.com/portabilis/i-educar/blob/fcb585cc0a0ad7bd1bd11492b541dd8e3b6214a9/database/sqls/views/relatorio.view_historico_series_anos.sql que não vem inclusa na versão 2.3.6

**AMBIENTE:**

- i-Educar: 2.3.6

**Comment by msoares94** [comment]
@robson-alcantara, isso já foi resolvido ?

Se sim, pode seguir com o fechamento da issue.

**Comment by robson-alcantara** [comment]
A view está inclusa na versão 2.6.0
