### ISSUE TITLE
Adicionar tópico hacktoberfest ao repositório

### ISSUE THREAD

**Issue by lhsazevedo** [portabilis/i-educar#729]
Neste ano, mantenedores de projetos terão que optar por participar do Hacktoberfest adicionando o tópico "hacktoberfest" ao repositório.

Reparei que este repo está na [lista de repositórios PHP brasileiros aceitando contribuições para o #hacktoberfest](https://github.com/PHPRio/hacktoberfest), mas ainda não possui este tópico.

Adicionalmente, o repositório será listado na [página do tópico](https://github.com/topics/hacktoberfest) junto à outros que optaram por participar.

[Mais informações aqui](https://www.youtube.com/watch?v=FxBv4FMcDgo).

**Comment by edersoares** [comment]
@lhsazevedo o tópico ficou do ano passado, para este ano não nos preparamos para a Hacktoberfest. Tópico removido.
