### ISSUE TITLE
Atualização do Laravel

### ISSUE THREAD

**Issue by edersoares** [portabilis/i-educar#734]
Atualmente o i-Educar está na versão 6.0 (LTS) do Laravel que tem _Security Fixes_ até 03/09/2022, porém não há mais _Bug Fixes_.

É necessário atualizá-lo para a versão 7 e 8 seguindo seus guias de atualização oficiais.

- [Versão 7](https://laravel.com/docs/7.x/upgrade)
- [Versão 8](https://laravel.com/docs/8.x/upgrade)

**Comment by edersoares** [comment]
Atualização para o Laravel 7 na versão [2.5.0](https://github.com/portabilis/i-educar/releases/tag/2.5.0).

**Comment by JJDSNT** [comment]
Kudos! :)

https://github.com/portabilis/i-educar/releases/tag/2.6.0

**Comment by edersoares** [comment]
Atualização para o Laravel 8 na versão [2.6.0](https://github.com/portabilis/i-educar/releases/tag/2.6.0).
