### ISSUE TITLE
Utilizar imagens Docker baseado no Alpine

### ISSUE THREAD

**Issue by vinaocruz** [portabilis/i-educar#736]
Olá,

reparei que os _containers_ gerados possuem um tamanho considerável por utilizar as imagens padrão do nginx e php, baseado no Debian. Existe algum requisito no projeto que necessite utilizar esta base?

```
i-educar_nginx      latest              db0c021ea8c9        18 minutes ago      150MB
i-educar_php        latest              0fd16ef196d8        18 minutes ago      2.02GB
```

Minha ideia é alterar o Dockerfile para utilizar as imagens baseadas no alpine. O que acham?

**Comment by edersoares** [comment]
Hey, @vinaocruz!

Então, atualmente não damos suporte a imagens Docker para produção e a nossa imagem é um misto completo de ferramentas para auxiliar o desenvolvimento, é basicamente o que nós, desenvolvedores da @portabilis, utilizamos no dia a dia.

Sinta-se a vontade para auxiliar na contribuição de uma imagem melhor estruturada.

Só peço que valide as limitações quanto a algumas tecnologias necessárias, como:

- OpenJDK para emissão de relatórios.
- Cliente Postgres 9.5 para utilização de alguns recursos de restaurações e acesso ao banco de dados.
- Extensões e módulos PHP.

Abraço!

**Comment by vinaocruz** [comment]
Oi @edersoares, 

fiz as alterações de todas as imagens, incluindo o redis e postgres para utilizar também o alpine. A título de comparação com os _containers_ anteriores citados:
```
i-educar_nginx                     latest              ad6701261756        1 hours ago         24.1MB
i-educar_php                       latest              2fd9b1b985f1        38 seconds ago      735MB
```
Sobre as versões dos requisitos:

- Java

```
$docker-compose exec php java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (IcedTea 3.16.0) (Alpine 8.252.09-r0)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```
- Postgres Client
```
$ docker-compose exec php psql -V
psql (PostgreSQL) 9.5.13
```
- Módulos do PHP
```
$ docker-compose exec php php -m
[PHP Modules]
bcmath
Core
ctype
curl
date
dom
fileinfo
filter
ftp
gd
hash
iconv
json
libxml
mbstring
mysqlnd
openssl
pcntl
pcre
PDFlib
PDO
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
redis
Reflection
session
SimpleXML
sodium
SPL
sqlite3
standard
tokenizer
xdebug
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]
Xdebug
```

A cobertura dos testes são suficientes para eu possa validar estas alterações?

Abraço

**Comment by edersoares** [comment]
Excelente @vinaocruz! Muito bom mesmo!

A cobertura de testes não contempla todo os sistema, mas como disse, utilizamos Docker apenas para desenvolvimento no momento, abra uma pull request que faremos utilizaremos as novas imagens durante um período para garantir que não irá quebrar nada.

Obrigado, ótimo trabalho!

**Comment by vinaocruz** [comment]
Só uma observação, @edersoares: o redis estava com última versão estável. Não sei de quando foi definido, mas esse ano (em abril, se não me engano) foi lançado a versão 6. Mantive o latest, então assumirá essa versão. Caso o projeto esteja homologado com o redis 5, devemos atentar para essa mudança

Optei por um downgrade do alpine da versão 3.12 para 3.11, visando mais uma redução da imagem. A partir da 3.11 já é utilizada o Linux kernel 5.4 e não vi novas features na 3.12 que fossem extremamente necessárias para o projeto

**Comment by vinaocruz** [comment]
#737

**Comment by edersoares** [comment]
PRs aceitos https://github.com/portabilis/i-educar/pull/737 e https://github.com/portabilis/i-educar/pull/740 e o i-Educar está rodando com imagens Alpine.
