### ISSUE TITLE
Erro ao instalar usando o Composer 2.0

### ISSUE THREAD

**Issue by jrbarros** [portabilis/i-educar#738]
Erro ao instalar o projeto usando o composer 2.0

**AMBIENTE:**

- PHP 7.4
- Composer 2.0

Abri uma [PR](https://github.com/edersoares/laravel-plug-and-play/pull/6) na dependência do plugin que resolve o problema.

**Comment by edersoares** [comment]
@jrbarros está para sair o patch com a correção, mudamos o plugin para https://github.com/edersoares/composer-plug-and-play/ que resolve o problema de melhor forma :)

**Comment by jrbarros** [comment]
@edersoares  Massa! 

Quando essa mudança é que fechamos por definitivo  ?

**Comment by edersoares** [comment]
@jrbarros sim!

Foi feito o merge do teu PR https://github.com/edersoares/laravel-plug-and-play/pull/6 como forma paliativa até o merge de terceiro ser feito e/ou o patch com a correção sair.

**Comment by edersoares** [comment]
Corrigido na versão [2.5.0](https://github.com/portabilis/i-educar/releases/tag/2.5.0).
