### ISSUE TITLE
Menu Configurações / Configurações de sistema

### ISSUE THREAD

**Issue by flavio2209** [portabilis/i-educar#751]
**MENU:**

Configurações / Configurações de sistema

**DESCRIÇÃO:**

Configurações / Configurações de sistema, em bases novas e sem dados, as configurações não aparecem, porém nas bases antigas aparece todas a configurações.

**OBSERVAÇÕES:**

Palavras do Eder:
São configurações do Laravel e do próprio i-Educar que podem ser sobrescritas, nesta caso há realmente uma falha em não popular a tabela em novas instalações.

**AMBIENTE:**

- Plataforma utilizada ( instalação direta)
- Sistema operacional e versão (Ubuntu 18.04)
- Navegador e versão (Chrome 88)
- Outros detalhes importantes

**Comment by netocx** [comment]
Como faço para resolver sem fazer nova instalação?

**Comment by edersoares** [comment]
@netocx basta popular a tabela `settings` com as chaves do arquivo https://github.com/portabilis/i-educar/blob/2.6/config/legacy.php.

Exemplo: 

Para o ter a configuração do nome do app na tela:
https://github.com/portabilis/i-educar/blob/6513f475828c2ef8915312f92dce8e5cdbe3fd6a/config/legacy.php#L67-L68

Deve ser populada a tabela settings com a `key` = `legacy.app.name` e o value que desejar.

**Comment by msoares94** [comment]
Olá @edersoares, estou avaliando a issue e estou pensando na seguinte solução.

Tratar o erro adicionando os inserts na migration 2020_01_01_110000_create_settings_table.php

Pois pelo que analisei, após isso, existe algumas migrations que alteram a tabela settings, são elas:

2020_07_07_161425_create_menu_settings.php
2020_08_03_150015_create_settings_categories_table.php
2020_08_03_151235_populate_settings_categories_table.php
2020_08_03_163703_add_foreign_key_in_settings_table.php
2020_08_03_165637_update_categories_in_settings.php
2020_08_03_170501_atualiza_nomenclatura_dos_campos_da_tela_de_configuracoes.php
2020_08_04_143226_atualiza_tipo_dos_campos_da_tela_de_configuracoes.php
2020_10_12_232901_adiciona_campo_hint_configuracoes.php 

Além disso, pelo que pude entender, precisaria informar somente a "key" e "value", pois as demais migrations ajusta as colunas type, description e setting_category_id nos quais a key corresponde com o critério informado nas migrations:

public function up()
    {
        Schema::create('settings', function (Blueprint $table) {
            $table->increments('id');
            $table->string('key')->unique();
            $table->text('value')->nullable();
            $table->string('type')->default('string');
            $table->string('description')->nullable();
            $table->timestamps();
        });

        // Aqui iria o bloco de inserts, contendo somente a key e valor
        DB::table('public.settings')->insert(['key' => 'legacy.app.name', 'value' => 'i-Educar']);

A lista das key's eu obteria do resultado do comando:

php artisan tinker
config('legacy')

Qual a sua opnião?

**Comment by edersoares** [comment]
@marcosoliveirasoares94 exatamente isso, só precisa gerar a migration com um nome (data) que rode antes de `2020_08_03_150015_create_settings_categories_table`, exemplo ``2020_08_03_000000_populate_settings.php`.

**Comment by edersoares** [comment]
Resolvido na release [2.6.2](https://github.com/portabilis/i-educar/releases/tag/2.6.2).
