### ISSUE TITLE
Erro ao emitir "Ficha do servidor"

### ISSUE THREAD

**Issue by lrtuirng** [portabilis/i-educar#758]
Olá e obrigado por nos ajudar a tornar o i-Educar um projeto mais estável. Não esqueça de revisar o nosso
[guia de contribuição](https://github.com/portabilis/i-educar/blob/master/contributing.md) para saber melhor como colaborar com a nossa comunidade. Para reportar seu bug use o template abaixo:

**MENU:**

Servidores --> Documentos --> Ficha do Servidor 
**DESCRIÇÃO:**

Ao preencher os campos solicitados (Ano, Instituição, Escola e Servidor) e em seguida clicar em "Exibir" o sistema retorna a seguinte mensagem de erro:
"Erro no preenchimento do formulário"

![image](https://user-images.githubusercontent.com/82607586/114916228-f142be00-9dfa-11eb-8ff4-8f41c4c28b08.png)

**OBSERVAÇÕES:**

Ao marcar o check "Emitir em branco?" o campo "Servidor" não é desabilitado. Comportamento diferente, por exemplo, das versões 2.4.x que o formulário era emitido corretamente, inclusive desabilitando o campo quando o check era marcado.
 
**AMBIENTE:**

- Plataforma utilizada (instalação direta)
- Sistema operacional e versão (Ubuntu 16.04)
- Navegador e versão (Chrome 89)
- Outros detalhes importantes

**Comment by edersoares** [comment]
@lrtuirng com as últimas atualizações este erro foi corrigido?

**Comment by gilcimartec** [comment]
@edersoares testei a pouco essa funcionalidade no i-educar 2.7.5 e continua com o mesmo erro.

**Comment by edersoares** [comment]
@robertfsousa consegue analisá-la para nós por favor.

**Comment by netocx** [comment]
Na ficha de servidor a questão é com a referencia à tabela pmieducar.religions, na base de dados a tabela está com o nome ...pmieducar.religiao

troquei o nome da tabela e os campos, funcionou aqui

**Comment by edersoares** [comment]
Alguma migration não deve ter sido executada corretamente. Obrigado pelo retorno!

**Comment by robertfsousa** [comment]
> Na ficha de servidor a questão é com a referencia à tabela pmieducar.religions, na base de dados a tabela está com o nome ...pmieducar.religiao
> 
> troquei o nome da tabela e os campos, funcionou aqui

Realizei os testes com a versão limpa e está funcionando corretamente. A migration `2022_09_06_115338_update_religion_table` não deve sido executada.

**Comment by msoares94** [comment]
@robertfsousa acredito que precisamos entender qual é o nome correto, tendo em vista que temos o Model `./app/Models/Religion.php` apontando para `protected $table = 'pmieducar.religions';` 

Temos também o `Reports/StudentSheetReport.php` fazendo referência a religions.

Eu estou com esse problema porém não sei qual seria o nome correto a utilizar e o meu caso não esta faltando execução de migrations

![image](https://github.com/user-attachments/assets/f3b3b437-10d4-4393-93b0-ba96f06a5a34)
