### ISSUE TITLE
Erro 500: Tipos de Habilitação de curso

### ISSUE THREAD

**Issue by lrtuirng** [portabilis/i-educar#762]
Olá e obrigado por nos ajudar a tornar o i-Educar um projeto mais estável. Não esqueça de revisar o nosso
[guia de contribuição](https://github.com/portabilis/i-educar/blob/master/contributing.md) para saber melhor como colaborar com a nossa comunidade. Para reportar seu bug use o template abaixo:

**MENU:**

Escola --> Cadastros --> Tipos --> Cursos --> Tipos de habilitação 

**DESCRIÇÃO:**

Ao clicar em Tipos de habilitação (seguindo o caminho de menu listado acima) o sistema direciona para o "Erro 500"

**OBSERVAÇÕES:**

Segue logs do sistema:
UnexpectedValueException

The stream or file "/[instance_dir/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied 

**AMBIENTE:**
    

-     Plataforma utilizada (instalação direta)
-     i-Educar 2.6.0
-     Sistema operacional e versão (Ubuntu 16.04)
-     Navegador e versão (Chrome 89)

**Comment by edersoares** [comment]
@lrtuirng ainda não foi fechada a release, mas a correção já está disponível na branch `2.6`.

**Comment by edersoares** [comment]
Corrigido na versão [2.6.1](https://github.com/portabilis/i-educar/releases/tag/2.6.1).
