### ISSUE TITLE
Instalação de um comando

### ISSUE THREAD

**Issue by radaway** [portabilis/i-educar#904]
Fiz essa gravação de desktop onde instalo o i-educar digitando só um comando,também divulgo o comando para instalar a versão 2.8,aqui a gravação,obrigado pelo os fontes
https://youtu.be/ADiKwaopLus

**Comment by edersoares** [comment]
Obrigado pela contribuição @radaway, eu sugiro você criar um Gist https://gist.github.com/ com estes comandos, assim o pessoal pode contribuir com você e ir evoluindo a instalação, o que acha?

**Comment by radaway** [comment]
https://gist.github.com/radaway/aa00c20c842c44517374f2d989878a69
Radamés Kremer


Em seg., 24 de abr. de 2023 às 10:16, Eder Soares ***@***.***>
escreveu:

**Comment by edersoares** [comment]
A comunidade fica o recurso para testes e validações, obrigado @radaway!

**Comment by edersoares** [comment]
@radaway agora o i-Educar conta com uma manual de instalação em servidor https://github.com/portabilis/i-educar/blob/2.8/INSTALL.md#instala%C3%A7%C3%A3o-em-servidor-web caso queira atualizar seu script ou fazer sugestões.
